### ISSUE TITLE
Nested components - how do I use them?

### ISSUE THREAD

**Issue by jeznag** [skatejs/skatejs#1016]
I'm trying to get nested components working, e.g.
```<script src="./bundle.js"></script>
<cz-grid>
  <cz-grid-col cols=8>
    <cz-logo></cz-logo>
    <cz-headline>Sample headline</cz-headline>
    <cz-subheading>Sample subheading.</cz-headline>
  </cz-grid-col>
  <cz-grid-col cols=4>
    <img src="hotel-image.png" />
  </cz-grid-col>
</cz-grid>
```

```
import 'skatejs-web-components';
import { Component, h, prop } from 'skatejs';
import styles from '../css/grid.css';
class GridRow extends Component {

  renderCallback() {
    const nestedContents = this.innerHTML;
    return (
      <div>
        <style>
          {styles}
        </style>
        <div class='grid'>
          {nestedContents}
        </div>
      </div>
    );
  }
}

customElements.define('cz-grid-row', GridRow);
```

The elements don't nest though. 
![image](https://cloud.githubusercontent.com/assets/1034890/22010046/d9945150-dcda-11e6-85d6-3e83814e03d1.png)

I tried putting {this.innerHTML} inside the cz-grid component's renderCallback but innerHTML comes up as blank.
![image](https://cloud.githubusercontent.com/assets/1034890/22010108/410675b6-dcdb-11e6-8b11-63900de07506.png)

**Comment by treshugart** [comment]
Instead of using `innerHTML`, you should use the spec'd `<slot />` element instead. Where you've tried to render `nestedContents`, you should instead put `<slot />` and things will just work. For more information on Shadow DOM v1 and the slot element, Eric Bidelman wrote a great article over at https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom. I'd link you to the spec, but it's a pretty dry read.

**Comment by treshugart** [comment]
Have a look at http://www.webpackbin.com/NJJqrRULf for a simple example of this. We need to add some docs for the slot element, linking off to other references most likely. Theres an open issue for this https://github.com/skatejs/skatejs/issues/860.
