### ISSUE TITLE
Docs are unclear on CSS style encapsulation

### ISSUE THREAD

**Issue by 0xR** [skatejs/skatejs#1027]
The docs say here: https://skatejs.gitbooks.io/skatejs/content/docs/recipes/#styling-components

```
If you want to ensure your styles are encapsulated even if using a polyfill, you can use something like CSS Modules.
```

This reads to me that ShadyCSS is not working with SkateJS. I don't know whether this is true, but I can't seem to get it work.

**Comment by Hotell** [comment]
That is correct. ShadyCss is the culprit here though, because they force you to use `<template id="hello">`. 

Skate doesn't need this(template element) because it uses IncrementalDOM for "templating". ShadyCSS is for me personaly kind of a trap from Google Polymer engineers :D, because it is suited to work solely with Polymer. I've tried to use it with raw WC but encapsulation didn't work...

**Comment by 0xR** [comment]
Ok I did further digging and I concluded that there is no CSS encapsulation with skatejs in browser which do not support shadow dom. The polymer team have not officially released either ShadyDOM or ShadyCSS. Note the github references in the [skatejs polyfill](https://github.com/skatejs/web-components/blob/master/package.json).

Further more using ShadyCSS requires a lot [manually setup](https://github.com/webcomponents/shadycss#usage) to get working. This is also not in SkateJS. Indeed it does require using HTML templates which are not used in SkateJS.

The most confusing part is that ShadyCSS is [recommended](https://github.com/skatejs/skatejs#browser-support) by SkateJS, but it will never work.

**Comment by 0xR** [comment]
ShadyCSS does seem to add additional CSS classes to DOM node which have a CSS class: `<div class="counter"></div>` becomes `<div class="counter style-scope my-counter"></div>`. You could in theory use `.counter.style-scope.my-counter` manually in your component style tag. Also you can use the `<custom-style>` tag to do avoid styles leaking into your component:

```
<custom-style>
  <style>
  .counter {
    color: blue;
  }
  </style>
</custom-style>
```
Turns into:
```
<custom-style>
  <style>
  .counter:not(.style-scope) {
    color: blue;
  }
  </style>
</custom-style>
```

**Comment by Hotell** [comment]
> The polymer team have not officially released either ShadyDOM or ShadyCSS. 
Well the main contributor is https://github.com/azakus ( Googler ) that speaks for itself anyway 

> Note the github references in the skatejs polyfill.

Yup that should go away. I've already reported it.  https://github.com/skatejs/skatejs/issues/950#issuecomment-265683435

**Comment by Hotell** [comment]
> .counter.style-scope.my-counter

that would not work in browsers with native ShadowDOM support

> Also you can use the `<custom-style>` tag to do avoid styles leaking into your component:

doesn't work. there is runtime error when using custom-style element

**Comment by 0xR** [comment]
You're right it wouldn't work in browser with native ShadowDOM>

I did have the `custom-style` tag working in Firefox. Could be that chrome would give errors.

In summary you just can't use any shadow dom features and might as well only use the custom elements polyfill. That would also decrease your bundle size.

As for ShadyDOM it is extracted from polymer itself: https://www.polymer-project.org/1.0/blog/2016-12-21-polymer-2.0-update.html . So it makes sense that is relies on HTML templates. It would be nice if there was a prepareElement method which works on any dom element and transpiles its containing CSS.

**Comment by Hotell** [comment]
> In summary you just can't use any shadow dom features and might as well only use the custom elements polyfill. That would also decrease your bundle size.

that is not true. Don't forget that shadowDOM === scoped styles + projection via slots

If you don't include shadowDOM polyfill to non native browsers, projection wont work. Because projection is a very important part of component API ( Composition ) skate depends on it when it creates "shadowRoots" https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L363.

> It would be nice if there was a prepareElement method which works on any dom element and transpiles its containing CSS.

exactly, can you rise issue on their repo pls? 

thanks !

**Comment by treshugart** [comment]
I tried getting it working awhile back: https://github.com/treshugart/skatejs-examples/blob/master/index.js. I just updated the lifecycles to match latest Skate so you can try it but nothing else has changed there.

I tried using their imperative code example to get at the prepared `<style>` within the `<template>` but It looks as if `prepareTemplate()` removes it from the actual template node for some reason. No way to get the prepared CSS to insert into `render()`. If we can get at the prepared style element somehow, then we can insert its text content or into a skipped node.

**Comment by Hotell** [comment]
>I tried using their imperative code example to get at the prepared `<style>` within the `<template>` but It looks as if prepareTemplate() removes it from the actual template node for some reason. No way to get the prepared CSS to insert into render(). If we can get at the prepared style element somehow, then we can insert its text content or into a skipped node.

So it works and doesn't. Here is why and how:

when `prepareTemplate(templateRef, elementName)` is called, they:
- extract and remove `<style></style>` from `templateRef` and create transformed `css` and assign it back to `templateRef._style` property and append new transformed styles to `document.head`
- traverse all children nodes ( expect `<style>` ) of `templateRef.content` and add them scoped class names ( `style-scoped`, `<your-element-name>` ) , so they can be leveraged afterwards ( with `<custom-styles>` and our shadowDom styles ( in case with skate, there are none, because we are just creating dummy template )

Detailed call stack:
```
prepareTemplate(templateRef, elementName)
-> `_gatherStyles` -> removes `<style>` from `templateRef` and save content to local variable

-> `StyleTransformer#dom` -> traverses all `template.content` nodes and applies to them scoped classNames ( `style-scoped`, `<your-element-name>` )

-> `_generateStaticStyle`
  --> `applyCss`
  --> `createScopeStyle`
  --> `applyStyle` (appends transformed style with `scope="<your-element-name>" attribute to `document.head`)
 --> save transformed styles to `template._style` prop
```

then `applyStyle()` is called:
-

**Comment by treshugart** [comment]
Thanks for the detailed investigation, @Hotell. I'll admit I didn't have much time to look that deep into it. Much appreciated.

It would be nice to get @justinfagnani's thoughts on this. It'd be nice if there was a standard way that any library that doesn't opt to use <template> could use this.

**Comment by justinfagnani** [comment]
I'm not an expert on ShadyCSS, but I can see why it's done this way. The idea is to prepares the styles and template only once so that at stamping time there's no overhead to fixing up styles. To use this with a purely imperative API you'd have to give ShadyCSS a stylesheet, and receive back some type of mapping that you could pass all `class` attribute values to fix up as you write out DOM. The underlying transformation of styles and classes would be the same.

@treshugart ShadyCSS attempts not to make styles private, but to give them the same scoping rules as ShadowDOM. This means correct upper and lower bounds, and CSS custom variable inherit even though shadow boundaries. ShadyCSS also implements the `@apply` shim.

@azakus could tell you more.

**Comment by camagu** [comment]
How about a skatejs specific solution based on ShadyCSS?

A wrapper for `skatejs.h` could be used to inject the extra classes as each element is built, while a pure function could be used to transform the CSS string or object. Pollyfills for custom attributes and apply rules could be written separately as functions which transform the CSS which can be used at render time.

I built a [proof of concept](https://plnkr.co/edit/lk2VXyPgo805CZ0qh5QN?p=info) to explore this solution.

**Comment by alexlafroscia** [comment]
I was able to hack together a base class for "styled elements" that sort-of works. It's a definite "work in progress" and has a few restraints: you can only style elements with classes (I'm hoping to fix this).  On the plus side, the custom transformations no-op when there is real "shadow DOM" support.

https://gist.github.com/alexlafroscia/f0b2493c1abebd28a22d7164832ddaa7

I'll update the gist as my implementation evolves, but this seems to be working to enable scoped CSS in Safari, at least.

**Comment by treshugart** [comment]
Hmm, this appears to work perfectly:

```js
/** @jsx h */

import 'skatejs-web-components';
import { Component, define, h } from 'skatejs';

const { ShadyCSS } = window;
const templates = {};

function style (elem, css) {
  const template = templates[css] = templates[css] || (templates[css] = document.createElement('template'));
  template.innerHTML = `<style>${css}</style>`;
  console.log(template);
  ShadyCSS.prepareTemplate(template, elem.localName);
  return <style>{css}</style>;
}

const Test = define(class extends Component {
  renderCallback () {
    return [
      style(this, `
        :host {
          background-color: black;
          color: white;
          display: block;
          padding: 10px;
        }
      `),
      <div>test</div>
    ];
  }
});
```

**Comment by camagu** [comment]
@treshugart I think the shadow styles bleed outside of the component. When adding a `div` outside of the component (e.g. as a sibling) it's font color will be white as well.

It seems that `ShadyCSS.prepareTemplate` adds the scoped style rules to the `head` element while the component's style element includes the raw rules (that's why they bleed). If the return value of the `style` function is changed to an empty string the rules for `div` will not be applied.

It surprises me though that the scope classes are being applied to the `slot` wrapper (it look something like `<span class="slot style-scope x-54f87a3a">`).

Although it violates the shady css encapsulation, I think this can be solved by somehow adding the scope classes inside the `h` function.

**Comment by treshugart** [comment]
@camagu

> It surprises me though that the scope classes are being applied to the slot wrapper (it look something like <span class="slot style-scope x-54f87a3a">).

It does this for every element that you target in your polyfilled CSS.

In testing some stuff from your comment, it looks as if only `:host` and `.classname` selectors work in ShadyCSS. Element, id and attribute selectors don't seem to work at all.

It also turns out that if you use class selectors, styles don't bleed at all. That said, I've updated the example to only use ShadyCSS if it needs to, so it doesn't create an unnecessary template.

```js
/** @jsx h */

import 'skatejs-web-components';
import { Component, define, h } from 'skatejs';

const { HTMLElement } = window;
const { attachShadow } = HTMLElement.prototype;
const { ShadyCSS } = window;
const $template = Symbol();
const nativeShadowDomSupport = attachShadow && attachShadow.toString().indexOf('native code') > -1;

function style (elem, css) {
  if (nativeShadowDomSupport) {
    return <style>{css}</style>;
  }
  const template = elem[$template] || (elem[$template] = document.createElement('template'));
  template.innerHTML = `<style>${css}</style>`;
  ShadyCSS.prepareTemplate(template, elem.localName);
}

define(class extends Component {
  static is = 'x-test'
  renderCallback () {
    return [
      style(this, `
        :host {
          background-color: black;
          display: block;
          padding: 10px;
        }

        .span {
          color: white;
        }

        .slot ::slotted(*) {
          color: red;
        }
      `),
      <div>
        <span class="span">shadow </span>
        <span class="slot"><slot /></span>
      </div>
    ];
  }
});

document.body.innerHTML = `
  <x-test><span>light</span></x-test>
  <div>outside</div>
`;
```

**Comment by camagu** [comment]
@treshugart nice!

Working fine in FF, even rules on the `div` element are being applied `¯\_(ツ)_/¯`

Seems to work fine in EDGE as well, but it stops working for me when introducing custom properties.  :/

**Comment by alexlafroscia** [comment]
I was able to get an implementation of my subclass working with the approach @treshugart took up there. Will update my gist tomorrow, it works really well and avoids the private API usage I needed with my initial approach.

Thanks @treshugart!

**Comment by treshugart** [comment]
@camagu there's some extra [imperative stuff](https://github.com/webcomponents/shadycss#usage) you need to do to get custom properties working but I'm not sure exactly what that is yet.

@alexlafroscia did you get custom properties working? Glad to hear you got it working. Let me know if you have any questions. I would like to offer an official mixin for this at some point, but need to work out the details of where we might put it. Raised an issue to figure this out in #1079.

**Comment by alexlafroscia** [comment]
Hmm, what do you mean by "custom properties"?

**Comment by treshugart** [comment]
@alexlafroscia web components as a whole have a questionable story for that. However, it's worth testing the claims prior to making assertions. Do you have any data proving web components aren't good for SEO?

**Comment by treshugart** [comment]
@alexlafroscia see also https://gist.github.com/justinfagnani/936791248120749ff1f8188f1f4064d9

**Comment by alexlafroscia** [comment]
> Do you have any data proving web components aren't good for SEO?

Not personally, but another team member of mine said he saw a conversation somewhere about the fact that crawlers aren't able to get down into the ShadowDOM in order to detect stuff in there that might be SEO-relevant. And even if Google can, we need to support all of them

**Comment by treshugart** [comment]
Sounds like your team member should prove their claim.

**Comment by alexlafroscia** [comment]
After just a brief search on Google, it seem like he's right...

This Treehouse blog post mentions the fact that search engines do not inspect the Shadow DOM, for example
http://blog.teamtreehouse.com/working-with-shadow-dom

I've found a number of other blog posts around the web that say the same thing. While I'm skeptical of accepting this as fact just based on these blog posts, I also know that search engines typically don't state exactly what they do (or do not) take into consideration. Based on that, if there's a chance they don't look into ShadowDOM trees to inspect links, then my team needs some way to serve up the content of a custom element without the Shadow DOM to search engines.

**Comment by treshugart** [comment]
That's fair. I did some testing on GoogleBot for https://skatejs.github.io. It complained there was no semantic markup and only saw `<sk-app />` (because that's my app component). However, it successfully rendered the app.

Can we take the SEO discussion over to: #573?

**Comment by alexlafroscia** [comment]
Yeah, good idea

**Comment by alexlafroscia** [comment]
Just to follow up on the style stuff here... I've found that the mixin that I made doesn't actually work reliably.  I've switched to the code snippet that @treshugart posted above and it works much more reliably on the browsers without native shadow DOM support.

**Comment by fredyagomez** [comment]
@treshugart Above you mentioned: 

"@alexlafroscia did you get custom properties working? Let me know if you have any questions. I would like to offer an official mixin for this at some point, but need to work out the details of where we might put it. Raised an issue to figure this out in #1079."

Is there any solution/link I can see for this official mixin implementation in SkateJS?

**Comment by alexlafroscia** [comment]
AFAIK there's still no "official" mixin at this time. I've been using [this helper function](https://github.com/skatejs/generator-skatejs/blob/master/generators/app/templates/src/util/style.js) and it works very well.
