### ISSUE TITLE
Using slots with react 15

### ISSUE THREAD

**Issue by tauren** [skatejs/skatejs#1096]
I'm trying to build a CE that uses slots and render it in a React app.  This fails:

```
warning.js:36 Warning: Unknown prop `slot` on <h1> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

It appears there was a [PR](https://github.com/facebook/react/pull/8061) to resolve this specific issue, but it won't land until React 16. In the meantime, is there a workaround I can use to make things work?

Here is the CE:

```
/** @jsx h */
import { Component, h, define } from 'skatejs';
export default class Example extends Component {
  static is = 'u-example'
  static get props() {
    return {}
  }
  renderCallback() {
    return [
      <style></style>,
      <div>
        <header><slot name="header"/></header>
        <main><slot name="body"/></main>
        <footer><slot name="footer" /></footer>
      </div>
    ];
  }
}
define(Example);
```

And here is a React component that uses it:

```
import React from 'react';
import '../Example';

export default function ShowExample () {
  return (
    <u-example>
      <h1 slot="header">This is the header</h1>
      <div slot="body">This is the body</div>
      <span slot="footer">This is the footer</span>
    </u-example>
  )
}
```

Perhaps `reactify(Example)` would help? But wouldn't I still run into the same problem with `slot` not being allowed on `h1`, `div`, and `span` elements.

What pattern or techniques would make this work with React 15.x? Or is there no solution?

**Comment by Hotell** [comment]
Hey @tauren

Right that PR was done by me. 

I suppose those warnings are only in development mode, but it's a showstopper for our team to use react with WC. 

Maybe @treshugart has some solution as they are using React with WC AFAIR.

In the meantime checkout https://github.com/skatejs/val

**Comment by treshugart** [comment]
I recall us having to do something, but I can't remember exactly what it was. The https://github.com/skatejs/val project will get you much further, anyways, as it supports any attribute or event, not just the ones they've put into their inclusion list. I'd recommend using that as it will enable seamless integration.

For what it's worth, though, if you have a choice, Preact will serve you better in terms of size, performance and DOM integration without having to use a wrapper.

I'd do a bit more searching, I know there was a way, even if it was a bit hacky. You may also be able to do something like `ref={e => e.setAttribute('slot', 'some-slot')}`.

**Comment by Hotell** [comment]
yup exactly as @treshugart  said

At work we have following stack ( works like charm btw ;) ):
- Preact for data binding and application glue
- Redux  for data management
- Redux-observable for side effects
- Jest for snapshot testing and unit testing ( YES with preact )
- Skate for reusable UI components


Only main reason for using React at this time would be if we had shared codebase for ReactNative and React apps.

**Comment by tauren** [comment]
Thanks for all the suggestions. I'll take a closer look at Preact. And this is the first I've heard or `skakejs/val`, but I'll look at it too. Can you guys answer a couple questions?

* Do I understand correctly that Preact is a drop-in replacement for React? 
* If I use Preact, would I not need `val`?
* If I use Preact, would I no longer need to `reactify()` components?
* It isn't quite clear to me the relationships or the benefits for using the various tools. Is there a good article or blog post that explains things? 

Also, @Hotell, your stack is very close to mine. I'm obviously using React not Preact, but the rest is essentially the same. I've just started migrating code from redux-sagas to redux-observables. Another person on the team thinks we should consider mobx instead of redux. And another team is using react-native to build an android version of the web-app my team is building. Right now they are separate code bases, but we'd like to eventually share code.

Lastly, I solved my immediate problem by writing a simple webpack loader for `/HTMLDOMPropertyConfig\.js$/`:

```
module.exports = function patchReactWebpackLoader(source) {
  return source.replace(/Properties: {/, 'Properties: {\n    slot:0,')
}
```

**Comment by treshugart** [comment]
> Do I understand correctly that Preact is a drop-in replacement for React?

@developit is best to answer this. It's ES2015 API is compatible and there's also [preact-compat](https://github.com/developit/preact-compat).

> If I use Preact, would I not need val?

Not for most things. It brings consistency across the popular VDOM libs if you want *full* control over the DOM, like if you want to explicitly set an attribute or property, rather than rely on the internal heuristics of the VDOM library in question. For example, if you want to set a property on a DOM element, and it hasn't been upgraded to a custom element yet, Preact won't set it as a property because it won't be `in` the `prototype` yet (IIRC).

> If I use Preact, would I no longer need to reactify() components?

As long as you declare them by their custom element name. For example `<custom-element />` rather than trying to use them like a constructor: `<CustomElement />`. However, `val` is a good candidate here as it allows you to pass a custom element constructor directly without reactification and you get the consistency it offers. It's likely to supersede `react-integration` in the near future.

> It isn't quite clear to me the relationships or the benefits for using the various tools. Is there a good article or blog post that explains things?

My spare time is limited and mostly dedicated to answering questions and maintaining Skate core. It's pretty clear there's a need for this. If you have anything specific that you want addressed here, I'm more than happy to answer at length.

**Comment by developit** [comment]
@tauren it sounds like you're using react as a glue for WC's. Since that's (mostly?) first-party code that you're writing, you'd probably be able to switch to `preact` (without preact-compat) via simple aliases and never really notice ([here's the couple important differences](https://preactjs.com/guide/differences-to-react#what-s-missing-)).

I think the main reason @Hotell suggested looking at Preact is that it doesn't have any whitelists, so it'll never tell you "we don't think h1 has a `slot` attribute sorry".

**Comment by Hotell** [comment]
> I think the main reason @Hotell suggested looking at Preact is that it doesn't have any whitelists, so it'll never tell you "sorry, we don't think h1 supports the slot attribute".

Not just that ofc
- lighter , faster, stronger
- works with WC's ( when registering events  which they emit or setting props ) - React ignores that because it is unknown element

Following is not possible with React:

```ts
import {h,Component} from 'preact'

type State = {userName:string}
class App extends Component<any,State>{
  state = {
    userName: 'PreactSuperman'
  }
  handleNameChange = (event: CustomEvent) => {
     const {value} = event.detail;
     this.setState({userName: value});
  }

  render(){
   const {userName} = this.state;
   return (
    <div>
      <form>
         <label>Name:</label>
         <my-input onChange={this.handleNameChange} value={userName} />
      </form>
    </div>
   )
  }
}
```

**Comment by treshugart** [comment]
I'm going to close this for now. Please feel free to continue the discussion if necessary, but it doesn't seem like there's anything actionable.

**Comment by morewry** [comment]
I came across this because I'm prototyping web components using skatejs and when I got to the point of prototyping an integration with React, I got the error,

```
Warning: Unknown prop `slot` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (at App.js:14)
    in gcui-site (at App.js:12)
    in App (at index.js:7)
```

Reading the posts on this issue did not clear up for me how to fix it. 

- Switching to another framework is not a solution, since we have people who use React and the point of the prototype is to demonstrate that they can integrate web components (if, in fact, they can).
- I am aware of https://github.com/webcomponents/react-integration, but had gotten the impression it's not required. My strong preference would be to _not_ convert the web components in at least my first prototype.

I have never previously used React, so I'm not very clear on what is being said here. React restricts what HTML attributes you can use? React specifically bans `slot` on `h1`, `div`, and `span` (what about `h2`)? I'd have to add another dependency to my skatejs web components with slots in order for them to be utilized by React users?

**Comment by treshugart** [comment]
> React restricts what HTML attributes you can use and doesn't include all the valid ones? For goodness' sake, why? 

React has an inclusion list of valid attributes. You can see @Hotell's PR is simply to include it: https://github.com/facebook/react/pull/8061/files. What version are you using? I can't tell if it's been released or not yet, but it looks as if it hasn't (which is odd because it's pretty old). @Hotell can you confirm if it has been or not?

> I'd have to add another dependency to my skatejs web components with slots in order for them to be utilized by React users?

It's likely that https://github.com/skatejs/val would make your life easier because it completely subverts React's internal checks.

I'm really sorry you have to do this, but unfortunately there's not really much we can do but try and work around the poor behaviour.

**Comment by morewry** [comment]
It's nothing to apologize for. I'm just not clear on what the options are. 

I can look at val, though that begs the question of whether val should be a dependency of a published component, or of the app consuming the component. If the component, what are the ramifications of val for anyone using vanilla JS or Angular?

Are those all of the work around options: val and reactify? Above, you mentioned `ref={e => e.setAttribute('slot', 'some-slot')}`; is that some React thing I can look up?

**Comment by treshugart** [comment]
> If the component, what are the ramifications of val for anyone using vanilla JS or Angular?

For Vanilla JS, nothing at all. You set props, attributes and events as you see fit. You have full control.

With angular, I think you're still okay. Depending on if it's 1 or 2, your options will be different. I think with Angular 1, it sets attributes, so if you need complex data structures you need to deserialise from the attribute to the prop, or somehow find a way to make it set props. @Hotell can most probably give you a good option for 1. For 2, I'm fairly certain you can choose to set props or attributes based on the syntax that you use.

> Are those all of the work around options: val and reactify?

As you say, you can use `ref`. This is actually what `val` uses internally to bypass their algorithms. To take `ref` usage a step further you could have a utility to get around your issue:

```js
function slot (name = '') {
  return { ref: e => e.setAttribute('slot', name) };
}

<div ...slot('my-slot') />
```

That might work for now. However, it's likely your consumers will run into issues when trying to pass complex data structures to your components as properties. For this, it's best for your consumers to use `val`. It's trivial to use and it only needs to be used if they encounter the issues that it solves.

> For val and reactify, as the author, what is your recommendation? Should a component author use them as dependencies and distribute wrapped / converted versions, or would you advise leaving up to the consumer whether and how to use them?

Definitely the responsibility of the consumer. They may not like this, but they've chosen to use something that doesn't integrate well with standard DOM practices.

In terms of not using React, Preact is a mighty fine solution and is many cases is a drop-in replacement for React, and it integrates perfectly.

**Comment by morewry** [comment]
Great! That gives me plenty to mull over and try out. Thanks very much for
your help and input, it's deeply appreciated.

**Comment by treshugart** [comment]
@morewry No worries at all. I just updated my last comment, in case you didn't see it.

**Comment by Hotell** [comment]
> @Hotell can most probably give you a good option for 1. For 2, I'm fairly certain you can choose to set props or attributes based on the syntax that you use.

So for ng1 you can create a directive or something that will access the attributes and will set them to CE props. It's just DOM. 

ng2 Works likes charm by default - you use the same syntax as with ng2 component () [] - just import CustomElements schema to root app module

**Comment by Hotell** [comment]
> React has an inclusion list of valid attributes. You can see @Hotell's PR is simply to add it. What version are you using? I can't tell if it's been released or not yet, but it looks as if it hasn't (which is odd because it's pretty old). @Hotell can you confirm if it has been or not?

I'm kinda confused about Facebook releases. It was merged long time ago but I guess it will be shipped with React 16, ehm ehm....

**Comment by Hotell** [comment]
> For val and reactify, as the author, what is your recommendation? Should a component author use them as dependencies and distribute wrapped / converted versions, or would you advise leaving up to the consumer whether and how to use them?

I would definitely ship 2 versions 
- pure WC with skate
- WC with skate and val 

So consumers which are not using artificial tech like React are not penalized by payload size etc

**Comment by treshugart** [comment]
> I would definitely ship 2 versions

The only issue with this is you have to add an additional export that wraps React's `createElement`. It's probably simpler for the React consumers to simply create their own wrapped `createElement` and only use it where necessary. WDYT?

**Comment by tauren** [comment]
@morewry I ended up using Preact for my application so it was easier to integrate with web components. However, if I remember correctly, I was also able to get things working with React by doing this:

1. Using the custom webpack plugin in [my comment above](https://github.com/skatejs/skatejs/issues/1096#issuecomment-285275280). This monkeypatches the React file that defines the whitelist, adding `slot` as a valid attribute.

2. Using `@skatejs/val` to pass events, attributes, and props. You'll have to wrap your attributes and events in an object. For instance: `<my-button events={{ click: ... }}>` instead of `<my-button on-click={...}>`.

There may have been other things I did as well, it was a fair amount of effort. Honestly, the whole experience getting web components working within React has really soured my opinion of React.

**Comment by morewry** [comment]
> I would definitely ship 2 versions

@Hotell That's what I was thinking, potentially. Although, in fact, it seems like I could end up distributing more versions than that, what with also needing to support UMD (without burdening users to add or alter pipelines to transpile dependencies) as well as ES Modules.

> It's probably simpler for the React consumers to simply create their own wrapped createElement and only use it where necessary.

@treshugart And especially as they use React and I haven't (until this very moment, anyway) they'd be more versed in what, why, and how to best integrate with their own code. 

OTOH, it seems to me I'll shortly get to the point where I'll know in advance based on how the web component I implemented works (e.g. does it have slots? props? events?), so it'd be predictable for me as author and potentially trial-and-error for users. Though good documentation on my end would help there. Worth considering.

On which note, I found the recipes portion of the SkateJS docs very useful and it seems like some of this conversation would be useful there. Do you have any contribution guidelines for docs in case I stumble upon the motivation to write some snippets derived from my continued experience?

> There may have been other things I did as well, it was a fair amount of effort. Honestly, the whole experience getting web components working within React has really soured my opinion of React.

@tauren Interesting! Despite having my own related reasons for being a bit sour too, I'm actually pretty surprised, because I coulda sworn I'd heard there was a series of PRs that had fixed low hanging fruit web component compatibility issues (into which description whitelisting slot fits); React's docs certainly imply so. But, then, @Hotell's PR _is_ from 7 months ago.

**Comment by treshugart** [comment]
@morewry 

> Do you have any contribution guidelines for docs in case I stumble upon the motivation to write some snippets derived from my continued experience?

Just what's here: https://github.com/skatejs/skatejs/blob/master/CONTRIBUTING.md. @Hotell is making some improvements here: https://github.com/skatejs/skatejs/pull/1118/files#diff-6a3371457528722a734f3c51d9238c13.

But feel free to open a PR. Our process is pretty lightweight ATM, so feedback is definitely welcome.
