### ISSUE TITLE
Not possible to include stylesheet via link element in renderCallback

### ISSUE THREAD

**Issue by RevillWeb** [skatejs/skatejs#1139]
Hi,

Could anybody give me some pointers as to how I could resolve the following issue.

Basically I am looking at injecting a stylesheet into a component using the link element. When I do this with a SkateJS component I get the following error:

```
HTML element <link> is ignored in shadow tree.
```

I can only assume that this error is because the component isn't connected yet. I come to this conclusion because, for a link[rel="stylesheet"] to work in the Shadow Root the element has to already be connected, as far as I understand anyway.

So my understanding must be lacking in what stage of the component lifecycle the renderCallback is called. Any help in figuring out how to get a link element to work in the example below would be greatly appreciated. 

```
const sSym = Symbol();

class SkateCounter extends Component {
    static get props () {
        return {
            count: prop.number({ attribute: true })
        };
    }
    constructor() {
        super();
    }
    connectedCallback() {
        super.connectedCallback();
        this[sSym] = setInterval(() => ++this.count, 1000);
    }
    disconnectedCallback() {
        super.disconnectedCallback();
        clearInterval(this[sSym]);
    }
    renderCallback(props) {
        return [
            h("style", `
                :host {
                  background-color: var(--host-bg, black);
                  display: block;
                  padding: 10px;
                  color: #CCC;
                }

                span {
                  color: white;
                }

                .slot ::slotted(*) {
                  color: red;
                }
            `),
            h("link", { "rel": "stylesheet", "href": "style.css" }),
            h("div", { class: "container" }, "Skate Count ", h("span", this.count), ".")
        ];
    }
}

customElements.define('skate-counter', SkateCounter);
```
I have tried setting a `_connected` flag in the `connectedCallback` and only including the link element when this is `true` but the `_connected` flag always returns `true` from the `renderCallback`. I've also checked that adding the link element manually to the Shadow Root works but obviously gets removed once the `renderCallback` gets executed again.

I've also implemented the same component using vanilla JavaScript (below) without any issues at all providing that this should be possible.

```
const vSym = Symbol();

customElements.define('vanilla-counter', class extends HTMLElement {

    constructor() {
        super();
        const $template = document.createElement("template");
        $template.innerHTML = `
            <style>
                :host {
                  background-color: var(--host-bg, black);
                  display: block;
                  padding: 10px;
                  color: #CCC;
                }

                span {
                  color: white;
                }

                .slot ::slotted(*) {
                  color: red;
                }
            </style>
            <link rel="stylesheet" href="style.css" /> 
            <div class="container">
                <p>Vanilla Count <span id="countValue"></span>.</p>
            </div>
        `;
        this._$template = document.importNode($template.content, true);
        this._$countValue = this._$template.querySelector("#countValue");
        this.attachShadow({mode: "open"});
    }

    connectedCallback () {
        this.shadowRoot.appendChild(this._$template);
        this[vSym] = setInterval(() => {
            ++this.count;
            this._render();
        }, 1000);
    }
    disconnectedCallback () {
        clearInterval(this[vSym]);
    }
    _render () {
        this._$countValue.innerText = this.count;
    }
    static get observedAttributes() {
        return ["count"];
    }
    attributeChangedCallback(name, oldValue, newValue) {
        if (oldValue !== newValue) {
            this.count = parseInt(newValue);
            this._render();
        }
    }
});
```

Thank you very much!

Leon.

**Comment by treshugart** [comment]
Hey @RevillWeb, the `renderCallback()` is called for the first time *after* the element is connected to the document. I think you're seeing this error because `<link />` elements are considered inert in the shadow tree (prettu sure this is still accurate). There's a little more information [in the spec](https://www.w3.org/TR/shadow-dom/#inertness-of-html-elements-in-a-shadow-tree).

I know @matthewrobb was looking into this quite extensively. Maybe he can help more than I can here.

FWIW, I prefer CSS in JS for most things and generally opt to use something like [Glamor](https://github.com/threepointone/glamor) for most things. Either that or simply putting your CSS in a template literal. You can do this in the same file, or a different file and include it where necessary. It's been asked a few times, but browsers that support Shadow DOM will optimise the duplicated CSS in the document tree.

**Comment by RevillWeb** [comment]
Hi Trey, thanks for the quick response. The information around the use of link in shadow root does appear to be a little confusing but as far as I can tell it should (and does at least in Chrome - see vanilla example above): https://github.com/w3c/webcomponents/issues/530

The reason I am including a style sheet via the link element in this way is probably an edge case for most people, I need to allow component users to be able to specify an overriding style sheet to a component at run time. But I'd really like to understand why it doesn't work with a SkateJS component but does work perfectly fine in my vanilla example.

Thank you!

**Comment by treshugart** [comment]
I did some investigation and found that this happens due to the way Incremental DOM patches the DOM. When it creates your link element, it does the following in this exact order:

1. Creates the element (via `document.createElement()`)
2. Appends the link to the `shadowRoot`
3. Sets the `rel` attribute
4. Sets the `href` attribute

If you use a `template` or `innerHTML`, everything is applied at once, and works without warning. So it seems to have to do with the fact that either `rel` or `href` is added after it is appended to the `shadowRoot`.

I've created a bin for it: https://www.webpackbin.com/bins/-Ki1BCPBpT1He_bjrmBf. Chrome actually crashes with that, so load it up in Safari to see it work, or to modify it.

At the end of the day, it seems using `link` in a shadow root is - at best- buggy, and the spec is fairly clear about the behaviour. While Chrome seems to work under certain circumstances, and Safari works in all that I've tried, I wouldn't rely on it.

For your use case, if you want to provide style overrides, you can use a prop on your element that you just add to your style template literal when rendering your component.

**Comment by matthewrobb** [comment]
The quickest suggestion I can offer is to use:
```html
<style>@import url(...)</style>
```
There are a plethora of performance concerns and an even greater number of ways to go about addressing most of them. My conclusion has come around to feeling very unsure that I want to do any of this. Any stylesheet that wasn't written with the intent of being in a shadow root will have gotchas. @font-face won't do anything unless also included in the root document styles and the same goes for keyframe animations. One of the biggest problems I have run into is with style frameworks like bootstrap applying base styling for html and body and in bootstrap@4 everything moves to be rem unit based and that is a total nightmare.

**Comment by matthewrobb** [comment]
@treshugart honestly someone in the standards group needs to consider the portability concerns of stylesheets that might be in a root document or a shadow because rem is really strange and while :root is a nice idea it doesn't port because there are different reasons at different times to apply styles to the html element vs the body element and those decisions do not have a 1:1 parellel in a shadow root.

**Comment by RevillWeb** [comment]
Thank you @treshugart for looking into that. I can understand why that is the cause, since a link element without a `rel="stylesheet"` should be ignored, I would have expected it to get "upgraded" though. I'd not really given using a property to specify additional style a thought, I'll investigate to see if it fits my use case.

Thanks @matthewrobb for the added comments, I was hoping to avoid @import due to the obvious performance concerns but its looking more likely that i'll need to. I really hope we can discover some better ways of achieving this type of functionality with the Shadow DOM soon.

I appreciate your time, Leon.

**Comment by treshugart** [comment]
@matthewrobb have you tried raising an issue in https://github.com/w3c/webcomponents? it might be worth discussing.

@RevillWeb I missed the issue you linked to earlier and updated my response accordingly. Sorry about that. The issue https://github.com/w3c/webcomponents/issues/628 reflects what we've experienced with Incremental DOM, which I'm not sure if you've seen. Is Chrome still working for you? You might just be getting that warning from the initial appending without `rel`.

**Comment by matthewrobb** [comment]
@RevillWeb If your primary concern with @import is the loading characteristics then my suggestions would be to use preloading techniques in the root document where possible and rely on caching. There are many other potentially viable optimizations such as using data-uri's and object-urls but I wouldn't go that deep down the rabbit hole unless you are feeling performance pain from @import and/or simply copying the css source text into the shadow root which again is supposed to be well optimized/deduped by the browser.

**Comment by RevillWeb** [comment]
Thanks @matthewrobb for the suggestions. I suspect in my use case most of the import performance issues may not be much of a problem, I'll need to do some testing.
