### ISSUE TITLE
Consider possibility to create custom elements without shadow DOM

### ISSUE THREAD

**Issue by majo44** [skatejs/skatejs#1145]
I see that on 5.x you are going to use preact instead of incremental-dom. Are you going to support also server side rendering ? I see possibility to do this in very simple way by using https://github.com/fgnass/domino. I created PR do domino which provides custom elements support https://github.com/fgnass/domino/pull/96. This PR is passing all critical web-platform-tests/custom-elements tests. I checked and is working fine with incremental-dom and preact based custom-elements. 

But it is not supporting shadow DOM. As you know Shadow DOM is imperative (currently, but https://discourse.wicg.io/t/declarative-shadow-dom/1904) and it is  not possible to server side prerender of it. That is why I looking for custom-elements authoring tool which will allow me to prerender as regular DOM children.

Please consider possibility to create custom elements without shadow DOM.
With preact there will be a issue https://github.com/developit/preact/issues/654, but I hope preact will  support this idea.

**Comment by treshugart** [comment]
> Are you going to support also server side rendering ?

SSR support for Shadow DOM isn't really possible at this point due to the lack of a declarative API (as you note later). I think @matthewp might be working on something to help this?

> I see possibility to do this in very simple way by using https://github.com/fgnass/domino. I created PR do domino which provides custom elements support fgnass/domino#96.

Very cool!!!

> Please consider possibility to create custom elements without shadow DOM.
With preact there will be a issue developit/preact#654, but I hope preact will support this idea.

This is already in the works. We just need to get https://github.com/skatejs/skatejs/pull/1141 over the line. The title of that is misleading in its relationship to this, but as part of allowing an element to create its own shadow root, while also automatically doing it, we'll likely be providing a property so that the consumer can specify where they want to render to.

**Comment by matthewp** [comment]
No plans to generalize SSR for me personally.  I'll likely just use inline scripts to shift things into the shadow DOM for now.

Yep, #1141 will allow a way to specify the Node to append to. I plan on wrapping that up today or tomorrow.

**Comment by Hotell** [comment]
I guess this was closed by #1141 

so closing, feel free to reopen if there are more things to discuss/implement
