### ISSUE TITLE
ReferenceError: Can't find variable: skate

### ISSUE THREAD

**Issue by JacobEvelyn** [skatejs/skatejs#1170]
I've been playing around with various web components-related things over the past few days and Skate seems to meet my needs well. But I honestly can't figure out how to use it. I just want to drop in a script tag but following the [instructions on your README](https://github.com/skatejs/skatejs#script-tag) don't seem to work.

For starters, that `unpkg` link takes me [here](https://unpkg.com/skatejs@5.0.0-alpha.3/dist/index-with-deps.min.js), and even when I change the `unpkg` URL to just `https://unpkg.com/skatejs@5.0.0-alpha.3` or `https://unpkg.com/skatejs@4.6.7/dist/index-with-deps.min.js` I still get errors telling me that `skate` is not defined. All I'm trying to do is play around with Skate in a browser (Safari 10.1) that supports its dependencies without having to muck around with a build chain or anything like that.

Where am I going wrong?

**Comment by Hotell** [comment]
try this:

it's template for 4.x version

will setup 5.x soon

**Comment by treshugart** [comment]
Here's a JSBin http://jsbin.com/pifejixegi

You need to supply Preact as a dependency (it's a `peerDependency` in 5.x) as that is what does the rendering by default. There is a custom renderer API, though, so if you're using the bundle and want to write a custom renderer, you can just do something like `window.preact = {};` to get around this (this should be documented at some point). This is only an issue with the bundle.

Unfortunately we can't get around having to load the polyfills, even in Chrome, until #1167 / #1142 is resolved because the [native-shim](https://github.com/webcomponents/custom-elements#es5-vs-es2015) is needed.

**Comment by Hotell** [comment]
Can we close this or it's still an issue ?

**Comment by treshugart** [comment]
Closing as alpha.7 doesn't seem to be an issue.
