### ISSUE TITLE
5.0 - SSR with domino - Please add option to synchronous rendering.

### ISSUE THREAD

**Issue by majo44** [skatejs/skatejs#1190]
I created simple example of skatejs SSR: https://github.com/majo44/skatejs-ssr
In general it is works fine but I noticed problem with the debounce of rendering.
I think for SSR is really unexpected that dom modifications occurs asynchronously.
Are we able to add option to force synchronous rendering. 
I think the best option will be do this globally (to be able to reuse same code of components on client and server).

**Comment by treshugart** [comment]
I can see how this would catch you off guard. This was a hard trade-off to make. If you set 10 props, you do 10 renders if it's sync. Microtasking it makes it only one. What's the ultimate goal here for you?

If we introduce an option, I don't think it should be global. If you want to set an option for all of your components, extends a base class that has this option set. Still not sure if I want to introduce an option. Maybe we can make the API more approachable so you don't have to `setTimeout()` (like using promises)? Open to ideas.

**Comment by treshugart** [comment]
Also, why aren't you just using https://github.com/skatejs/ssr?

**Comment by majo44** [comment]
I clearly understand why you using debounce. But in general in my opinion this is not good approach. The nature of native DOM is synchronous.  Please look if in DOM I will call `div.setAttribute('style', 'position: fixed');` I do not have to `setTimeout` to take new `div.getBoundingClientRect();`.
Even custom-elements are designed in this way (connectedCallback is called with all attributes already set). This will be a really unexpected for end users that after x.innerHTML = 'x-tag' the x-tag will be rendered asynchronously, the native DOM is not behave in this way. 

As I know even Preact and React are not doing this. There is possibility to add debounce to React/Preact component, but you are doing this on your own risk. The base implementation is synchronous.

There is alternative possibility for provide some optimizations but only for cases when the one skate component is rendering another skate component. In such case we can queue the the rendering. 

Eg.  
```
let rendering = false;
let stack = [];

function queuedRender(element) {
    if (!rendering) {
        rendering = true;
        try {
              render(element.renderRoot, element.renderCallback());
        } finally {
            rendering = false;
            if (stack.length > 0) {
                queuedRender(stack.shift())
            }
        }
    } else {
        let index: number = stack.indexOf(element);
        if (index > -1) {
            stack.splice(index, 1);
        }
        stack.unshift(element);
    }
}
```

I'm also against ideas for providing some Api with Promises ect. Lets try to be as close as possible to standard. 

I did not know there is https://github.com/skatejs/ssr :)
Nice to see, but as I see domino provides more possibilities, I will look closer at undom and jsdom CE support.

**Comment by majo44** [comment]
Btw FYI
I used https://github.com/raxjs/server-side-rendering-comparison to compare performance of ssr techniques

```
Preact#renderToString x 1,229 ops/sec ±2.23% (86 runs sampled)
Preact#undom x 249 ops/sec ±4.04% (75 runs sampled)
Preact#domino x 30.89 ops/sec ±2.08% (53 runs sampled)
Preact#domino.innerHTML x 31.44 ops/sec ±2.56% (55 runs sampled)
Preact#jsdom x 37.63 ops/sec ±3.30% (51 runs sampled)
Preact#jsdom.innerHTML x 40.78 ops/sec ±3.07% (53 runs sampled)
Fastest is Preact#renderToString
```

**Comment by treshugart** [comment]
Most of what you're saying seems to revolve around:

> Lets try to be as close as possible to standard.

There's a bit more to it than that and we've spent a lot of time investigating and figuring these things out; our implementation and approach is not naive.

Firstly, nothing in the standards say that being synchronous is a DOM convention and there's nothing directing supersets to be sync either. The custom element specification points the following out about [custom element reactions](https://w3c.github.io/webcomponents/spec/custom/#custom-element-reactions):

> The way in which custom element reactions are invoked is done with special care, to avoid running author code during the middle of delicate operations. Effectively, they are delayed until "just before returning to user script". This means that for most purposes they appear to execute synchronously, but in the case of complicated composite operations (like cloning, or range manipulation), they will instead be delayed until after all the relevant user agent processing steps have completed, and then run together as a batch.

To this point, engines have the ability to write deferred or asynchronous operations while appearing synchronous to the user's script. As users, we don't have this ability. The closest we can get to this would be to delay something until the next microtask. You may have read https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/ (if not it's a great read).

I can see why you would prefer synchrony and we would too, but given the constraints, this choice is deliberate. We favour performance over API in this scenario because the only time you should need to check the async rendered tree is in your tests. If you have component code reaching into shadow roots, you should probably reconsider your approach.

Libraries like React and Preact can render synchronously because they have a proprietary model for setting and responding to property updates. They happen all at once via `setState()` and by passing down props. They don't respond to individual property sets like DOM nodes do.

I've long considered adding a way to make things synchronous. We in fact use to have an imperative way to render with props synchronously but it felt like a divergence from the standard web component conventions, and it could easily be abused, so we decided to remove it. I'm not against adding a particular option to make testing synchronous, but those sort of things can have unexpected outcomes where you write tests that pass but in production something breaks due to the differences in render timing. I'm open to suggestions here, but Skate's default won't ever change to be sync until userland has the ability to schedule like the internals can.

**Comment by treshugart** [comment]
> Nice to see, but as I see domino provides more possibilities, I will look closer at undom and jsdom CE support.

Domino currently doesn't support custom elements or shadow DOM so there aren't really any possibilities. JSDOM is standards compliant so they require a lot of patching and workarounds. The polyfills also fail when used in it because it lacks features they require to function.

> I compared only preact render, not custom-elements.

According to these, I wouldn't want to use Domino even if it supported web components.

**Comment by treshugart** [comment]
To directly answer how to do this in other implementations aside from `@skatejs/ssr/register` (which is basically Undom with stuff on top), you should be able to just:

```js
const render = require('@skatejs/ssr');

// Where myComponent is a custom element instance.
render(myComponent).then(console.log);
```

**Comment by treshugart** [comment]
I just realised that may also work in Domino, too.

**Comment by treshugart** [comment]
Re:

> There is alternative possibility for provide some optimizations but only for cases when the one skate component is rendering another skate component. In such case we can queue the the rendering

If you see where some improvements can be done, then I'm happy to discuss that in a separate issue.

**Comment by treshugart** [comment]
I raised #1191 to discuss the implementation of a possible option for this (this issue contains tangental discussions).
