### ISSUE TITLE
Referencing light DOM within a slot

### ISSUE THREAD

**Issue by bjork24** [skatejs/skatejs#1193]
I have a situation where I need to reference the light DOM to validate and manipulate the passed element, however, I can't figure out how to get a reference to the passed element. Here's what I have:

```html
<res-checkbox>
  <label slot="label">This is res-checkbox</label>
  <input slot="checkbox" type="checkbox" id="test-id" />
</res-checkbox>
```

And in the component:

```javascript
import { Component, h, define, prop } from 'skatejs';
import styles from './style.scss';

export class ResComponent extends Component {

  static get is() { return 'res-checkbox'; }

  renderedCallback() {
    console.log(this.querySelector('input[type="checkbox]'));
    // -> null
    console.log(this.getElementsByTagName('input')[0]);
    // -> undefined
    console.log(this.shadowRoot.querySelector('input[type="checkbox]'));
    // -> null
    console.log(this.shadowRoot.getElementById('checkbox').querySelector('input'));
    // -> null
    console.log(this.shadowRoot.getElementById('checkbox').assignedNodes());
    // -> []
    console.log(this.childNodes[1]);
    // -> undefined
    console.log(this.children[1]);
    // -> undefined
  }

  renderCallback() {
    return <div id="wrap">
      <style>{ styles.toString() }</style>
      <slot name="label" id="label"></slot>
      <label id="fakeCheckbox">
        <slot name="checkbox" id="checkbox"></slot>
      </label>
    </div>;
  }

}

define(ResComponent);
```

I've tried the same reference methods in `renderCallback` and `connectedCallback`, but they don't work there either. Is there a best practice for referencing light DOM?

**Comment by treshugart** [comment]
Re referencing children / assigned nodes, there's an [open issue](https://github.com/skatejs/skatejs/issues/995) for doing this in an official way at some point. There's a [link off to a gist](https://gist.github.com/treshugart/6bb7093a709b5cf1d52bc67a89c70709) that implements what is discussed.

If you want to do this for a specific slot, you can use `ref` on the `<slot />` in `renderCallback()`:

```js
<slot ref={slot => {
  // Do something with the slot's assigned nodes.
  const nodes = slot.assignedNodes();
}} />
```

At this point, adopting either of these patterns could be considered controversial. It's the same thing as doing anything more than a straight rendering children in React, such as mapping over children etc. Some feel this a very acceptable thing to do, especially since it's part of React's API (and similarly, also the shadow DOM API - via `assignedNodes()`).

Just be aware that relying on children for data could prove to be brittle in some scenarios. In yours, for example, the nodes could be provided in different orders, so mapping and filtering would be a better way than accessing via indicies.

I'm not sure why `this.querySelector()` isn't working for you, but it's probably because the children haven't been rendered yet. However, using this method isn't reliable because you could be selecting any descendant, not just immediate children.

Using the `childrenChangedCallback` implementation, suggest setting a prop that you define (or possibly creating a mixin that does this for you.

```js
static props = {
  mychildren: props.array
}
childrenChangedCallback () {
  this.mychildren = [...this.children];
}
renderCallback () {
  // etc...
  this.mychildren.filter(child => child.localName === 'label');
}
```

**Comment by bjork24** [comment]
Thanks @treshugart . That's really helpful. After some more debugging, I figured out that the problem was caused by me putting the script in the head rather than the foot of the document.

**Comment by treshugart** [comment]
> I figured out that the problem was caused by me putting the script in the head rather than the foot of the document.

Custom elements you write should be resilient to this because your consumers may choose to do either and your element may, or may not, be initialised with children (i.e. via the parser before CEs are defined).
