### ISSUE TITLE
What does new SkateJS do behind the scenes?

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1204]
I'm looking for a brief overview to know how SkateJS uses cdom behind the scene and how it is different than what React does.

The new API is much like React when using `skate.h` with JSX, but with Custom Elements APIs.

When returning the elements from `renderCallback` what happens? How is it different than React? Does it get put in a ShadowDOM?

How does one do component encapsulation in SkateJS using `skate.h` in `renderCallback`? Do we use ShadowDOM? How do we distribute child components in the markup of a renderCallback?

**Comment by treshugart** [comment]
> When returning the elements from renderCallback what happens? How is it different than React? Does it get put in a ShadowDOM?

The return value of `renderCallback()` depends on the renderer implementation `rendererCallback()`. By default in 5.x it uses Preact, so the return value is rendered directly to the custom element's shadow root and Preact handles the rest. This could use React, or anything else; Skate is just a functional DOM interface to a functional renderer with a safe default.

Skate renders to a `shadowRoot` by default, but there is public API to specify a custom render target, or `renderRoot`. This is all automated under the hood so all you need to worry about is writing your `renderCallback()`.

I'll leave this open so that we can address it in the docs rewrite before we release 5.0.

**Comment by trusktr** [comment]
Ah, cool, I see. So whereas a React app may have a single vdom context (a single React hierarchy) for the whole app, SkateJS apps using skate.h/Preact, or custom `rendererCallback` with React/Preact/anything-else will have a context per component (per shadow root), and these contexts will be composed together in components that use these components in there own shadows. Interesting! I wonder what perf implication this has compared to single-context-per-app.

(I like your extensive use of class factory mixins!)

**Comment by treshugart** [comment]
You've summed it up well :)

> I wonder what perf implication this has compared to single-context-per-app.

From some tests I've done in the past, leveraging the built-in custom element lifecycle is much faster than relying on a custom component implementation. Besides that, the fundamental difference is that each component is it's own atomic render tree. I don't think this has any implications on performance, it just makes the components composable inside any library instead of just itself.

**Comment by trusktr** [comment]
> Besides that, the fundamental difference is that each component is its own atomic render tree. I don't think this has any implications on performance, it just makes the components composable inside any library instead of just itself.

Yeah! That what I like about it! It is possible to develop components similarly to how we do in React, but anyone can use the components, unlike React components being limited to usage inside React only.

Can you post any of those perf tests? I can probably make my own too.

A `rendererCallback` with [Turbine](https://github.com/funkia/turbine) would be conceptually interesting. In concept, it seems like it could be faster than vdom implementations (it n theory, if optimized), but also the paradigm is interesting!

**Comment by treshugart** [comment]
> Can you post any of those perf tests? I can probably make my own too.

Honestly, I'm not sure where to even start looking and, like I said, I don't think they'd show anything real-world useful.

> A rendererCallback with Turbine would be conceptually interesting. In concept, it seems like it could be faster than vdom implementations (in theory, if optimized), but also the paradigm is interesting!

It does look interesting. It seems all you'd be doing is calling `runComponent` within `rendererCallback()`.

For reference, here's another renderer using [lit-html](https://github.com/PolymerLabs/lit-html): https://github.com/lastmjs/data-bound/issues/13#issuecomment-317135667.

**Comment by arjunyel** [comment]
Hey I'm pretty new to this renderer stuff, is there a reason you choose preact as the default instead of lit-html? I don't understand how they differ really, I just know lit-html is around 2kb while preact is 3kb

**Comment by joshgillies** [comment]
@arjunyel My guess would be that Preact is a much more mature project. lit-html has only been around for ~2months.

**Comment by treshugart** [comment]
> arjunyel My guess would be that Preact is a much more mature project. lit-html has only been around for ~2months.

Basically this. Maturity and familiarity. Skate straddles the line between Web Components and React-like stuff in terms of philosophy.

Skate doesn't "bundle" Preact, you still have to add it as a dependency, it's just that we defaulted a renderer to use it. This is trying to walk the fine balance of size vs API complexity.

**Comment by treshugart** [comment]
The preact renderer is now a separate dependency: https://github.com/skatejs/renderer-preact. We need to updated it to the latest 5.x API but it should work with beta-3 (latest beta).

**Comment by YvanDaSilva** [comment]
@treshugart  Sorry to comment on a closed issue, but, would you mind adding to the docs what @trusktr said ?

> Ah, cool, I see. So whereas a React app may have a single vdom context (a single React hierarchy) for the whole app, SkateJS apps using skate.h/Preact, or custom rendererCallback with React/Preact/anything-else will have a context per component (per shadow root), and these contexts will be composed together in components that use these components in there own shadows, so an app can have layers of vdom contexts, and child vdom contexts may only be updated only if a parent vdom's state causes actionable diffs on the parent content. Interesting!

This is just perfect! I was trying to understand what is going under the hood.

Since SkateJS is quite a multipurpose library for webcomponents with various renderers pluggable, would it make sense to add an extra section to the documentation which explains this and more ?

I don't think a documentation as in the "framework doc" sense is needed, but some bits and pieces would be absolutely awesome, just like the ones we found if we dig deep in github issues and the short ones already provided on the current doc.

example:
- Advanced section
  - SSR
  - CSS ( https://github.com/skatejs/skatejs/issues/1027 )
  - Integration with webpack if anything out of the norm
  - Open issues (css with ssr, jsdom, etc.)
  - Testing ( https://github.com/skatejs/skatejs/issues/948 )
  - HMR (Some doc got lost : https://github.com/skatejs/skatejs/issues/564 see your last comment )

If you want me to open a new issue with all the points related to documentation let me know.

**Comment by treshugart** [comment]
@YvanDaSilva added in https://github.com/skatejs/skatejs/issues/1426.

**Comment by YvanDaSilva** [comment]
Nice ! Thank you ! :)
