### ISSUE TITLE
Ability to pass custom arguments to renderCallback() closure

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1221]
It's fairly easy to write a custom renderer for view that uses strings to render the template: https://gist.github.com/treshugart/b27bf304a5cba2f79b5eafa5436c414e.

However, if you wanted to use a functional component that uses vdom (`createElement`) you need a way to pass `createElement` to the function to `renderCallback()` because Vue doesn't expose this outside of its `render()`. This means we need a way to be able to pass it in to the user defined `renderCallback()` which we wrap in a closure. We do this to ensure that `renderCallback()` always gets the expected props, however, it seems edge cases need to be catered for.

Currently, I have no proposals as to how this should be handled.

**Comment by darrenjennings** [comment]
New to skate here, but typically you'd create an injection component as your `template` property on `new Vue({template:...})` and just pass props to it. Something like this:
https://gist.github.com/darrenjennings/1431eec141bcf17787d11fb62bd8ee60

Webpack bin:
https://www.webpackbin.com/bins/-L1zqzM5W02Zx8qfQ58O

Am I missing something? New to skatejs so unclear how this would exactly fit into building the future vue renderer.

**Comment by treshugart** [comment]
I was talking about returning `h()` directly from Skate's `render()`, not Vue's. So where you're writing the template string, I'm talking about, instead, using `h`. In order to do that, somehow it needs to gain access to the `h` function. I think the way you've done it is okay for now and we can write quite a comprehensive renderer and only consider this in the future if need be. I prefer template literals, for the most part, anyways.

Does that clear things up?

**Comment by darrenjennings** [comment]
Yes I think so. My approach seems to allow *any* vue component to be plugged in without the user having to write the template literal, just tell `withVue` which component you wanted to pass WC props to and then do any `h` work inside the vue component. It's not the same flexibility as the preact/react renderer though so I see the issue.

Not sure if you were aware but once you have a vue instance, you can access createElement (a.k.a. `h`) via `this.$createElement` where `this` is the vue instance. That didn't seem immediately helpful in passing it to Skate's render for me when I was looking into this, but since you're the author of the code maybe you'd know what to do.

**Comment by treshugart** [comment]
The `@skatejs/element` class now forces renderer sub-classes to explicitly call `this.render()` in `renderer()`, thus making it possible to pass custom args then.
