### ISSUE TITLE
static property syntax not valid in ES2015

### ISSUE THREAD

**Issue by kito99** [skatejs/skatejs#1248]
## Bug report

The examples in the README compile using TypeScript (and presumably Flow), but don't work in browsers that support ES2015 (such as Chrome).

- Skate version: 5.0.0-beta-3
- Affected browsers (and versions): *Chrome (latest)

### Current behaviour

For example, this doesn't run in Chrome:

```javascript
  static props = {
    name: props.string
  }
```
Using a static getter seems to interfere with Skate, but this works:

```javascript
    GreetingComponent.props = {
        name: props.string
    };
```
### Expected behaviour

The documentation should state that the code isn't pure ES2015 and/or provide an alternate example.

**Comment by treshugart** [comment]
That's a good point to call out. I'm not sure what the best thing to do here is yet. Class fields are now in Stage 3, so basically all but implemented in the latest spec: https://github.com/tc39/proposal-class-fields.

FWIW, getters not working is a conscious decision because if using getters, you end up having to either:

1. imperatively invoke their registration on the component, or
2. lazily do it somewhere in the lifecycle

The problem with 1 is that it's imperative, your definitions are no longer declarative. The problem with 2 is that your props may not be defined yet if you need static access to them because a component may not have gone through it's lifecycle yet.

I'm open to better options, but it seemed that the best thing to do here was to be explicit and use a setter to define properties on the prototype. This sets everything up for proper inheritance the way native is, as opposed to lazily doing it, or having to call `super.props` in the getter.

**Comment by Hotell** [comment]
Yeah we will update docs with proper info, but I would keep it as is. getters == dynamic values == RIP statical type checking :)

**Comment by treshugart** [comment]
Yeah, getters are hard with type systems. Unfortunately we have to do this low-level in Skate, but it means that you don't have to ;)

**Comment by kito99** [comment]
Makes sense. Just pointing it out in the docs is sufficient; it should be clear (1) that you need a transpiler to use that syntax, and that (2) you can also do it the other way (just define the property on the prototype without using the static keyword).

**Comment by treshugart** [comment]
Made main example work without transpilation. Will work on other examples as we encounter them.
