### ISSUE TITLE
Extending a custom element fails in Chrome with registerElement error

### ISSUE THREAD

**Issue by nicolasv** [skatejs/skatejs#125]
In `test/unit/components.js` [line 44](https://github.com/skatejs/skatejs/blob/621de5a/test/unit/components.js#L44) it ends up calling through to `skate()` with `extends` equal to `'non-existent'`.

This causes the test to fail in Chrome with

```text
Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'my-element-10'. The tag name specified in 'extends' is a custom element name. Use inheritance instead.
```

This [discussion in the W3 mailing list](http://lists.w3.org/Archives/Public/public-webapps/2014OctDec/0155.html) indicates that Chrome is following the spec here:

> In the [definition construction algorithm](http://www.w3.org/TR/custom-elements/#dfn-definition-construction-algorithm), step 8.2, it says:
>
> "If BASE does not exist or is an interface for a custom element, set ERROR to InvalidName and stop."
> In this case, BASE is the x-button and it is an interface for a Custom Element. I think this is the case you're hitting. I think Chrome roughly matches the spec in this case.

**Comment by nicolasv** [comment]
@treshugart any suggestions on how to workaround/fix this?

**Comment by treshugart** [comment]
You can just make it extend a non-div built-in element since that function only uses div's. The purpose of those tests are to ensure that the `is` attribute is checked properly. This doesn't really matter for native, but matters for both falling back and when using attribute / class bindings.

Lines 45 and 46 don't need to be changed but probably should be to be consistent with line 45. Just to be clear, changing those lines to the following should work:

    assertType(skate.types.TAG, 0, 'span');
    assertType(skate.types.ATTR, 0, 'span');
    assertType(skate.types.CLASS, 0, 'span');
