### ISSUE TITLE
Documentation assumes shadow dom is implemented

### ISSUE THREAD

**Issue by blikblum** [skatejs/skatejs#1268]
## Discussion

The readme examples shows the behavior when shadow dom is supported natively, but according to [caniuse](https://caniuse.com/#feat=shadowdom) only Chrome supports it natively. 

Later in  [polyfills](https://github.com/skatejs/skatejs#polyfills) section says that polyfills are available.

The problem is that the recommended polyfill, according to the provided [link](https://github.com/webcomponents/webcomponentsjs) is ShaddyDom that has a few drawbacks and do not render exactly as documented.

IMO somehow this should be cited

**Comment by treshugart** [comment]
That's v0. V1 is implemented in Chrome, Safari and currently being implemented in Firefox. https://caniuse.com/#feat=shadowdomv1

ShadyDOM works just fine for the most part. There's drawbacks to most polyfills, but i'm not sure if it's our job to document them, especially if they're already documented in the polyfill docs. Do you have anything in mind that you'd like to call out specifically? Otherwise I think what we've done is fine here https://github.com/skatejs/skatejs#polyfills.

**Comment by blikblum** [comment]
You are right. The polyfill issue should not be documented here
