### ISSUE TITLE
Question: Is there a callback for when props are set?

### ISSUE THREAD

**Issue by donifer** [skatejs/skatejs#1279]
## Question

Is there any life cycle callback for when props are initially set? Currently using `updating` to work around it but I'm looking for something that would just run once when props are initially set.

PS: Is this the best place to ask questions?

**Comment by treshugart** [comment]
Yep! The `updating()` callback will be the one you want. It's mentioned in http://skatejs.netlify.com/mixins/with-update but it's not very visible because it's in a small section at the bottom. Apologies.

This is definitely the correct place to ask question. Ask away!

**Comment by donifer** [comment]
Awesome thanks! More questions your way:

1. When using a custom mixin, I've been able to "extend" the props of a component, however I haven't find a way to do the same with `state`, I know that `state` should be "internal" but shouldn't I still be able to do it since I'm composing the whole component making it still be "internal"?

2. Why is props `static` but not state? And for props I can do a getter function but not for state?

Thank you!

**Comment by treshugart** [comment]
## 1. Extending state

You should be able to do something like:

```js
class Base extends withComponent() {
  state = {
    test: true
  }
}

class Extended extends Base {}
```

And `Extended` will inherit the `state`. However it's likely you don't want this. If you set `state` in `Extended`, of course it's going to override `Base` because that's how class fields work.

What you *might* be referring to with "getter function" for state is this:

```js
class Base extends withComponent() {
  state = {
    test: true
  }
}

class Extended extends Base {
  get state() {
    return { ...super.state, ...{ anotherValue: true } };
  }
}
```

The problem here is that you've overwritten the getter, so setting state has no effect.

However, all that might be a bit too much. Maybe just use a `constructor`?

```js
class Base extends withComponent() {
  state = {
    test: true
  }
}

class Extended extends Base {
  constructor() {
    super();
    this.state = { ...super.state, { myNewState: true } };
  }
}
```

Without the exact use case it's sort of hard to tell what you might want to do instead. The key to remember here is that it's just JavaScript, there's not much magic happening with state here.

## 2. Static props

`static props` does a few things:

1. It links attributes with properties, 1 way by default if you use the built-ins.
2. It defines properties on the element that invoke a render (i.e. `element.myProp`).
3. It ensures that when the properties change, that they're properly batched up into a single render.
4. Provides extra semantics, such as how data is coerced to the property value and how data is serialised to an attribute, or deserialised from an attribute.

There is no corresponding `static state` because state is set like `element.state = {}`. You update it all at once; it's not exposed as public API.

> And for props I can do a getter function but not for state?

Can you elaborate on this? A getter function for what?

**Comment by donifer** [comment]
@treshugart Seriously man, thanks a lot for taking the time giving these detailed answers to my questions. I really appreciate it.

>Can you elaborate on this? A getter function for what?

Disregard this one, I thought I couldn't use a getter function for state, all my state questions were answered in your 1. response.

I should be good for now, I feel that I understand way more of how things work now, thanks again. Will close this for now. 

If I have more questions should I reopen this one to avoid polluting the issues page or create a new one? Much ❤️.

**Comment by treshugart** [comment]
@donifer I'd prefer you open an issue per question / consecutive-questions. Probably makes it easier for others to find answers because they'd be in the title. Thanks for the thanks!

**Comment by MikaAK** [comment]
These detailed answers are awesome. I've been stuck understanding how to use props all day. This should be in the docs!

**Comment by treshugart** [comment]
Cheers @MikaAK, I raised https://github.com/skatejs/skatejs/issues/1291 to do that :)
