### ISSUE TITLE
React renderer: Rendering to light DOM is not working properly. When parent custom-element is rerendering, child custom-element content is lost.

### ISSUE THREAD

**Issue by belubeltran** [skatejs/skatejs#1284]
This is basically the same issue as https://github.com/skatejs/skatejs/issues/1197 but with react-renderer.
My question is: Is it possible to remove the shadow-root and render the children correctly with react-renderer?

**Comment by treshugart** [comment]
No it's not possible to do this because of React's reconciliation algorithm. When you stop using a shadow root, you lose the encapsulation.

You may be able to use something like https://gist.github.com/treshugart/e19c2be255448cd31d261f2e8db2127c to trick React while not having to fully polyfill Shadow DOM.

**Comment by treshugart** [comment]
In `@skatejs/element` you can now override `renderRoot` to provide a custom target to render to. However, you may run into issues with how React reconciles the DOM when there's no encapsulation.
