### ISSUE TITLE
Is it possible to prerender everything on serverside?

### ISSUE THREAD

**Issue by Align-Deployment** [skatejs/skatejs#133]
Subj. 
Thanks.

**Comment by treshugart** [comment]
Actually, yes. It depends on how you're templating your custom elements,
though. On its own, all Skate does is bind behavior. Whether or not you
render your template client or server side doesn't really matter.

If you want to be able to do both, you can set a flag attribute in the
server markup and check for it in your template code. If the attribute
exists on the element, don't render client side, otherwise go for it. I've
been thinking about building that into Skate as a feature, but it'd only
save you a couple lines of code anyways.

I hope that helps.

**Comment by treshugart** [comment]
Just FYI, a recent commit will make it so you don't have to worry about checking manually.

https://github.com/skatejs/skatejs/commit/0d5ed709b9da54958690ac2e16414707a9aa2a06

I just came across an issue where jQuery was cloning and reinserting the element after it was templated causing it to happen twice. This only seemed to happen if browsers supported custom elements natively and when skate was using those means to register the component.

**Comment by treshugart** [comment]
Closing this now. Please re-open if you still have any questions.

Cheers.

**Comment by Align-Deployment** [comment]
Thanks a bunch

**Comment by treshugart** [comment]
@Align-Deployment, just FYI, this technique for server-side rendering isn't public API yet. I don't want to solidify anything until we feel it's ok to start using as public API. I'm putting it on the road map, but until then use with caution.

**Comment by treshugart** [comment]
https://github.com/skatejs/skatejs/issues/136
