### ISSUE TITLE
WC with React Render Props

### ISSUE THREAD

**Issue by belubeltran** [skatejs/skatejs#1339]
Hello! I'm looking for a way to wrap React components that use the render props pattern (like Downshift https://github.com/paypal/downshift or react-toggled https://github.com/kentcdodds/react-toggled) , which requires being able to receive functions as attributes from Web Components. Is this possible? Is there a way to do this? or a workaround?
Thanks

**Comment by treshugart** [comment]
Render props with custom elements have inherent restrictions due to the fact that they tightly couple your public API to your internal templating mechanism. For example, if you're using React to render your web components internally, your render props must return React nodes. You're naturally restricted to this when using only React, so it's not inherently a bad thing, it's just something that you'll need to make your consumers aware of when documenting your public API.

Out of the box, there isn't anything you need to do with Skate or custom elements to enable this feature because it's just a property. However, since you're using React, they don't yet set properties on custom elements (only attributes). This restricts the data-type you're able to use with custom elements to strings. You can work around this, though, as I'll show in the next section. There's also a couple RFCs happening over in React to address custom element compatibility: https://github.com/facebook/react/issues/11347 and https://github.com/reactjs/rfcs/pull/15#issuecomment-361022582.

I recommend using https://github.com/skatejs/val,  in the mean time, to enable better custom element interop. Probably best if I leave it up to the docs over there to explain the rationale and usage. I'll close this for now, but feel free to reopen if you have any more questions.
