### ISSUE TITLE
Simplify attribute / property reflection

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1348]
API change details:

- `attribute` should be called `attr` for consistency with `props` abbreviation.
- `attribute` will be deprecated, but still work in 6 for simpler upgrades. Removed in subsequent major release.
- If `attr` is `true`, then it should default to `propName.toLowerCase()`.
- If `attr` is a truthy, it is used as is with no transformations.
- If `attr` is anything else no attr-to-prop reflection occurs at all.

```js
propName: {
  // propName.toLowerCase()
  attr: true,

  // 'myattr' is the attribute name
  attr: 'myattr',

  // 'myattr' is the attribute name
  // If the browser doesn't do this, we won't worry about it
  attr: { toString: () => 'myattr' },

  // No attribute reflection.
  attr: undefined | null | false | 0 // etc
}
```

### Breaking change

The only breaking change here is that we will not reflect back to the attribute at all. This massively simplifies a lot of the reflection logic and will reduce size even further. *Most should not be affected by this as it is not recommended anyways.*

To work around this, use the `updating()` callback to set attributes.

**Comment by trusktr** [comment]
> If attr is true, then it should default to propName.toLowerCase().

Can this be optional? And also option to have both?

I think dash-case is more readable. Vue for example has a [`.prop` modifier](https://vuejs.org/v2/api/#v-bind) for passing values to properties instead of attributes, which converts from dash-case to camelCase.

But for convenience, an option to have both at the same time would be interesting (it is what I do on my custom elements). So both of these could be the same:

```html
<i-node mountPoint="..."></i-node>
```
```html
<i-node mount-point="..."></i-node>
```

where `mountPoint` is the same as `mountpoint` due to case insensitivity. It'd be nice if I could have both automatically for when I migrate some elements to SkateJS.

**Comment by treshugart** [comment]
This is now superceded by #1499.
