### ISSUE TITLE
Lifecycle behavior and documentation?

### ISSUE THREAD

**Issue by mnemanja** [skatejs/skatejs#1400]
How should one go about updating a local state of a component? I'm using `react` as a renderer.

The `render` method gets called before the `connectedCallback`, and it doesn't get rerendered after the `connectedCallback` updates the state.

Could you please point me to a documentation that lists all lifecycles events?

**Comment by treshugart** [comment]
All lifecycle events applied by all mixins are shown here: http://skatejs.netlify.com/mixins. Each mixin has separate docs on each lifecycle callback.

If you want to do something after a render, you should use the `rendered()` callback. There's `connecting` and `connected` that wrap around `connectedCallback()`, but since renders are batched, you're not guaranteed to have a render happen sync in that.

To update local state, set the `state` prop on the element. For example:

```js
onClick() {
  this.state = { clicked: true };
}
```

**Comment by mnemanja** [comment]
Thanks @treshugart.
