### ISSUE TITLE
Extend elements other than HTMLElement not working

### ISSUE THREAD

**Issue by cndev123** [skatejs/skatejs#1424]
## Bug report

* Skate version: _5.1.1_
  
* Affected browsers (and versions): _Chrome_

### Current behaviour

You can use the following two lines without problems:
`const Component = withComponent();`
`const Component = withComponent(HTMLElement);`

However, if I want to derive from another HTMLElement like:
`const Component = withComponent(HTMLDivElement);`

I get an error message: 
Uncaught TypeError: Failed to construct 'HTMLDivElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

### Expected behaviour
I would like to derive from other elements than HTMLElement.

**Comment by treshugart** [comment]
I need some more info:

1. What line of code is actually causing that error? It sounds like the native shim, or polyfill. 
2. How are you defining your element? If you're using `customElements.define()`, and correctly specifying the options as spec'd, things should just work, so long as the polyfill supports it. Skate's `define()` doesn't define a customised built-in because of number 3, but you don't have to use it; it just provides convenience.
3. Customised built-ins (anything other than `HTMLElement`) is spec'd, but will never be implemented by all browser vendors, unless Apple decides to change their mind. Keeping that in mind, this will never be cross browser.

Skate should work like this out of the box because it doesn't do anything special; the polyfill should handle this case, if it says that it supports it.

**Comment by cndev123** [comment]
Thank you for your investigation. Based on your comments I now believe that the custom-elements-es5-adapter.js polyfill is causing the problem. It has some hardcoded HTMLElements inside. If I replace them with HTMDivElement, I get another error: "Uncaught TypeError: Illegal constructor: autonomous custom elements must extend HTMLElement". 

This is the original stacktrace from the error described in my first post: 

with-renderer.js:21 Uncaught TypeError: Failed to construct 'HTMLDivElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
    at HTMLDivElement._class2 (with-renderer.js:21)
    at HTMLDivElement._class (with-update.js:97)
    at HTMLDivElement._class (with-context.js:17)
    at HTMLDivElement._class2 (with-children.js:19)
    at HTMLDivElement._class (with-lifecycle.js:19)
    at HTMLDivElement.CyNavigator (cyNavigator.min.js:130)
    at new j (custom-elements-es5-adapter.js:4)

**Comment by treshugart** [comment]
When calling `customElements.define()`, with an extension of `HTMLDivElement`, you need to pass some extra arguments. If you don't it treats it as an "autonomous custom element". See this section in the spec: https://www.w3.org/TR/custom-elements/#custom-elements-customized-builtin-example.
