### ISSUE TITLE
Canvas Support?

### ISSUE THREAD

**Issue by michaschwab** [skatejs/skatejs#1446]
## Bug report

I'm not positive I'm posting this in the right place, but I hope so.

I'm trying to run unit tests on custom web components with jest and the skatejs ssr test environment, which is working great - thank you. However, it's failing to instantiate a custom element that uses a canvas, saying canvas.getContext is not a function. Is this a mistake in my setup, or a bug?

I did notice that you referenced jsdom improving their support, and see that they mention canvas here: https://github.com/jsdom/jsdom/issues/1030. Would that solve my problem?
Is there anything I can do in the meantime?

Thanks for your help!
Micha

* Skate version: 5.1.3
* Affected browsers (and versions): all

### Current behaviour

The tests fail because the execution crashes because the canvas function "getContext" is not known.

### Expected behaviour

The tests should pass.

### Use case(s)

We're trying to build a canvas-based tool using web components at Google, and need to find a way to run unit tests.

**Comment by michaschwab** [comment]
I now realize that this is probably not a skatejs issue or even a web components issue, but an issue with jest/jsdom itself. After installing https://www.npmjs.com/package/jest-canvas-mock, this was mostly addressed. Thank you.

**Comment by treshugart** [comment]
Hey, sorry for the late reply. The SSR env uses [undom](https://github.com/developit/undom) as a base implementation because it's so easy to extend. I've been thinking about trying to make it agnostic to the running environment, but have limited time to do so right now. The lack of canvas support would be because neither supports it, but stoked you got the canvas mock working (good to know for future reference, as well!).

Let us know if you have any more issues.

**Comment by michaschwab** [comment]
Good to know and to be aware of, thank you!
