### ISSUE TITLE
Events and custom methods accessibility  

### ISSUE THREAD

**Issue by cliren** [skatejs/skatejs#146]
How do we listen to events on components (like a normal DOM element) and how to use jQuery to interact with skatejs elements?

I am running into the following issues:

1. Listening to click events on my-component doesn't work, get undefined is not an object. Guessing on is not available.

document.getElementById('my-component').on('click', function(e){
    console.log("my component clicked.");
  });

Using jQuery ($) and custom methods:

$(function() {

  document.getElementById('my-component').click(); // doesn't fire the event defined
  document.getElementById('my-component'').configure({}); //doesn't recognize configure method. But    //when called in the browser's console, fires the configure method

  var comp = $('#my-component');
  comp.click(); // doesn't fire the event defined
  comp.configure({}); //doesn't recognize within domReady or post page load from console.

});

//Component

require('skate');

var component = {
  initialize: function() {

    skate('my-component', {
      created: function(element) {
        element.textContent = 'My Component Text';
      },
      events: {
        'click': function(element, eventObject) {
          console.log("my element clicked");
          console.log(element);
          console.log(eventObject);
        }
      },
      prototype: {
        configure: function(config) {
          console.log("my component called!");
          console.log(config);
        }
      }
    });

  }
};

module.exports = component;

**Comment by treshugart** [comment]
Hey, mate, thanks for your questions. Responses below:

**`.on()` not working when called on the raw DOM element**

This is because `getElementById()` returns a raw DOM element and `.on()` is only available on jQuery instances. The DOM "equivalent" is `addEventListener`.

**`click()` and `configure()` don't work when called on the raw DOM element:**

This is because the element is initialised asynchronously when using Mutation Observers to polyfill native web component behaviour. This is assuming you're using <= 0.12. If this is master, then you're probably using a browser that doesn't support native web components. If native web components are available, elements are initialised synchronously. In order to ensure your element is initialised you can either execute your code "after mutations" have been triggered (`setTimeout(callback, 1)` works) or by calling `skate.init(element)` prior to running anything on the element in question. The latter is documented [here](https://github.com/skatejs/skatejs#asynchrony) along with a more in depth explanation on why it needs to be done. In case you're wondering, there is absolutely no other way to (sanely) init synchronously when native web component methods aren't available.

**`click` and `.configure()` don't work when called on a jQuery instance:**

Theres two parts to this. First, jQuery does not fire native browser events (`$(...).click()` or `$(...).trigger('click')`). They do bind to them, however (`$(...).on('click', ...)` or $(...).click(callback)`). IMO this is kinda shitty, but this is a conscious decision in how jQuery has been designed.

The second part to this is that `configure()` is being called on the jQuery instance and jQuery doesn't have that method available on its prototype. You'd want to call `comp[0].configure()` instead.

I hope this helps.

**Comment by cliren** [comment]
Thanks for the quick reply and very detailed explanation! I am using latest Chrome and skate master but still not able to call a custom method without using skate.init(el) or settimeout(callback, 1). I have setup a sample project at https://github.com/cliren/simple-component for you to take a look. Its simple to get it up, clone it and run npm start (will install all the required deps and starts the app).

**Comment by treshugart** [comment]
jQuery strikes again!

To rule out if it was a Skate problem or not, I converted the component to a native custom element and the problem persisted. When I converted the jQuery ready callback to a native `DOMContentLoaded` event handler everything worked.

So the solution seems to be that if you convert:

    $(function() {

At https://github.com/cliren/simple-component/blob/master/src/main.js#L6 to:

    document.addEventListener('DOMContentLoaded', function () {

Then your web component will work. For some reason not calling `$(function(){})` causes jQuery to not be defined. To fix that just call `$.noConflict();` somewhere before it's used. In my code, I put this before the call to `addEventListener()`.

**Comment by cliren** [comment]
Thanks again! Its working. I resolved the jQuery not defined problem by making jquery available globally using webpack configuration. I really like the way skate is going, I started using this extensively and gave up waiting on other libraries.

**Comment by treshugart** [comment]
Thanks for the feedback and thanks again for raising the issue. If you have time, I'd like to hear what libraries you're using it instead of and why. It will help us improve the roadmap and vision. Cheers!

**Comment by treshugart** [comment]
I'm going to close this now, but feel free to leave feedback here.

**Comment by cliren** [comment]
I was using polymer since last year and always thought it can be simplified and be made production ready sooner. I like JS style distribution and bundling as opposed to html import style. If its a regular JS style library its easy to bundle required components into an app. With Polymer, we had to make all the components available to get served at runtime, bundling required components was not easy and the related questions were not answered quickly by polymer team.
