### ISSUE TITLE
Issue with Object literals, missing element constructors, deprecation warnings

### ISSUE THREAD

**Issue by imaustink** [skatejs/skatejs#1464]
## Bug report

I am seeing several issues when implementing `@skatejs/ssr@0.19.6` to test web components with Jest. I have installed the packages and added the following to my `package.json`:
```
"jest": {
  "testEnvironment": "@skatejs/ssr/jest"
}
```

### Current behavior

1. Object literals are no longer an instance of the `Object` constructor, e.g `expect({}).toBeInstanceOf(Object)` fails and so does `expect([]).toBeInstanceOf(Array)`.
2. Some HTML element constructors are undefined, e.g `HTMLParagraphElement === undefined`
3. I am seeing `DeprecationWarning: 'GLOBAL' is deprecated, use 'global'` and `DeprecationWarning: 'root' is deprecated, use 'global'` in the console.

### Expected behavior

1. Object literals should always be an instance of `Object`.
2. I would expect all HTML element constructors to be defined as they are in the vanilla Jest environment and in the browser.
3. No deprecation warnings. These are not originating from my code and do not happen with the vanilla Jest environment.

### Additional notes

Perhaps I am missing something? Any advice would be greatly appreciated!

**Comment by treshugart** [comment]
> Object literals are no longer an instance of the Object constructor, e.g expect({}).toBeInstanceOf(Object) fail

Interesting. We'll have to look into that but it might be because you have a different global `Object` constructor than the one that is patched in in the jest config.

> Some HTML element constructors are undefined, e.g HTMLParagraphElement === undefined

This isn't a complete DOM polyfill; it only does what's necessary and uses Undom as a base, so many element-specific constructors won't be present. Happy for these to be added in as necessary.

> I am seeing DeprecationWarning: 'GLOBAL' is deprecated, use 'global' and DeprecationWarning: 'root' is deprecated, use 'global' in the console.

Both of these don't seem to be used in the src but could be used in Undom.

> I would expect all HTML element constructors to be defined as they are in the vanilla Jest environment and in the browser.

Jest uses JSDOM which is a fairly comprehensive and standards compliant envionrment... but... you can't implement web components *on top* of it. It has to go into core, so I opted to use Undom as a base so I don't have to rewrite any of that stuff.

> Perhaps I am missing something? Any advice would be greatly appreciated!

Sorry for the delayed response. I'm happy to accept contributions if you require this functionality.

* Implementing the constructors should be pretty straight-forward.
* Deprecation warnings I believe are from other libs, but I could be wrong (I can't search the code atm).
* The `Object` constructor issue is likely originating from the patching going on in the jest config: https://github.com/skatejs/skatejs/blob/master/packages/ssr/jest.js#L9.

**Comment by treshugart** [comment]
Things we still need to do:

1. Create interfaces for all DOM elements.
2. Figure out why the Object test fails.

**Comment by imaustink** [comment]
Just so you know, I've updated my original comment because It seems I was wrong about `Array`s. They suffer from the same issue as `Object`s.

**Comment by treshugart** [comment]
I've fixed and [added tests](https://github.com/skatejs/skatejs/blob/060c6d10378b715ee4bb2f971aa5d2f9d209a54f/packages/ssr/register/__tests__/window.js#L5-L13).

**Comment by imaustink** [comment]
🎉 thank you very much kind sir!
