### ISSUE TITLE
SSR MutationObserver behavior

### ISSUE THREAD

**Issue by HarrySystems** [skatejs/skatejs#1470]
I have two questions about the current implementation of the MutationObservers:
- Why does the `_records map` receives new records with the `parentNode` as a parameter? 
   I noticed that changing multiple attributes causes this map to always have only one item, ignoring many of the mutations
- Why does the callback is called as a promise? 
   I understand that MutationObservers are async, but are they async to the layout and paint of the browser or async to your code itself?

**Comment by treshugart** [comment]
> Why does the _records map receives new records with the parentNode as a parameter?
I noticed that changing multiple attributes causes this map to always have only one item, ignoring many of the mutations

That's probably a bug in the algorithm. We should probably be pushing on the record instead of associating with the `parentNode` as this might be an issue with several child list mutations, as well.

> Why does the callback is called as a promise?
I understand that MutationObservers are async, but are they async to the layout and paint of the browser or async to your code itself?

Mutations get reported at microtask-timing. See: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/ for more info on that stuff. Promises are also microtasks, so that's used to schedule the firing of the callback as close as possible to the real thing.

**Comment by treshugart** [comment]
Set as a bug so we can investigate the MO issues you have with the single mutation record being overridden. Happy for you to fix if you're keen.

**Comment by treshugart** [comment]
So, I've looked a bit more into this. You are supposed to have a single mutation record per parent. Mutations to these observables are batched up and reported as one record per parent in the callback. Each item is a record that represents several mutations that occurred. These are batched into several parts such as `addedNodes` etc. I've referenced the commit that tests for this and I've also fixed a few other issues with it.
