### ISSUE TITLE
Replacing original element with contents of element

### ISSUE THREAD

**Issue by cliren** [skatejs/skatejs#149]
Is there a way to replace parent element with the contents of the element? For example I want to replace <my-dropdown> with my own <a> tag (I could render a dropdown or a simple anchor conditionally) so that bootstrap styles work fine here. I guess I can try $.replaceWith in created or a custom method but I don't want to use jquery.
```
<ul class="nav nav-tabs">
  ...
<li role="presentation" class="dropdown">
    <my-dropdown> </my-dropdown>
</li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
      Dropdown <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      ...
    </ul>
  </li>
  ...
</ul>
```

**Comment by treshugart** [comment]
Hey man, sorry it's taken me awhile to get back to these.

Skate won't handle this for you and it can cause some unexpected things to happen. For example, if you replace the web component element with another element, that element becomes detached from the DOM and thus its lifecycle will fully trigger and won't be available in the DOM in the attached callback if you replaced it before that.

You can try doing what you want with the native [replaceChild](https://developer.mozilla.org/en-US/docs/Web/API/Node/replaceChild):

    element.parentNode.replaceChild(newChild, element);

This is discouraged, however, since with native web components such behaviour causes the same gotchas as it would in Skate, but the ramifications could be even worse.

The best solution here is to override / extend styles from Bootstraps Less or CSS, though, it does require slightly more effort.

I'm sure the community would benefit from someone abstracting less for styling around custom elements.

Sorry if this doesn't help much.

**Comment by cliren** [comment]
Thanks, I ended up overriding styles!
