### ISSUE TITLE
Simplify prop definitions

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1499]
___This is in preview in the v6-trey branch.___

---

I'm proposing we make some simplifications to the property definitions.

## Do not nest options; everything should live at the top level.

This means stuff like `prop.attribute.target` would just become `prop.target`. I propose:

- `attribute.source` -> `source`
- `attribute.target` -> `target`

Both will become a function that takes the prop name as the only argument and returns the attribute name that should be used for the prop. The default for this would just be a `toLowerCase()` of the prop name to match what most attributes become for built-ins.

Both `deserialize` and `serialize` remain unchanged.

## Remove `coerce`

The `coerce` option has always been a band-aid for not using typed JS like Flow or TS, it incurs overhead and isn't really necessary.

## Other changes

Everything else stays the same, including using built-in types such as `String`.

**Comment by trusktr** [comment]
> The default for this would just be a toLowerCase() of the prop name to match what most attributes become for built-ins.

Because builtins do it doesn't mean we can't choose to do something better. I like dash-case: I find it easier to read and write, and aligned with Custom Element and CSS variable naming.

> The coerce option has always been a band-aid for not using typed JS like Flow or TS, it incurs overhead and isn't really necessary.

As you probably read me write in other places, we should accommodate people who don't use (don't want to use) a type system.

I think it would be great to make runtime type stuff optional, just like React makes the use of `PropTypes` optional.

**Comment by trusktr** [comment]
We should also mention in the docs how great a type system can be, and how it can help for performance, so end users can make an informed choice.

**Comment by treshugart** [comment]
Much of the simplification happened, as in it was flattened and good defaults were chosen, but we've also kept a lot of the flexibility that it already had, so no real changes here.
