### ISSUE TITLE
Props should be defined when connected

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#1500]
___This is in preview in the v6-trey branch.___

---

I'm proposing that props be defined when the first element of a particular type is connected. There's a few reasons for this:

- It's fairly hacky to do it in `observedAttributes` as we're relying on browser implementations to call this when defining.
- It's work that's done before it's really necessary.
- Props are used for rendering and re-rendering, and we don't render until connected, so we really don't need them to trigger updates until the component is ready for rendering.

**Comment by sghoweri** [comment]
In theory I think we might be ok here... I seem to recall a weird quirk of our prop-less components not rendering till we added [this check in](url
https://github.com/bolt-design-system/bolt/blob/master/packages/core/renderers/bolt-base.js#L8), however this is in our connectedCallback (and might not even be affected by this).

This one is a harder to know for certain if this will require some rework without testing this change out locally. I’ll see what I can do a little later in the week!

**Comment by treshugart** [comment]
> I seem to recall a weird quirk of our prop-less components not rendering till we added

You should be okay now as the latest stuff is calling `forceUpdate()` directly and not relying on props to implicitly invoke it. See https://github.com/skatejs/skatejs/blob/4aa99272e2a4e1fd8663464340f25c1fe6ead72e/packages/skatejs/src/component.ts#L207 for deets.

> This one is a little harder to know for certain if this will require some rework without testing this change out locally. I’ll see what I can do a little later in the week!

This branch is a bit unstable, so beware. Sorry for the delayed reply.

**Comment by trusktr** [comment]
I am in favor of this sort of thing. I've actually been thinking about this on various occasions, but haven't opened and issue or PR yet.

An obvious problem is wasting resources when `defineProps` defines props on some class when we just wanted to read the list of attributes, making extra un-used normalized props.

Also in my non-DOM cases, I was calling `connectedCallback` before ever reading `observedAttributes`, which caused `withUpdate` not to work. So if it initialized in `connectedCallback` then it would be more likely to just work.

---

The `observedAttributes` getter should still return the attributes generated by SkateJS, but it can leave normalization to `connectedCallback`. Otherwise Custom Elements won't detect the attributes.

**Comment by treshugart** [comment]
I've ended up reverting this to use the `observedAttributes` method again as the reason this was *needed* isn't part of the new API anymore.

I still find it fairly hacky, but I don't think there's any way that it can't happen as the browser needs to call this no matter what, early on.

I'll close this for now and we can revisit later if need be.
