### ISSUE TITLE
Author question: Roadmap for skatejs

### ISSUE THREAD

**Issue by cliren** [skatejs/skatejs#151]
What are some of the upcoming features? Are there any metrics on how well a component performs in different browsers?

**Comment by treshugart** [comment]
### Roadmap

As for upcoming features, skate is fairly feature-stable at this point and most features can come as helpers that hook into existing behaviour. For example, if I wanted to make parts of an element change based on attribute changes, I could write a helper:

    function html () {
      var content = [].slice.call(arguments).join('');
      return function (element) {
        element.innerHTML = content;
      };
    }

    function text (selector) {
      return function (element, change) {
        [].slice.call(element.querySelectorAll(selector)).forEach(function (descendant) {
          descendant.textContent = change.newValue;
        });
      };
    }

    skate('my-component', {
      attributes: {
        // When this attribute is created / updated it
        // will set the `textContent` of descendants
        // of the component element matching the
        // given selector to the new value of the
        // attribute.
        name: text('.name')
      },

      // When the `name` attribute changes, the text
      // content of the span below will change.
      template: html('<span class="name"></span>')
    });

Right there are two fairly useful helpers than use existing features to extend it in a functional way. At this point I'm unsure as to exactly what I want to publish and how I want to publish it (separate repos vs one helpers repo). They wouldn't be shipped with the core of Skate, though, as they're fairly simple to create and I don't want to add bloat. Skate will continue to be small, focused and designed to work with common patterns.

Something that might happen at some point, is the removal of attribute and class bindings. Class bindings because they're designed as a way to gradually move away from legacy code that uses classes to find elements to bind behaviour to. Attribute bindings are still useful for polyfilling new attribute behaviour that may not be available in all browsers we need to support. As browsers evolve, this may become unnecessary and at that point in time we'll consider removing that feature. At the point native Web Components are available in all supported browsers, Skate will still be relevant, so there aren't any plans to discontinue development in the foreseeable future.

### Perf Metrics

I don't have any published metrics, or anything I can publish at the moment. That said, though, there was extensive performance testing done to make using it in IE, in real-world applications bearable. In modern browsers, the difference between Skate and other libraries is negligible.

In IE9 Skate's internal mutation observer polyfill was about 10x faster than the one used in Polymer (circa 2 or 3 months ago). Since then, I haven't checked. I was testing with 100k elements on the page and their Mutation Observer took 40+ seconds, to completely crashing the browser. Skate's took around 4 seconds. This was simply adding 100k elements to the DOM at once; something that is costly in itself, but something that should be performant.

There's also [a bug](https://connect.microsoft.com/IE/feedback/details/817132/ie-11-childnodes-are-missing-from-mutationobserver-mutations-removednodes-after-setting-innerhtml) in IE11's Mutation Observer that require overriding of `innerHTML` and forcing Skate to use the Mutation Observer polyfill instead of native which have immediate performance implications. A entire *year* later this bug is still unfixed and even if it was there is unfortunately no way to test which service packs have been installed. Because of that, this is a blanket rule when using IE and having any component that uses the `detached` callback. That's another reason why performance was very important to us.

As browsers evolve and start to support native web components, browser metrics will be come less important especially as people start to use custom elements over attribute and class bindings.

**Comment by treshugart** [comment]
Following up on this: Skate is going 1.0 and now has an opinion on rendering. See the docs for more details, but basically it uses [Incremental DOM](https://github.com/google/incremental-dom) and a virtual DOM now.
