### ISSUE TITLE
SSR lit-html support (Jest, lit-element, SSR)

### ISSUE THREAD

**Issue by tristanMatthias** [skatejs/skatejs#1532]
## Bug report

I'm attempting to use the SSR with Jest and [lit-html](https://github.com/Polymer/lit-html) and [lit-element](https://github.com/Polymer/lit-element/). I use both lit libraries to author my components.

* Skate version: _0.19.9_
* Affected environments: Node OSX with Jest (23.6.0)

### Current behaviour

My `jest.config.js` is:
```js
module.exports = {
    "testEnvironment": "@skatejs/ssr/jest"
}
```

My Button component is:
```ts
import { LitElement, html } from "@polymer/lit-element";
import { TemplateResult } from "lit-html";

class Button extends LitElement {
    render(): TemplateResult {
        return html`button`;
    }
}
window.customElements.define('zen-button', Button);
module.exports = Button;
```

My `__tests__/button.spec.js` file:
```js
const register = require('@skatejs/ssr/register');
const render = require('@skatejs/ssr');
require('../lib/Button');

let t;

test('Created', async() => {
    const b = document.createElement('zen-button');

    t = await render(b);
    console.log(t);

    expect(b).toBeDefined();
});
```

It's failing in lit-html:
![image](https://user-images.githubusercontent.com/2550138/45924517-5edd2500-bf45-11e8-89b7-ec2459818005.png)

It's also creating the component with:
```
<zen-button><shadowroot><undefined></undefined><undefined></undefined><script>__ssr()</script></shadowroot></zen-button>
```
Do I need to call anything extra for this to work?

### Expected behaviour
I would expect this to work or for me to patch something to enable it. I realise this falls under lit-html, but thought I might ask here to see if anyones encountered this issue before.

**Comment by treshugart** [comment]
Hey @tristanMatthias and @sghoweri, I've been busy trying to get other aspects of Skate ironed out for the next release and this has sort of fell onto the back burner, and I've had less time to work on open source over the past few months, so I apologise.

It's likely that lit / lit-element are using a DOM interface that we simply haven't patched yet. Unfortunately, it doesn't seem JSDOM has landed web component support yet, which would render this library unnecessary in terms of fixing up the DOM APIs.

I'm hoping to be able to find some time to work on this package over the next month. In the mean time, if you could find where the problem lies, I'm happy to help get a fix. I'll see if I can find some time to test lit myself soon.

**Comment by tristanMatthias** [comment]
Thanks @treshugart. I'm looking forward to what you come up with! Thanks for all the work :)

**Comment by treshugart** [comment]
I've thought a bit about the roadmap for SSR support and it now sort of lands into two areas:

- Use this until JSDOM gets support
- Work on a different model for SSR in production (i.e. renderers and view libs are responsible not skate core)

Given that, it's unlikely we'll want to work real hard on patching DOM interfaces because JSDOM will be used for testing and the rest will be handled on a per-renderer basis.
