### ISSUE TITLE
Latest round of the View-Layer Olympics

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1535]
https://www.stefankrause.net/js-frameworks-benchmark8/table.html

The results are interesting. In particular, check out [solid](https://github.com/ryansolid/solid), which uses [babel-plugin-jsx-dom-expressions](https://github.com/ryansolid/babel-plugin-jsx-dom-expressions) for JSX-to-HTML-elements with fine-grained updates, and [S.js](https://github.com/adamhaile/s) for reactivity.

Not only is it fast, the language is clean and simple. The following will render an updating count of seconds to the screen.

```jsx
import S fromn 's-js'

const seconds = S.value(0)
const div = <div>Number of seconds elapsed: {seconds}</div>

setInterval(() => seconds(seconds() + 1), 1000)
S.root(() => document.body.appendChild(div))
```

It is similar to (and inspired from) [Surplus](https://github.com/adamhaile/surplus), but differs in that it uses the technique from [domc](https://github.com/Freak613/domc) (template cloning, which is faster than createElement, etc).

Check out how simple it is to [make a Web Component with Solid](https://github.com/ryansolid/solid/blob/master/documentation/components.md) (that example uses Solid's `State` helper which is effectively for making an object with S.js signals in it).

---

It would be easy to make a SkateJS renderer, but with S.js reactivity we may not need the Skate's `props` reactivity system.

@treshugart this is another reason why mixins are great, because in the case of a SkateJS renderer with Solid and S.js, we probably don't need the `props` stuff.

However, with the Skate `props` system in place, it would make end-user experience better because instead of writing things like

```js
this.seconds(this.seconds() + 1) // update the S.js reactive value
```

we could write

```js
this.seconds++
```

**Comment by trusktr** [comment]
In fact, with the new `props` system in `v6-trey`, it would be much easier to do this.

I'd still argue that things should be separate mixins, so that we can mix and match things, and most importantly, figure out what tools we like best by selecting them on a case by case basis as mixin applications.

**Comment by trusktr** [comment]
In my cases, I would still need the `props` system, as in some cases I'm using it in ways where the values don't change because they are objects, but I still need to trigger updates for subobject sub-values. In my cases, using S.js on object leaf values may make most sense.

There's lots of good food for thought over in those super fast View-Layer Olympic winners.

**Comment by treshugart** [comment]
The only *real* separation of concerns that we could have in the proposed v6 API is separating out renderer and props, yet they're still pretty tightly coupled. I might see if we can do this at some point, but the need really isn't there.

The `props` system is mean to make property getting / setting, and the API to define them consistent across any element defined with Skate. It's more for the consumer / integrating libs than the author. The not often talked about part for `props` is attributes. If you don't hook up Skate's prop system, then you have to also wire those up somehow to both updating and props.

I'm going to close this because it looks like we can integrate these as is, it's just that someone may not *want* the overhead of *props* which is negligible at worst.
