### ISSUE TITLE
The concept of "custom attributes" (an alternative or supplement to SkateJS props)

### ISSUE THREAD

**Issue by trusktr** [skatejs/skatejs#1553]
This topic is just for discussion/ideas.

Currently, SkateJS take maps attributes to props (or vice versa) to add a nice and simple layer of reactivity on top of Custom Elements.

[A-Frame](https://aframe.io), in contrast, uses a concept of "custom attributes" for reactivity. They don't call them "custom attributes", but they call them "entity components" where an HTML element is an "entity" and an attribute is a "component".

For all intents and purposes, the concept is just like @matthewp's [custom-attributes](https://github.com/matthewp/custom-attributes/), but A-Frame took the additional steps of adding a system of schemas to the attributes for deserializing attribute values into objects, meaning for example that something like `some-attribute="foo: 123; bar: 'asdf';"` (with a syntax similar to the `style=""` attribute) maps internally to an object `{ foo: 123, bar: 'asdf' }`, which is a sub-object of the HTML element called `'some-attribute'` and can be interacted with using JS like `element.getComponent('some-attribute').foo`.

So I'm wondering

- if one mechanism (props/attributes on a single element) vs the other (each attribute is a reactive object ("custom attribute" or "A-Frame component") is better
- if both mechanisms can be used together
- if this "custom attribute" or "component" idea is anything SkateJS might like to explore

---

In my [lib](https://github.com/trusktr/infamous/), I'm using a combination of SkateJS props and [element-behaviors](https://github.com/trusktr/element-behaviors), The advantage of "custom attribute" and "A-Frame components" over my "element behaviors" is that all data that is consumed by a "custom attribute" or "component" is clash-free, meaning that you pass all data to the custom-attribute/component via a single attribute value. In contrast to element-behaviors define the behaviors with a `has=""` attribute, and then the behavior instance can observe any attributes of the element that it wants to, which can be problematic if more than one behavior rely on the same attribute but expect different format of values. This problem is mitigated in custom-attributes and A-Frame components by just renaming the custom attribute or component. Renaming an element behavior does not change which attributes it observes, so in the case of behaviors, we have to take an extra step to make sure that attribute names are more unique (f.e. `material-color="pink"` instead of `color="pink"`).

**Comment by treshugart** [comment]
I see custom attributes as mixins and prefer the html element's props still be the reactive layer (as opposed to getting the attribute component and setting props on it). This has the ability to clash, but you could just add a single entry prop for your component (like sub objects) that represents the custom attribute.

This is something you can already kinda do with Skate, you just can't do custom attributes on existing html elements. You could, if the `is` attribute was stable because you'd say something like `<div is="custom-attributes" custom-attribute-1="" />`. With the current state of the spec, you'd have to settle for doing something like `<custom-attributes custom-attribute-1="" />`. This becomes less semantic, unless you want to enable this type of behaviour across several custom elements as mixins.

I don't see this happening anytime soon at the spec level and @matthewp's library is sufficient for if you do. It's compat with custom elements, so I don't see any problem with using them in tandem.

**Comment by treshugart** [comment]
I think I'll close this given I don't think there's a point in exploring this here. If there's any issue integrating the two, let's discuss later.
