### ISSUE TITLE
Recalculate style / reflow when executing Skate

### ISSUE THREAD

**Issue by iangrunert** [skatejs/skatejs#166]
On skate version 0.9.0, when executing the skate javascript a reflow / recalculate style event occurs.

This might be due to the style element that's appended to the document, though I'm not 100% sure.

![reflow in browser dev tools](https://cloud.githubusercontent.com/assets/2259495/7081450/a4dd91b4-df85-11e4-8de4-c8ef5ac224c5.png)

**Comment by treshugart** [comment]
I think you're right in that it's because of that. That's one of the reasons that was removed from that minor dev version. From 0.10 on, style elements are no longer added to the DOM. It now uses something similar to how Polymer handles FOUC by adding / removing attributes on the element.

I'll leave this open until we can confirm that this is not happening in 0.10+.

**Comment by treshugart** [comment]
I can't reproduce this in later versions so I'll close for now. If this happens in versions that aren't doing that silly style insertion then please reopen. Thanks!
