### ISSUE TITLE
events object can't be used for shadow DOM children

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#197]
Currently any properties in the `events` object will be consumed by skate assuming the custom element is not using shadow DOM for its contents, so shadow DOM children can't be selected using the current API (though the host element itself can, by only providing the event string).

**Comment by treshugart** [comment]
That's due to event retargeting. See: http://output.jsbin.com/qidisu/4. Skate checks `e.target` but doesn't check `e.path`.

If you're using native Shadow DOM, or the polyfill, you should be able to use the `::shadow` pseudo element selector.

```js
...
events: {
  'click my-el::shadow button': handleShadowButtonClick
}
...
```

Since Skate uses the [native `.matches()` method (normalised to a function for browser prefixes)](https://github.com/skatejs/skatejs/blob/master/src/lifecycle/events.js#L16) using this selector should just work when using native or polyfilled Shadow DOM.

**Comment by treshugart** [comment]
@marcoms I've issued a PR for supporting this: #198. Have a look at the test cases and see if you can think of any other scenarios.

**Comment by treshugart** [comment]
Also, that PR assumes that if you're using Shadow DOM selectors that you are either using native or a polyfill that supports those features. If you use a Shadow DOM selector and you're in a browser that doesn't support Shadow DOM or you're not using a polyfill, there will be errors.

**Comment by marcoms** [comment]
I haven't been able to use `'click my-el::shadow button'`-esque method using the latest .13.4 release as you describe. Am I misunderstanding?

**Comment by treshugart** [comment]
I redacted that comment. See the edit. Also, there's a PR for master that I linked for you to have a look at if you want.

This functionality will be in a 0.14 release.
