### ISSUE TITLE
RFC - skate.html()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#212]
For setting innerHTML and initialising at the same time.

```js
skate.html(element, html);
```

**Comment by marcoms** [comment]
So `skate.html("x-foo", "[innerHTML]")`, equivelant to:

```
let xFoo = document.createElement("x-foo");
xFoo.innerHTML = "[innerHTML]";
```

?

Sounds good to me

**Comment by treshugart** [comment]
@marcoms It'd be more like:

```js
var el = skate.create('my-element');
el.innerHTML = '<some>content</some>';
skate.init(el);
```

Since we're offering `skate.create(elementName)`, it'd be a way to create a method using html. Not sure if it's worth bloating the API. Do you think it'd be useful?

**Comment by marcoms** [comment]
It's definitely useful, however I think since its in the same scope of element creation, and `.html` doesn't really have explicit meaning that it will create an element to me, I like it better in `skate.create`, either by adding an optional argument, or by redefining the semantics of the first argument (I prefer the former)

```
skate.create("x-foo", { [props] }, "<span>innerHTML goes here</span>");

// or

skate.create("<x-foo><span>innerHTML goes here</span></x-foo>", { [props] });
```

...Or the function could just be renamed, but I still think that it would be duplicating some of `skate.create`'s functionality

(since `skate.init` is not yet fully documented, I assume that it explicitly runs the element's `.created` handler, `.template`, etc.)

**Comment by treshugart** [comment]
The former is explicit, but I try as much as possible to stay away from creating anything more than a dyad in public APIs if possible. What about overloading the first argument?

- If the first character is a `<`, then create an element from HTML.
- If it is not a `<`, then create an element using the provided string as the element name.

**Comment by marcoms** [comment]
That sounds like a good solution to me. I suppose that skate should also check for well-formed HTML (has a closing tag, etc.) if the first character is a `<`.

**Comment by cyberdash** [comment]
This sounds useful to me. I can think of a few use cases for this in components I've written.

**Comment by treshugart** [comment]
@cyberdash if overloaded like that, we'd probably be specifying the "outer html" of the element and it'd return you the element already initialised. It'd be similar to specifying HTML to the `jQuery()` function.
