### ISSUE TITLE
Typical methods of deleting a property propagate non-ideal results to attribute

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#223]
```js
> delete elementInstance.customProp;
false

> elementInstance.customProp = undefined;  // -> <x-element custom-prop="undefined"></x-element>

> elementInstance.customProp = null;  // -> <x-element custom-prop="null"></x-element>
```

I would expect if the property is set to undefined for the attribute to be removed, however there is no way to achieve this without adding custom behaviour to the properties setter method to directly call `removeAttribue`, if the setter is given null or undefined as a value.

AFAIK there is no way to have the `delete` operator work as desired since you can't overload it, but I believe the last two are feasible.

**Comment by treshugart** [comment]
I originally didn't implement this because it contradicts native behaviour for non-boolean attributes.

![screen shot 2015-06-22 at 10 02 24 am](https://cloud.githubusercontent.com/assets/136556/8273943/d99e0e96-18c5-11e5-99a2-80e5e18dbb89.png)

I have no idea why someone would want to set a linked property to `undefined` or `null` and want the value to be a stringified version of that, but native doesn't behave that way. Maybe that's a good thing if we fix it because (IMO, at least) native behaviour is unintuitive.

Currently we can `el.removeAttribute('custom-prop')` and it will set the value of the property to `null`, so it would make sense for it to be the other way around.

Personally I like using `undefined` rather than `null`. Maybe we should normalise all unset values to be `undefined` as part of this instead of `null`?

**Comment by marcoms** [comment]
I also think `undefined` is the better choice here.

Do you aim to patch `setAttribute` itself or alias `undefined` to `removeAttribute` calls?

**Comment by treshugart** [comment]
`undefined` it is then!

I don't think patching `setAttribute()` is a good idea because it would completely rewrite the native behaviour. Doing this from a property perspective, though, I think is ok, especially since we define custom behaviour for our properties that are documented.

**Comment by treshugart** [comment]
PR'd in #227.

**Comment by treshugart** [comment]
In master now. Both `undefined` and `null` when set on a property will remove the linked attribute.
