### ISSUE TITLE
Use .className instead of attributes['class'] in CLASSNAME binding type.

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#229]

**Comment by alexreardon** [comment]
Why not `classList.contains`?

**Comment by treshugart** [comment]
Because IE9.

**Comment by alexreardon** [comment]
Yep:

```
function getClassList(element) {
    var classList = element.classList;

    if (classList) {
      return classList;
    }

    var attrs = element.attributes;

    return attrs['class'] && attrs['class'].nodeValue.split(/\s+/) || [];
  }
```

I actually like this one. No penalty for newer browsers. 

One observation though: for newer browsers you will get a `DOMTokenList` which has the `contains`, `add`, `remove` and `toggle`. If no `element.classList` it will just return an array. For api consistency, perhaps instead of returning the `DOMTokenList` just return an array `Array.from(element.classList)`. That way the function always returns an array

**Comment by treshugart** [comment]
That's possible but `Array.from()` requires a polyfill and this is performance critical code.

**Comment by alexreardon** [comment]
My apologies, I thought this file was transpiled. Perhaps:

```
Array.prototype.slice.call(element.classList)
```

**Comment by alexreardon** [comment]
My only concern is that this function has an inconsistent return type. Sometimes a `DOMTokenList` and sometimes an `Array`

**Comment by treshugart** [comment]
Your concern is valid. It's only used internally to that file, so I think having that difference is ok. Re transpilation, you have to include polyfills for ES6 features; unless Babel will auto-include it (it very well might, not sure).

**Comment by treshugart** [comment]
Fixed in: https://github.com/skatejs/type-class/commit/4677c5bd3433fa7e227937ce3059ca0c9fda4f07.

**Comment by treshugart** [comment]
This actually ended up breaking a test. It's because svg elements don't have the `className` property. Reverting.
