### ISSUE TITLE
RFC: apply skate.ready's semantics to all component callbacks

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#242]
Most of my callbacks interface with the component's shadow DOM in some way, and as explained in Skate's readme, the parent is upgraded before its children in browsers natively supporting custom elements. As a result, without `skate.ready` in use, children elements return unpredictable values (in most cases `undefined`) when accessing attributes etc. when a callback is run before children are upgraded.

For me then having children upgraded before running callbacks would remove a lot of code burden since there is less to think about. ("do I access custom element children in this function? If so, is it wrapped in `skate.ready`? ...")

Hopefully others can share their opinions.

**Comment by treshugart** [comment]
@nicolasv would be a good one to weigh in here. I've actually been thinking the same thing as you here but have been playing with the idea of forcing children to be initialised before parents. This is possible since when they'd naturally be fired by native means, Skate would just no-op. This also gets around potential issues with firing on ready. For example, if the DOM was ready and you set the innerHTML of an element, parents would still be initialised before the children.

**Comment by treshugart** [comment]
We might actually need a combination of both. I've ran into issues with putting component definitions at the bottom of the page. If you load a parent component before a child component, the parent will be upgraded sync before the child definition loads. Using `ready` would get around this. We may still have to force init children, though.

**Comment by treshugart** [comment]
Doing a hack day to spike lifecycle consistency tomorrow. Hopefully we'll have a resolution for this.

**Comment by treshugart** [comment]
Closing this because #258 makes it redundant.
