### ISSUE TITLE
Required properties and the 'type' key

### ISSUE THREAD

**Issue by alexreardon** [skatejs/skatejs#246]
This is more a question for discussion, but would it be worth adding a mechanism to specify some attributes / properties as **required**?

**Comment by treshugart** [comment]
Few questions for ya:

- What would the API look like?
- How would this impact the consumers and the users? Throwing errors? Logging warnings? Alerts (very kidding)?

I'm somewhat hesitant because part of good API design is to provide good defaults. For example in native HTML `<input>` is equivalent to `<input type="text">`. Providing a way for a developer to be lazy and not provide those defaults and pass that burden onto the consumer may not be idea.

**Comment by alexreardon** [comment]
Personally I lean towards the `react` syntax for `type` (which I think it is a little confusing in `skate` at the moment). If we did this then we could also get the `required` behaviour for free. I have had a play with it and it feels really nice.

https://facebook.github.io/react/docs/reusable-components.html

```js
React.createClass({
  propTypes: {
    // You can declare that a prop is a specific JS primitive. By default, these
    // are all optional.
    optionalArray: React.PropTypes.array,
    optionalBool: React.PropTypes.bool,
    optionalFunc: React.PropTypes.func,
    optionalNumber: React.PropTypes.number,
    optionalObject: React.PropTypes.object,
    optionalString: React.PropTypes.string,

    // Anything that can be rendered: numbers, strings, elements or an array
    // containing these types.
    optionalNode: React.PropTypes.node,

    // A React element.
    optionalElement: React.PropTypes.element,

    // You can also declare that a prop is an instance of a class. This uses
    // JS's instanceof operator.
    optionalMessage: React.PropTypes.instanceOf(Message),

    // You can ensure that your prop is limited to specific values by treating
    // it as an enum.
    optionalEnum: React.PropTypes.oneOf(['News', 'Photos']),

    // An object that could be one of many types
    optionalUnion: React.PropTypes.oneOfType([
      React.PropTypes.string,
      React.PropTypes.number,
      React.PropTypes.instanceOf(Message)
    ]),

    // An array of a certain type
    optionalArrayOf: React.PropTypes.arrayOf(React.PropTypes.number),

    // An object with property values of a certain type
    optionalObjectOf: React.PropTypes.objectOf(React.PropTypes.number),

    // An object taking on a particular shape
    optionalObjectWithShape: React.PropTypes.shape({
      color: React.PropTypes.string,
      fontSize: React.PropTypes.number
    }),

    // You can chain any of the above with `isRequired` to make sure a warning
    // is shown if the prop isn't provided.
    requiredFunc: React.PropTypes.func.isRequired,

    // A value of any data type
    requiredAny: React.PropTypes.any.isRequired,

    // You can also specify a custom validator. It should return an Error
    // object if the validation fails. Don't `console.warn` or throw, as this
    // won't work inside `oneOfType`.
    customProp: function(props, propName, componentName) {
      if (!/matchme/.test(props[propName])) {
        return new Error('Validation failed!');
      }
    }
  },
  /* ... */
});
```

**Comment by treshugart** [comment]
While it's nice, I reckon that would open a whole can of worms and bloat. Good idea for a separate module, though!

I disagree with the fact that it's confusing, though, but maybe that's because I see everything as a function. That's why you can do:

```js
skate('my-element', {
  properties: {
    prop: {
      type: Boolean
    }
  }
});
```

or even:

```js
function required (type) {
  return function (value) {
    if (value === undefined) {
      throw new Error('Required property not specified.');
    }
    return type(value);
  }
}

skate('my-element', {
  properties: {
    prop: {
      type: required(Boolean)
    }
  }
});
```

I don't think this will be something that goes in core Skate, but definitely an awesome idea for a separate module. The benefit of a separate module is that it can work with anything since it's just functions.

**Comment by alexreardon** [comment]
The challenge is that `type` can actually modify the property. I would expect `type` to just be a function that returns `true` or `false` and have some associated behaviour, rather than being a transformer of the data itself
