### ISSUE TITLE
Just use an option instead of the first argument to skate().

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#247]
It seems simpler to just have the component ID as part of the definition since we need it on there anyway.

```js
skate({
  id: 'my-element'
});
```

Naming is hard:

- `id`
- `name`
-  `is` (Polymer)

**Comment by marcoms** [comment]
`name` sounds more self-descriptive and clear to me. `id` and `is` could be a bit confusing as there are already attributes defined with those names.

**Comment by marcoms** [comment]
FWIW, I prefer having the component name as the first arg to skate, since it makes it clear that it is a required and core part of the component, as opposed to it being in an object with configuration entries that may or may not be present (this is what I associate function-argument objects with, anyway).

When Polymer made this change (0.8 release or something) I had the same feeling, however for Skate this may be beneficial if only to make migration from Polymer easier

**Comment by treshugart** [comment]
I tend to agree. If you're migrating from Polymer, there's going to be more than that you'd have to worry about anyways. It would also make extending a bit weird because you'd have to put the `name` on your class and ensure to override it. Small quibbles, but after playing with it I think we'll stick with it as the first parameter.
