### ISSUE TITLE
Allow multiple registration of custom attributes with the same name

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#262]
This:

```
skate('target', targetAttributeDefinition1);
skate('target', targetAttributeDefinition2);
```

causes error of duplicate definition.

And why it shouldn't is that many different behaviors can be attached to a attribute. A good example is the `target` attribute of anchors. I use two specific cases:  

1. `target=modal` which simply uses the `href` as a selector for an element that will be shown in a modal
2. `target=select-dropdown` which uses the `href` as a selector for a select2/selectize widget and then adds whatever is the anchor's `value` attribute as a selection to the dropdown.

I think, these are two completely different but still valid behaviors. Am I missing something?

**Comment by treshugart** [comment]
The reason it throws an error is to not stray too far from the custom element spec. You can't define multiple definitions for the same tag name in native custom elements so doing it for other types of definitions then diverges from that idea. I'm wary of straying too far from the spec even though attributes and classes are already different.

In master, binding types have been abstracted into separate repositories. The only binding type that is bundled is the element type. This means that Skate, by default is a custom element library that you can author your own types for. Maybe it's worth moving the check for existing registrations into the binding types so that for custom elements you can only have one behaviour but for attributes and classes you can have multiple.

It's an idea worth bringing to the table and exploring and maybe even having binding types manage their own registries instead of having a global one. The only thing making this difficult is that native custom elements has a global registry that you still have to worry about in the element binding. Maybe this is ok, but it's hard to say if this will end up working out at this point without spiking some ideas.

Hopefully that brain dump makes sense. What are your thoughts?

**Comment by treshugart** [comment]
I should add that being able to bind multiple behaviours to an element implicitly as such takes away from the benefits and expectations one can have from explicitly binding behaviour. Another way of doing what you want might be to have separate attributes for each binding. Instead of using `target`, do something like:

```js
skate('modal', ...);
skate('select-dropdown', ...);
```

Which changes your HTML declaration to:

```js
<div modal>
// or
<div select-dropdown>
```

Or if the developer wants to use both:

```js
<div modal select-dropdown>
```

I'm not sure if that fits your use case since both of ours seems a little contrived.

If your binding multiple behaviours because the latter behaviour requires the former behaviour to be present, using inheritance, or having a super-component that composes their behaviour together would probably be a more robust solution. Something like:

```js
import modal from './modal';
import selectDropdown from './select-dropdown';

skate('target', {
  created: function () {
    modal.created.call(this);
    selectDropdown.created.call(this);
  }
});
```

**Comment by antitoxic** [comment]
I got your point. It's good not to add too much stuff baked in. I guess `<div select-dropdown>` is the better way to do it because it's more familiar to coders (*at least those that have been working with anguar directives*) that just a value of a single attribute.

I'm closing the issue. 

I'm still using single `target` attribute for several behaviors though. May be it's my twisted mind but I really like the natural feeling of:
```
<a target=blank # native browser
<a target=popup # native browser
<a target=modal # custom, opens content in modal/lightbox
<a target=<anyelement> # custom, the attribute marks the current element as a trigger point targetting another
```

My point of view is that html already have the concept of changing behaviour based on attribute value, not just attribute name. Example would be `type=checkbox` , `type=password`.

Also I try to avoid:
```
skate('target', {
  created () {
    modal.created.call(this);
    selectDropdown.created.call(this);
  }
});
```
This doesn't allow me to encapsulate different behaviour. I'm already using a wrapper of skatejs that simplifies some of my development. Now, i'm using this wrapper to keep a registry of all custom attributes and when I call `mywrapper('attrName', definition)` twice it stacks both in 1 callback.

Hope this is not completely wrong.

**Comment by treshugart** [comment]
Ahh ok, I see your use case. You're not doing anything wrong; what you're doing is valid and can be achieved in a number of ways. One way would be to do what you're doing. Another might be to encapsulate the behaviour inside of a component with a custom property (on master, previously attribute handlers in <= 0.13).

```js
import typeAttribute from 'skatejs-type-attribute';

var targets = {};

export default skate('target', {
  type: typeAttribute,
  properties: {
    target: {
      attr: true,
      set (name) {
        if (targets[name]) {
          targets[name](this);
        }
      }
    }
  },
  registerTarget (name, handler) {
    targets[name] = handler;
  }
});
```

The reason we haven't implemented allowing multiple definitions is that it opens up a lot of questions around how the lifecycle of the component is managed when it is mutated. Removing and re-adding events, properties, re-templating, undoing the `created` callback and updating the prototype chain all become things that have to be handled.

You also can't handle the situation where `target` may not exist but you want to have a default value or behaviour for it. Probably not for this use case, but that's definitely a use case for the native `<input>` element.

There's some more issues that we've actually discussed at some length in the past and have decided to err on the side of simplicity and to stay as close as possible to the custom element spec. A lot of behaviour would require putting more and more logic into the binding types, which isn't necessarily a bad idea. If you'd like to spike any ideas, please feel free to do so.
