### ISSUE TITLE
Skate properties missing from API

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#267]
Not sure if I'm going crazy or not, but from recent testing, I can't access some of skate's API, such as `skate.ready`, and `skate.chain`

```js
console.log(skate.ready);  // undefined
console.log(skate.chain);  // undefined
```

http://codepen.io/marcoms/pen/aOPjRe

**Comment by treshugart** [comment]
No you're definitely not crazy. We've been playing with the API and trying to get it to a point where we expose enough Skate specific API but not too much stuff possibly better left to other libs.

`skate.ready`

This was removed because we needed a simpler way to write lifecycle code. It was decided that we should either have a `ready` lifecycle callback like Polymer, or to make `created` behave as one would expect rather than be all over the place like in native custom elements. `skate.ready` was a spike we were dogfooding internally to see if it was useful. Fortunately we were able to simplify the API so that `created` behaves as one would expect. For more information on that see: https://github.com/skatejs/skatejs/pull/258.

`skate.chain`

I actually really liked this, but most - including myself - felt it was too abstract to be part of Skate's mission, even if it were to use it internally. Internal things that were using this went back to just supporting a normal function.

If you have an objections or want to weigh in on those decisions, please feel free. The chain utility, if anything, would be useful as a separate lib for composing behaviour. I'm not sure there's really a use for `skate.ready` anymore, though.

**Comment by treshugart** [comment]
I forgot to add that master will be updated prior to the 0.14 release with an upgrade guide.

**Comment by marcoms** [comment]
Nice. I'm fine without skate.ready since #258 replaces my use-case for it.

Should I close #242 since #258 basically fixes it?

**Comment by treshugart** [comment]
Ha! I probably was closing both #241 and #242 as you were typing that comment. Since you seem to be running off bleeding-edge Skate, I'd be interested to see how #258 works for you.

Any thoughts about `skate.chain()` being removed?

**Comment by marcoms** [comment]
I've never used `skate.chain()` myself, so I don't feel too strongly on whether it gets removed or not.
