### ISSUE TITLE
created function called after property initialisation

### ISSUE THREAD

**Issue by marcoms** [skatejs/skatejs#285]
It seems that skated elements' created callbacks are now executed *after* properties are initialised. Not sure if this is intended behaviour or not..?

**Comment by treshugart** [comment]
Yeah, it was intentional, but I'm remembering you raised #179 awhile back. Is this biting you in the ass? It'd be good to discuss the benefits and caveats of its placement.

Pros:

1. Everything is set up for you by the time created is invoked.
2. If you use `template` and `properties` together, `created` may rarely be needed.

Cons:

?

Not sure yet because any property behaviour I put in the property setter. I rarely have to use the `created` callback, but I see it useful for edge cases.

Ideas?

**Comment by treshugart** [comment]
We used it during ShipIt (Atlassian's hackathon) and came to a fork in the road on this. Thought this is different from what you've described, I feel that it relates to it. What we decide here will ultimately decide the fate of this issue.

### Before `template`

Your template can be rendered dynamically, however, you cannot make alterations to the template on property initialisation as the templated nodes wouldn't exist yet. Modifications after `template` has been called will work.

This means your DOM alterations all go in `template`. If you need to re-render your template when a property changes you must call `template`; you should not use property setters to do this. This isn't all bad, but if you're doing bare-bones templating, you're smashing the DOM pretty hard. It does make for less side-effects and you can use a DOM diffing library if you don't want to thrash it. For most use-cases, this is probably a fairly practical approach.

### After `template

DOM modifications can be done piecemeal from within your property setters without worry that the template won't be there when they're initialised. You may use them in your templates, but their initial values won't be ready when `template` is called. If you want them to affect your template, then you will have to ensure that the renderer is called when properties are updated.

### My feelings

Up until now, I felt that properties should be initialised after `template` because I like putting my DOM alterations in the setters. However, this creates a lot of side-effects. It does initially help save you from yourself so you don't have to re-render an entire template for a small change, but you can ensure the DOM isn't thrashed from within whatever rendering engine you use within the `template` callback. 

My vote: before `template`. This means that properties will also be initialised before `created` which is what you originally had concerns about. What are your thoughts.

cc @alexreardon.

**Comment by marcoms** [comment]
Well I actually worked around properties being initialised before created by moving `created` code into `template`.

At the end of the day, I don't mind too much whether property init goes before or after `created`, however having properties initialised before template poses some problems for me (having always had DOM mutation in property setters):

- property callbacks can't assume anything about the component (e.g. `if(this.shadowRoot) ... else return`). AFAICT this means that property initialisation code that touches the DOM will have to be deferred to `template`/`created` and be duplicated.

- as mentioned in the previous point, properties will have to be initialised in `template` or `created` if they touch the DOM - lots of `if(myProp) ...; if(otherProp) ...` etc.

The above are only issues clashing with my current usage of skate however, since I don't avoid staggering DOM reads/writes in property setters. With your proposed solution of only re-rendering the DOM in `template` (I assume this implies limiting property setters to invoking `template` and computing its own value), do I understand it correctly to look something like this:

```js
properties: {
  red: {
    attr: true,
    set() {
      this.template();  // not sure how I would call template properly
    },
},

template() {
  if(!this.shadowRoot) this.shadowRoot = `
    <style>
      .red { color: red; }
    </style>

    <span id="text"><content></content>!</span>
  `;

  if(this.red) {
    this.shadowRoot.getElementById("text").classList.add("red");
  } else {
    this.shadowRoot.getElementById("text").classList.remove("red");
  }
},
```

I wasn't aware that `template` could be called after it is initially executed to make this all possible - how would I go about doing this?

**Comment by marcoms** [comment]
Quick question - if `template` is to be called inside property setters that require it, what difference does it make whether it is before or after `template`? If property initialisation happens after `template`, then the initial `template` call won't have access to property values, but it will be called again anyway by the property setter.

**Comment by treshugart** [comment]
Your last comment is correct. If you re-render the template after a property is set up it doesn't *really* matter. However, the first time your template renders it would be needless. 

### RFC

Maybe we should adjust the lifecycle callbacks to be in this order:

1. `created`
2. `events`
3. `properties`
4. `template` -> `ready` (renamed to be less specific since you can do more than templating at that point)

Basically, this means `created` is the first to happen and `ready` is the last. Everything else goes in between. If you want to template before props are initialised, you template in `created`. If you want to template after propers are initialised you then template in `ready`.

### Re-rendering

*All code and terminology beyond this point will use the suggest callback order and naming above.*

Template rendering is just a function that uses the element as `this`. This means that you can call that same function in your property setters, or anywhere you'd need to. If you were to use `properties` in your `ready` callback in your code example above, you could rewrite it like:

```js
properties: {
  red: {
    attr: true,
    set () {
      // Or you can define your `template` function
      // in the outer scope so it can just be called
      // like a function instad of having to do this.
      this.constructor.ready.call(this);
    },
},

// Runs before `properties`.
created () {
  this.createShadowRoot();
},

// As proposed: `template` -> `ready`.
// Runs after `properties`.
ready () {
  this.shadowRoot.innerHTML = `
    <style>
      .red { color: red; }
    </style>
    <span id="text" class="${this.red ? 'red' : ''}"><content></content>!</span>
  `;
}
```

However, you suggested in #269 that we reinstate property events. If we did that (I'm experimenting with it right now, actually) then you wouldn't have to manually re-render. All you'd need to do is listen for the event and re-render. This could be abstracted into a function (this is what I'm working with right now):

```js
function createShadowRoot (elem) {
  if (!elem.shadowRoot && elem.createShadowRoot) {
    elem.createShadowRoot();
  }
}

function getShadowRoot (elem) {
  return elem.shadowRoot || elem;
}

function createTemplate (handler) {
  return function (parse) {
    function render () {
      // Uses Shadow DOM if available.
      createShadowRoot(this);
    
      // Initial render.
      handler.call(this, parse.call(this));

      // Re-render whenever a property event occurs.
      this.addEventListener('skate.property', render);
    }
    return render;
  };
};

var template = createTemplate(function (html) {
  // Use Shadow DOM if available.
  getShadowRoot(this).innerHTML = html;
});

skate('my-element', {
  ready: template(function () {
    return `
      <style>
        .red { color: red; }
      </style>
      <span id="text" class="${this.red ? 'red' : ''}"><content></content>!</span>
    `;
  });
});

**Comment by antitoxic** [comment]
On similar but not entirely matching query: I vote for properties being initialized before the template is called.

Right now I don't have access to defined properties (via `properties:`) in my template callback.

**Comment by antitoxic** [comment]
Sorry, spoke too soon. In latest master version properties are initialized before template is run. I was using 2e0b4895add2229c635461cb7e80e109ae6c09be .

**Comment by marcoms** [comment]
Your proposed lifecycle order seems pretty sound.

>However, you suggested in #269 that we reinstate property events

I thought that property events were already present in skate via `notify`? Can't your example of automatic re-rendering be accomplished in skate's current state?

**Comment by alexreardon** [comment]
Having access to the element before and after bindings looks appealing @treshugart. I think there is a still a bit of uncertainty about where `template` fits into the lifecycle. My understanding is that the `template` function will be removed all together and either you stamp out your own template in `created` or `ready` as you see fit. Is that correct?

**Comment by treshugart** [comment]
That's correct, @alexreardon. Skate doesn't make any assumptions about templating so why should we call it template?

**Comment by alexreardon** [comment]
![i like it](http://i1248.photobucket.com/albums/hh488/ifoundcallie/101379-Jim-Carrey-I-like-it-alot-gif-GflM.gif)

**Comment by alexreardon** [comment]
:+1: ship it

**Comment by alexreardon** [comment]
Only issue I can see is backwards compatibility. Existing `created` callbacks would not work as expected. `template` could just be mapped to `ready` so no big issue there.
