### ISSUE TITLE
How to distingish between an element that was detached and attached and a cloned copy of it?

### ISSUE THREAD

**Issue by antitoxic** [skatejs/skatejs#296]
Let's have an element `<custom>` and its callback `attached`. The callback will do some behavior initialization. During the lifetime of the page `<custom>` can be moved around the dom tree, i.e. it will be detached and then attached again. 

Now, let's clone this element (`custom.cloneNode()`) and attach the clone to the body. Attached is called again.

The question: how do I know in the `attach` callback whether the element is a copy which has not been initialized?

**Comment by antitoxic** [comment]
I'm thinking setting a property (not attribute) like so:
```js
attached: function() {
  if (this.isAttached) return;
  this.isAttached = true;
 ... attach logic ...
}

**Comment by treshugart** [comment]
That'd be one way to do it. What your use case?

**Comment by antitoxic** [comment]
I'm using `attached` callback to apply jQuery plugin behavior (*I know it's a framework but some plugins like magnificpopup or parsley cant be replaces with native js packages easily*). And then throughout the life cycle of the page I clone the element to alter some of it contents and reuse it for another purpose.

**Comment by treshugart** [comment]
Yeah, that'd probably be the best way to do it. I've thought about adding something like an `attachedOnce` callback but it doesn't make sense because you should be undoing your `attached` changes in `detached`. Of course, jQuery plugins are the exception to this rule if they require something to have layout and they don't give you a way to unbind stuff.

I'd recommend that if possible, always use the `created` callback for this. The exception being when you need dom attachment. If you can't cleanup after yourself, using the `if (this.isAttached)` is perfectly fine.

**Comment by antitoxic** [comment]
Cool :)
