### ISSUE TITLE
Property updates

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#464]
Rename:

- `created` -> `defined`

Add:

- `created` (aka added) when the property is set to a non-empty value from an empty value
- `updated` when the property is updated and the old value is non-empty and the new value is non-empty
- `removed` when the property is set to an empty value

This restores the old attribute API and adds convenient hooks for property authors to use instead of having to do the logic themselves within the setter.

**Comment by marcoms** [comment]
Between this and set(), I don't mind so much (though I do prefer the cleanliness of set()). What I worry about is the inconsistency that comes from different property types when this is used.

E.g. boolean properties are set to false by default, whereas others have no default set.
If I wanted to have a callback execute whenever the property is set by someone, for booleans I would have to bind to updated, while for anything else I would have to bind to created and updated, because boolean properties have to default to false (not exactly common knowledge). I would think this could be a little bit confusing to those reading or maintaining the source code.

This problem also extends to the current situation of set() to a degree (though I think the proposed change would make it more evident), as I would have to manually check for change.oldValue to see if it was called by setting the default or by a natural change.

Either way, I think there should be some explicit distinction between the default value being set and the property naturally being set. At the same time, the developer can specify any events that would trigger the desired callback (perhaps with the old `"created updated": ()=>{}" ` system)

Apologies for the ramblings, this was written at night. Hopefully tomorrow I'll be able to convey my thoughts more clearly!

**Comment by treshugart** [comment]
@marcoms 

Maybe the best solution here would be to make a simpler addition that solves your problems here as they reflect some I've had when building large apps.

I see a couple of options so far:

1. Only trigger the `set` for actual sets (the default value doesn't count).

Pros

- More clear intent when reading the template.
- Less API surface area.

Cons

- Breaking change.
- Logic in `render` (for default values) and in `set` (for updates).

2. Add an `update` (or `updated`, `change`, `changed`) callback that only fires when it's actually set.

Pros

- Explicit callbacks.
- No doubled up logic. If you want all sets, bind to `set`. If you only want updates, then `update`.

Cons

- More API.
- No logic in `render` (not as clear, but possibly subjective).

Thoughts?

**Comment by marcoms** [comment]
Assuming that "actually set" means any property change that isn't setting the default value, then your `update` proposal sounds good. Having property logic delegated to their respective property objects I prefer to bundling property logic in `render()`.
The issue is the limited name choice we have, IMO. Since the property doesn't necessarily have to be 'updated' (it can be set from no value to begin with), we are left with choices like changed and assigned, which still aren't technically correct if you think about it. If we were to pick changed for example, i could imagine developers trying to pick up skate that would have quite a hard time trying to distinguish between `set` and `changed`.

I've been thinking about an alternative where we could introduce another callback (~~`initialised`~~`initialized`?) which is invoked only for setting the default value. Unfortunately this implies a breaking change, in that `set()` is reduced in scope to only natural property changes.

**Comment by treshugart** [comment]
Closing this as I think I don't think it's really necessary at this point.
