### ISSUE TITLE
Any plans for out-of-box content distribution solution?

### ISSUE THREAD

**Issue by krzksz** [skatejs/skatejs#497]
Hello! First of all I'd like to say that I'm very impressed by your incredible work guys! 

I discovered `skatejs` when I was searching for a library that would allow me to assign web component to a class, not only tags and attributes and it seems perfect in doing its job. First thing I decided to do was to make a little exercise comparison on different implementations of the same component in both `polymer` and `skatejs`, [here you can see my attempt](https://plnkr.co/edit/a4Y31PG9QZ3b5ESuW1zt?p=preview). 

The problem is that while `polymer` supports some(even outdated) kind of content distribution `skatejs` does not. I've even tried to work around it with `shade` but with more complexity and no luck :disappointed: I can see there is some [polygap](https://github.com/skatejs/named-slots) from you guys, but from what I'm seeing in docs its behavior differs from the one proposed in [Shadow DOM working draft](https://www.w3.org/TR/shadow-dom/#slots).

I don't need Shadow DOM features, HTML imports and numerous polyfills `polymer` tries to provide with negative performance impact. My main goal with web components is to hide implementation details from the user(as seen in my carousel example) with content discribution, so are there any plans for that? Is there any way I could help?

**Comment by treshugart** [comment]
Hey @krzksz, thanks for the kind words.

Shade is deprecated. I'm not surprised you couldn't get it working. It was an exploration that didn't really work out. I thought we had marked it as such. Sorry if not.

The named-slot polygap has a slightly different API than the latest drafts and is designed to be a subset rather than a complete polyfill due to rising complexity and performance issues with certain aspects of polyfilling. We wanted a minimal distribution algorithm that was performant without the rest of the features that allows us to expose a way for our component consumers to add content to our elements as if they were dealing with a ckmponent that had a shadow root. Certain properties work such as childNodes and children but things like querySelector probably won't ever be polyfilled due to complexity and performance.

If you'd like to chat about specifics, ID be more than happy to.

Best way to help would be to discuss ideas with us and if you've any fixes / improvements, raise issues or PRs.

**Comment by treshugart** [comment]
I just updated the docs at https://github.com/skatejs/named-slots/ to reflect the latest API.

**Comment by krzksz** [comment]
Thank you for your response @treshugart! As I said before, right now I have no need for complex features that would include heavy polyfilling. I see skatejs as a great library that would allow us to find a compromise between performance, dividing web into components that hide unnecessary logic from user and not braking existing libraries that depend heavily on light DOM.

I tried some of the examples you posted and unfortunately couldn't get them to work using ES5. That said I will try them along with some ES6 transpiler and report my findings in appropriate repo.

**Comment by treshugart** [comment]
No probs @krzksz. I checked the dist and it was broken which could have given you problems. Sorry :(. I've updated the docs to include an updated working example and some notes about why we "polyfill" it the way we do and some notes on performance.

**Comment by treshugart** [comment]
Just following up here, Skate is going 1.0 and now has an opinion on rendering. It's using [Incremental DOM](https://github.com/google/incremental-dom) as a virtual DOM layer. Docs are all up to date. Let us know if there's any questions.
