### ISSUE TITLE
Property change event

### ISSUE THREAD

**Issue by jpnelson** [skatejs/skatejs#513]
It'd be useful to have a property change event for creating stateless components. This could then be prevented, and a stateless component made.

We could make this optional on the property level – whether or not it triggers an event, and is preventable.

**Comment by treshugart** [comment]
```js
skate('my-element', {
  properties: {
    event: true // or 'event-name'?
  }
});
```

^ ??

Event should probably be:

```js
{ bubbles: false, cancelable: true }
```

**Comment by treshugart** [comment]
On second thought, it should probably be cancelable, we'll just need to be aware of the above issue when automating the React integration.

**Comment by treshugart** [comment]
### Outstanding items

The outstanding things for this as I see it are:

#### Default value

What's the default value? I'd vote for `false`, or some form of falsy. It'd be a big assumption to have on by default as it would create a significant amount of overhead for those who wouldn't be using it.

#### Allow boolean `true` or just `String`

Should we allow `true` to be specified? If so, what's the default event name we want to use? I'd vote for not supporting `true` and have it always coerce to a `String` if not falsy. You've got to opt-in anyways so the consumer may as well choose an event name. That way when reading the definition, it's clear to the reader what's going on, rather than making then have knowledge of what Skate's default is.

#### Property option name

What should the property option name be? I vote for either `event` or `notify`.

### IRL decisions:

1. The event should not bubble - performance and accuracy (a bubbled event could fire on an element who's property didn't actually change.
2. The event should be cancelable - allows for truly stateless components.
