### ISSUE TITLE
Registering elements for custom document

### ISSUE THREAD

**Issue by kelvinss** [skatejs/skatejs#535]
How can I register custom elements to a specific Document object, such as one inside an iframe?

**Comment by treshugart** [comment]
Currently the `skate()` function should register elements in whatever context it's included in (it just uses the `document` global). This means if you include skate in your iframe and have custom element definitions there, it should register within that frame. If you want to just have skate in your parent window and have that skate register to a select iframe, then that's not currently supported, but I'd be happy to consider proposals.

**Comment by kelvinss** [comment]
I'm considering including skate on the iframe, but I would probably have to re-include the libraries and some code inside it, and this iframe should be as clean as possible. I'm thinking in a way to keep the definitions independent from the rest of the code, but it would be very helpful register from the parent window.

**Comment by treshugart** [comment]
I wonder if something like:

```js
skate('my-element, {
  context: window
});
```

could work. It could default to whatever context `skate()` was called from regardless of where it was loaded. Anything referencing the global `document` could use the definition's context where necessary.

**Comment by kelvinss** [comment]
I'm trying to rewrite some code to become independent from the global `document`. I was thinking about replacing the `src/native/` folder by a `native.js` file, and use it like this:
```js
import Native from '../native';
var {createDocumentFragment, createElement} = Native(document);
```
What do you think?

**Comment by treshugart** [comment]
@kelvinss I like that idea. You could take that a step further and probably lookup `document` within the constructor of `Native` by default. Of course, this is probably for your use case of registering on the iframe.

**Comment by treshugart** [comment]
I wrote a test for this and in doing so, I realised that if you call any code from the parent, `window` in that context will be the parent. That being the case and the fact that custom elements v1 are scoped to windows via `window.customElements`, it won't be possible to register an iframe custom element from parent code. That leave the only current solution to load Skate within your iframe.

In the future, after v1 is in all browsers I see a possible solution to be that you can get the definition that Skate passes to `window.customElements.define()` from the parent and call that directly in the iframe.

**Comment by kelvinss** [comment]
I don't get it. My initial ideia was to replace every reference to `window` inside Skate by a reference to the iframe's `window`. Wouldn't that work?

**Comment by treshugart** [comment]
On master, I've refactored the code so that it lazily calls `document.registerElement()`. It would seem that when you call `skate()` that is contained on the parent window from inside the iframe that even references to `document` or `window` inside the functions still refer to the parent window. I could have been missing something, but I couldn't get the test to work. Stoked if you have something working, or would like to have a go.

**Comment by kelvinss** [comment]
I've managed to do that on some other library by wrapping the entire code with something like this:
```js
var init = function (win){
    if (typeof win == 'undefined'){ win = window }
    var doc = win.document;
    
    "[rest of the code]"
    
    skate.init = init;
    return skate;
};
export default init();
```
Then replacing every reference to `window` by `win` and `document` by `doc`, and then using it like this:
```js
import skate from 'skatejs';  // bound to parent window

ifr_skate = skate.init( iframe.contentWindow );  // bound to iframe window
```

I've already started to rewrite some code using these placeholders, but I'm with some problems to run the code for debugging. How exactly I'm I supposed to do that? How can I execute a single file?

**Comment by kelvinss** [comment]
The build system is unintelligible to me. What's exactly the reason for using ECMAScript 6?  :P

**Comment by treshugart** [comment]
It's the future! Seriously, though, we wanted to do less refactoring later on and using ES2015 afforded us the ability to use some features now, the most important being modules.

I like your idea, I'm just wondering how the connection between the registries for the different windows might look and how this would play into the V1 Custom Element polyfill (we are looking at using that instead of internally polyfilling) that the webcomponentjs peeps are working on right now. It's likely that polyfill will have to be included in whatever context it will be used in.

In terms of the current master code, there are uses of `window` and `document` in several spots. It might be worth spiking what it would look like to create instances of Skate where you could pass the context to it as an argument sort of like what you were doing. My thinking, though is that you'd do something like:

```js
const skate = new Skate(window);
skate.define('x-elem', { ... });
skate.emit(elem, 'some-event');
// etc...
```

And those would be the default exports and you'd maybe have another export that creates a new instance for those iframes:

```js
iFrameWindow.skate = skate.new(iFrameWindow);
```

Just not sure if adding this much to the code and API would be simpler than just loading Skate and the required definitions in the iframe. If it's coming from the same url on the same origin, it should cache. Or if it's coming from CDN, it should also cache.

Thoughts?

**Comment by treshugart** [comment]
Skate now uses the V1 custom element polyfill provided by webcomponentsjs. Though that doesn't solve your issue, it might open up a possibility to provide the registry to the skate call now:

```js
// It would default to this, but this is how you could pass a custom one.
skate.define(name, { registry: window.customElements });
```

Really, now that we use v1, we could probably just leave it up to the user:

```js
window.customElements.define('my-component', class extends skate.Component {});
```

**Comment by kelvinss** [comment]
If I got it right, I think that can solve it. I'll test ASAP.

Is this `skate.Component` already exposed? I can't find on the source [(index.js#L12)](https://github.com/skatejs/skatejs/blob/master/src/index.js#L12).

**Comment by treshugart** [comment]
To be clear, the above isn't possible at the moment, but could be possible in the future.

The `Component` module wasn't being exported. I wrote a test for this and exported it: https://github.com/skatejs/skatejs/blob/master/src/index.js#L14.

**Comment by treshugart** [comment]
Hey @kelvinss any luck?

**Comment by kelvinss** [comment]
I'm getting problems with building and running the tests. `npm install` failed asking for `rollup` and `webpack` packages. So I installed those packages, then it threw this warning:
`ERROR in Entry module not found: Error: Cannot resolve module 'babel-loader'`

Running `npm test` throws `sh: 1: karma: not found`.

Don't know if i'm doing something wrong. :P

**Comment by treshugart** [comment]
Weird. Can you try removing your node modules and reinstalling? I just tried on a fresh clone and `npm install` worked fine.

**Comment by kelvinss** [comment]
I found the problem is with Node 4.4.5. It worked fine on 6.2.2.

**Comment by treshugart** [comment]
Ahh, that'd do it :)

**Comment by kelvinss** [comment]
I got some code working: https://github.com/kelvinss/skatejs/commit/76f1c0980e8818181fc8046f19d339fe2da23068

I didn't test with polyfill, though.

**Comment by treshugart** [comment]
Just checked out your code and am leaving a few comments on it. Looks pretty good.

**Comment by treshugart** [comment]
Since the opening of this issue, we've simplified a lot of how defining a component works. You can now just #usetheplatform and do:

```js
window.customElements.define(class extends skate.Component {});
```

Which means you can choose exactly where you register it. The `define()` function still only works in the scope in which it's included, but I think for most use cases that's fine.

I'm going to close this issue, but if you feel that we can still address something here, please reopen and discuss.Cheers!
