### ISSUE TITLE
Explore component scoping

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#560]
https://github.com/w3c/webcomponents/issues/488

**Comment by trusktr** [comment]
@treshugart @justinfagnani What are your thoughts on something like this?

**Comment by treshugart** [comment]
You can do something similar using [`skate.factory()`](https://github.com/skatejs/skatejs#factory-componentdefinition). Right now, it'd be up to you to define the name within your dependant, though.

For example, if you had a component-a that is used by component-b:

```js
// a.js
import { factory, vdom } from 'skatejs';

export default factory({
  render (elem) {
    vdom.text(`This element is: ${elem.tagName}!`);
  }
});
```

```js
// b.js
import { factory, skate, vdom } from 'skatejs';
import b from './b';

// Define the namespaced tag name for the definition.
const componentB = b('component-a-b');

export default skate('component-a', {
  render () {
    // The virtual DOM function allows you to pass in the element constructor
    // and it will let Incremental DOM know that it should create a corresponding
    // virtual representation of the specified component.
    vdom(componentB);
  }
});
```

If you write `<component-a></component-a>`, it will output:

```html
<component-a>
  #shadow-root
    <component-a-b>
      #shadow-root
        This element is: COMPONENT-A-B!
    </component-a-b>
</component-a>
```

That said, the factory function has a slightly different purpose: to allow consumers of your component to define a name for your component without knowing anything about the implementation details; to them it's just a function call.

This could be implemented internally to Skate where if you pass a factory to the `vdom()` function that it could automatically work out the parent component's name and create a namespaced component for use specifically in the parent component's shadow root. The name doesn't really matter and it could be auto-generated so long as we were to make sure multiple instances of the parent component don't create new registrations for the scoped component.

I haven't really thought about this issue in much detail yet, but am open to ideas. The biggest thing for me would be to be able to export anonymous components (using `factory()`) so that my consumers could choose names, eliminating conflicts, while internally to those components, they can depend on each other without having a pre-defined name.

**Comment by justinfagnani** [comment]
Scoping is a very tricky problem due to the different ways elements can be created, an whether or not they can even be aware of the different scopes.

Earlier in the v1 spec discussion, when the registry was still tied to the document, not the window, there was an idea that different documents could have different registries. HTML imported document would then each have their own registry, and could merge in the registries of the document they import. This was a vague idea and the simple description wouldn't work as merging up the import tree would lead to the same elements as the global registry now, and so element definitions that would collide globally would still collide somewhere.

Things got trickier with constructor support - element constructors are global, and so the registry should be as well. Note that this assumes element classes are defined in non-modules. I'm not sure this logic applies the same if we assumed element would be defined in modules. Anyway, the registry is per-window now, for better or worse.

So, `new MyElement()`, `document.createElement('my-element')` and the parser seeing `<my-element></my-element>` all use the window's registry.

If we had a scoped registry somewhere, and we import a constructor into scope, then we could do `new MyElement()`, and if documents have registries in addition to windows, we could do `document.createElement('my-element'), and _maybe_ parse `<my-element></my-element>`. But the more common cases are probably one element definition importing another and then using that over any potential collision with a registration in window to write content to it's shadow root. This fits with my intuition on what scope we actually want: we want definitions scoped to an element, or it's shadow root.

So we really care about how an element creates element for it's own internal use. An element's template system can use something other than `cloneNode`, `importNode` or `document.createElement`. `this.createElement` or `this.shadowRoot.createElement` are good candidates, and the registry can be attached as `this.registry`, or `this.shadowRoot.registry`.

The registry class defined in the v1 polyfill should be able to be used independently of the rest of the polyfill (if not, file an issue).

Note that there are some potentially tricky issues with other parts of the system that are not scope aware, especially styling. A stylesheet in a shadow root can style both elements in the root and elements projected into the root by tag name. Two element definitions with the same tag name won't be differentiable in CSS. This might not really be a problem in practice though...

I'm really curious what you see in experiments here. If you land on something promising, it'd be great if other web component libraries were compatible with it :)

**Comment by treshugart** [comment]
Just updating this issue: skate.factory() was removed in https://github.com/skatejs/skatejs/issues/622 to minimize bloat. Scoping is still being worked on here, though.

**Comment by treshugart** [comment]
So one thing we've done here is to allow a component with the same name to be registered multiple times. If a conflict is found, a unique name is generated and used instead. Since you must always choose a name for your elements and you can't deregister them, this is really the only option to get around naming conflicts in things like Webpack's HMR. See #564 for more information.

Now, the reason I'm mentioning this here is because this essentially allows you to have component scoping, though, you must still provide a name to `define()`. That may change in the future if there is a consensus that it's a workable idea to do something like `skate.define({})` instead of `skate.define('x-name', {})`.

If you were able to register "anonymous" definitions, then you could essentially enforce the fact that you *must* import something in order to use it because you won't know its name:

```js
// component-a.js
export default skate.define({
  render() {
    return <div><slot /></div>;
  }
});

// component-b.js
import ComponentA from './component-a';
export default skate.define({
  render() {
    return <ComponentA>slotted content</ComponentA>;
  }
});
```

I've used JSX as it is a bit simpler to look at (and is supported). Since Skate supports passing tag names to its virtual elements, this works hand-in hand with anonymous definitions. This would only be recommended in situations where you didn't need to export a raw HTML API as your tag names are indeterminate. If you need to provide both, you should hard-code your component names, but at least you can still import them and use them in your vDOM.

I'm going to close this now and raise a separate issue for anonymous definitions.

**Comment by trusktr** [comment]
@justinfagnani 

> This fits with my intuition on what scope we actually want: we want definitions scoped to an element, or it's shadow root.

I highly want this.

@treshugart 

> This would only be recommended in situations where you didn't need to export a raw HTML API as your tag names are indeterminate.

It makes dev more encapsulated like with React, which I like. The thing is that opening inspector and seeing randomly generated tag names might be funky. On the other hand, @justinfagnani's idea of shadowroot-scoped registries would mean that you can see the same name across shadow roots in the inspector even though they can be completely different elements, but I think in general this would lead to a better devtools experience because most of the time names will probably not clash. There can also be an easy way for devtools to show which class is registered to the element when hovering (link to source line).

**Comment by trusktr** [comment]
I think my favorite solution, for now, is to just export classes from my library, and tell the user to do `customElements.define('name-that-user-chooses', MyClassThatIGiveThem)`.

In my specific case, I can recommend

```js
import {MotorHTMLNode, MotorHTMLScene} from 'motor/html'

customElements.define('motor-node', MotorHTMLNode)
customElements.define('motor-scene', MotorHTMLScene)

document.body.innerHTML = `
  <motor-scene ...>
     <motor-node ...>
       ...
     </motor-node>
  </motor-scene>
`
```

**Comment by Hotell** [comment]
@trusktr 
> think my favorite solution, for now, is to just export classes from my library, and tell the user to do customElements.define('name-that-user-chooses', MyClassThatIGiveThem).

yup exactly, even better export defined component to your particular name and raw class to let user register it under name that he wants.

This is how we do it with [blaze-elements](https://github.com/wc-catalogue/blaze-elements/blob/master/packages/button/index.ts)

so if user wants just registered component 
```ts
import {Button} from '@blaze-elements/button'
```

and if he want's raw class 
```ts
import Button from '@blaze-elements/button/Button`

customElements.define('my-btn', Button );
```

**Comment by treshugart** [comment]
The `{ define }` export will choose a name if you don't provide one using `static is = 'my-name'`, so there's that, too. While you can still export a constructor that hasn't yet been defined, this allows you to also do:

```js
import { define } from 'skatejs';
import ButtonCtor from 'some-button';

define(ButtonCtor);
```

If dev and readable names are an issue here, I'm happy to discuss making them more readable via a separate option on the constructor.

**Comment by treshugart** [comment]
Related, it'd be awesome of `document.createElement()` could take a constructor:

```js
document.createElement(CustomElement);
```
