### ISSUE TITLE
Revisit server-side rendering

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#573]
References:
- #282 
- #319 
- #320 
- #348 
- #364

A gist using electron: https://gist.github.com/treshugart/3dddaa6df8683afaf6bbba917e6ed95e.

UPDATE

Might be able to use something like https://gist.github.com/treshugart/e19c2be255448cd31d261f2e8db2127c which would support SSR because it's not native shadow DOM, but only fills necessary things at the custom element level (non-invasive, and can have it's own SSR technique).

**Comment by treshugart** [comment]
I think a good starting point for this could be simply rendering out all light DOM starting from a single root node.

Taking this a step further, expanding shadow roots on the server side is tricky and could prove to be more expensive than simply letting the browser do the necessary work.

**Comment by treshugart** [comment]
Gist for server rendering light DOM: https://gist.github.com/treshugart/3dddaa6df8683afaf6bbba917e6ed95e.

**Comment by pyros2097** [comment]
Any progress on server side rendering? Is there an example we can try out?

**Comment by pyros2097** [comment]
Gonna try to use this https://github.com/pimterry/server-components/ and this https://github.com/fgnass/domino to get something fledged out.

**Comment by treshugart** [comment]
Awesome! `server-components` have a slightly different API than native and look to only support v0 style APIs? cc @pimterry

Interested to see how `domino` works!

**Comment by pimterry** [comment]
Yep, currently working on moving to V1 and beefing out proper spec compatibility as we speak (and updating Domino to support some prerequisites en route). [Watch this space](https://github.com/pimterry/server-components/pull/30).

This is going to break backward compatibility completely, but feel free to build on the current API to get a PoC for what you're going for anyway, the basic concepts aren't going to be too wildly different.

**Comment by pimterry** [comment]
Main API difference (which will continue) is that your component rendering code needs to remember return a promise if it wants the document/fragment rendering process to wait before sending the resulting HTML to the client.

**Comment by treshugart** [comment]
@pimterry, do you have any plans to handle shadow content serialisation on the server and then re-hydrate on the client?

**Comment by pimterry** [comment]
Not right now, no. Shadow DOM is a bit out of scope for server components, since for purely server-side rendering, there's not much so value to it (CSS isolation particularly is meaningless here). I wouldn't be opposed to something for that, but I'd quite like to keep it fairly simple if possible. That would have to wait until our current changes are in place though. Although I think maybe actually that should be an independent extension for Domino anyway, rather than something that SC layers on top? Not sure.

**Comment by treshugart** [comment]
> CSS isolation particularly is meaningless here

I probably don't understand that point much. Maybe there's two different goals here: 1) running web components on the server and 2) static rendering on the server and rehydration on the client. It seems like `server-components` is the former, where it's not meant to help with perceived performance and isn't meant to interface with the client at all via initial HTML piping to the client whereas the latter is more of the concern that people want with this issue. Is that a correct analysis?

**Comment by pimterry** [comment]
Server components is designed to actively support the former, but intended be a useful core part of a larger solution for the latter. I definitely want SC to be able to support that further use case, where you render universally on both sides, but I also want to keep SC small - I'd rather layer frameworks for doing that effortlessly on top of a simple tool that lets you render components server side, rather than build on larger tool that does everything.

In that context alone, for the core immediate use case, shadow DOM isn't a key part. If you want to render client side on top with this you either:

1. Write both normal web components definitions for the client-side, with any WC tools you like, and totally independent server component definitions.

2. Build a universal component on top of the SC API, use real SC server-side, and just map the SC api to normal WC methods in the browser.

1 is easy and obvious I think, and works fine already. 2 is obviously preferable if you can though. For a simple PoC of that, see https://github.com/pimterry/leaflet-map-server-component. There, a [single component definition](https://github.com/pimterry/leaflet-map-server-component/blob/master/src/leaflet-map.js) works both server and client-side, by using real server components on the server-side, and [mapping](https://github.com/pimterry/leaflet-map-server-component/blob/master/server-components-for-web.js) the same API to the near-identical built-in API for the client-side.

That example is pretty basic and low-level, and all using the old API, but this is just a proof of concept, and I'm expecting to extract out a standard server-components-for-web stub (...perhaps with a better name) to do this more sensibly in time. This is fairly early stages though. Once you've got this, you could also add in support so you can universally use the shadow dom, but that's really an extension. That's also something that should plausibly live in Domino instead (since really Domino is the part providing the core DOM APIs, while SC should mainly be wrapping those to provide a nice API for easy rendering use).

Does that make more sense? I strongly want to keep server components as a simple tool that you can use just to transform HTML, but by doing that in the long term I'd like it to eventually also be an effective piece you can use in a framework for universal web component rendering generally.

**Comment by treshugart** [comment]
Makes perfect sense, @pimterry, I just wanted to make sure I had the priorities correct there. Definitely +1 for keeping it focused with the ability to layer functionality on top of it. Thanks for the clarifications :)

**Comment by treshugart** [comment]
GoogleBot said this about the markup at https://skatejs.github.io/

<img width="992" alt="screen shot 2017-02-13 at 10 57 56 am" src="https://cloud.githubusercontent.com/assets/136556/22867387/50ebfc66-f1db-11e6-8808-dd59224c4d73.png">

And this is what it sees:

<img width="849" alt="screen shot 2017-02-13 at 10 59 40 am" src="https://cloud.githubusercontent.com/assets/136556/22867402/8d0459fa-f1db-11e6-8229-878ae6597aaa.png">

However, it rendered the whole page:

<img width="554" alt="screen shot 2017-02-13 at 10 59 31 am" src="https://cloud.githubusercontent.com/assets/136556/22867403/93a2986c-f1db-11e6-828b-e1e0a0b24ef0.png">

**Comment by treshugart** [comment]
Update main content to reference https://gist.github.com/treshugart/e19c2be255448cd31d261f2e8db2127c, which is a pseudo shadow DOM partial fill at the custom element level (non invasive).

**Comment by treshugart** [comment]
This is now possible and 100% works with Skate and Preact. See https://github.com/skatejs/ssr. That also works for vanilla components, and possibly other libraries, but the DOM API coverage is minimal so YMMV. That lib is used to both SSR Skate and to test Skate with Jest. This should suffice for the purposes of this.
