### ISSUE TITLE
Evaluate if we can validate properties passed

### ISSUE THREAD

**Issue by joscha** [skatejs/skatejs#596]
Currently if you pass unknown properties to a skate definition, e.g.

```
define('some-name',{
properties: { ... // <-- should be props
}
```

skate does not yell at you.
We could leverage something like [Joi](https://github.com/hapijs/joi) to let the user know something passed in was incorrect. Potentially this could be done with code being pulled in/run on `NODE_ENV=development` only and would be stripped by the build system on a production build.

**Comment by treshugart** [comment]
I just referenced this in #754 since we might be able to use something like flowtype to do this for us, at the very least in components that consume the flowtype module.

**Comment by bradleyayers** [comment]
Echoing @treshugart, these problems have good solutions in the static typing space. I'd be interested in contributing a TypeScript definition for this. Someone else can probably chime in with a flowtype version.

That said, I don't think it needs to be an either/or scenario though, I wouldn't object to a debug build that emitted this kind of stuff.

**Comment by treshugart** [comment]
I think if we ever decided to adopt something like Flow or TypeScript that this would be inherently solved. That aside, now that we are using the platform (tm), we can't really yell at the consumer if the specify an unknown property as we advocate classes and passing directly to `customElements.define()`. Even so, you can't do this because a base class may be using a custom property to mixin behaviour.
