### ISSUE TITLE
Question on getting started

### ISSUE THREAD

**Issue by tmpfs** [skatejs/skatejs#636]
Hi,

I am currently evaluating the various frameworks for web components and have dismissed several as too bloated. This library looks very promising however I think the documentation lacks information on getting started (unless of course I am missing something).

I want to drop in a .js file and start writing components. I installed the library `npm i skatejs` and copied `dist/index.js` to the correct directory and load it in my HTML page. However I get an error referencing the nodejs `process` object:

```
skate.js:966 Uncaught ReferenceError: process is not defined
```

My app is running in electron with `nodeIntegration` disabled. I am curious why a distribution file would have lots of tests against `process.env.NODE_ENV`.

Can you please tell me the correct way to get a built distribution version of skatejs so I can evaluate it?

Also I have questions around styling the components in the shadow DOM (I see very little in the docs about styling) but I'll leave those until I can get up and running with a simple component.

**Comment by treshugart** [comment]
`process` comes from [`incremental-dom`](https://github.com/google/incremental-dom) which is bundled. We should add a definition for process if it's not found. I'll change this into a bug for that.

**Comment by treshugart** [comment]
Fixed in `1.0.0-beta.4` :)

**Comment by treshugart** [comment]
It turns out Incremental DOM doesn't ensure `process` is defined.

**Comment by tmpfs** [comment]
Thanks for getting back to me so fast, not quite there yet though. I updated to `1.0.0-beta.4` and the error has moved to `core.js` in `incremental-dom`.

For the moment I have to declare the `process` object like your patch *before loading* `skatejs` and then I can bypass the runtime error. I'll do that for the moment so I can test the library but some thought needs to be given to the rationale behind including those conditionals in a distribution file. From my point of view those clauses should be removed for a production distribution build rather than mocking the `process` object.

Thanks for your help.

**Comment by treshugart** [comment]
Ok, cool. There was an issue in their 0.4.0 release. In 0.4.1 their build is fixed and it doesn't included the process vars. I'll update the build to suit and then release and update this issue when it's fixed.

**Comment by tmpfs** [comment]
Great thanks. I am impressed it took me only a matter of minutes to port my existing (simple) vanilla components (no framework) to skatejs.

I have some more questions that I think you could help with as you are clearly very knowledgeable about web components. I hope you don't mind me continuing this issue, let me know if you would prefer separate issues.

### HTMLImports

I initially evaluated Polymer but learned that Firefox was not going to implement HTMLImports so am very happy that skatejs does not depend upon HTMLImports and I noticed in one of your slideshows that you mentioned HTMLImports, my opinion is that whilst I like the idea of HTMLImports without a Firefox implementation there is not much point moving forward with them. I assume that skatejs will not support or use HTMLImports in the future?

### Content Security Policy

My application needs to run with a *very strict* content security policy, however Polymer uses inline CSS and inline scripts, neither of which I can enable in my application which rules out using Polymer. Oddly, it appears that the `<link>` element is not allowed in the shadow DOM, I don't understand why, do you know why this would be the case and whether it might be possible to use the `<link>` element in the shadow DOM in the future to allow external stylesheets for components?

### Firefox & Shadow DOM

The simple components I have just written work fine in Chrome but don't seem to work in Firefox with the `dom.webcomponents.enabled` flag set to `true`, I am using Firefox Developer Edition 49.0a2 - according to your browser support matrix this should work, any idea what I am doing wrong here?

### Deprecated CSS selectors

Styling the shadow DOM involves using the `/deep/` and `::shadow` selectors both of which are deprecated, it seems to me that no browser currently supports the `>>>` deep child combinator. Should I continue to use the deprecated selectors or is there a better way you know of?

### HTML Template Element

I have read your section on using [templating languages](https://github.com/skatejs/skatejs#using-jsx-and-other-templating-languages) but I am quite keen to avoid any compiling/transpiling step, currently I am using vanilla javascript as I find it allows me to iterate very fast. Are there any plans to have native support in skatejs for the `<template>` element with some simple data-binding. I think maybe I am in the minority here but it feels weird building my DOM using javascript. I would quite like to see a component that looks something like this:

```javascript
skate.define('x-component', {
  render: (elem) => {
    skate.template('template.x-component', elem);
  }
});
```

And then a `component.html` that looks something like this:

```html
<template class="x-component">
  <span>{{elem.attributeName}}</span>
</template>
<link rel="stylesheet" href="x-component.css">
<script src="x-component.js"></script>
```

It would then be quite trivial to write a pre-build step that finds all components the user needs and build a single HTML, CSS and Javascript file containing just the components the user specifies.

This is probably a bit contentious but I thought I would throw it out there anyhow.

Thanks for your help and thoughts.

**Comment by treshugart** [comment]
@tmpfs I just released 1.0.0-beta.5. Update docs on installing: https://github.com/skatejs/skatejs#installing. Basically, none of the builds reference `process` anymore. If you want all the deps bundled, use `dist/index-with-deps.js` or the min file, otherwise use `dist/index.js` which is what NPM would find if you just did `require('skatejs')`.

**Comment by treshugart** [comment]
> I initially evaluated Polymer but learned that Firefox was not going to implement HTMLImports so am very happy that skatejs does not depend upon HTMLImports and I noticed in one of your slideshows that you mentioned HTMLImports, my opinion is that whilst I like the idea of HTMLImports without a Firefox implementation there is not much point moving forward with them. I assume that skatejs will not support or use HTMLImports in the future?

Even if the spec aligns to HTML Imports, I don't think Skate would ever need to use them for what it does, at least internally, because it's only a way to include stuff which Skate has no opinion on. Regardless, there's already better and more efficient ways to achieve the same thing which is why I think there is contention.

> My application needs to run with a very strict content security policy, however Polymer uses inline CSS and inline scripts, neither of which I can enable in my application which rules out using Polymer. Oddly, it appears that the <link> element is not allowed in the shadow DOM, I don't understand why, do you know why this would be the case and whether it might be possible to use the <link> element in the shadow DOM in the future to allow external stylesheets for components?

> The simple components I have just written work fine in Chrome but don't seem to work in Firefox with the dom.webcomponents.enabled flag set to true, I am using Firefox Developer Edition 49.0a2 - according to your browser support matrix this should work, any idea what I am doing wrong here?

Not sure. I haven't tried it. I assume that they got part of the way through the implementation and then stopped because of the spec churn that was going on from v0 to v1. Consumers of your components are unlikely to turn that flag on and it works in both Chrome and Opera. Happy to accept a PR here, but I'm not sure if we'll spend much time on it at this point considering Firefox will ship v1 and probably never ship v0 other than what's currently under the flag.

This *might* be answered here: https://github.com/w3c/webcomponents/issues/82. I don't really know off the top of my head, though.

> Styling the shadow DOM involves using the /deep/ and ::shadow selectors both of which are deprecated, it seems to me that no browser currently supports the >>> deep child combinator. Should I continue to use the deprecated selectors or is there a better way you know of?

[CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables). Currently supported everywhere, except for - you guessed it - Internet Explorer. Polymer uses some variation of this, but we don't have any plans to address this directly in Skate other than possibly documenting how to do it.

> Are there any plans to have native support in skatejs for the <template> element with some simple data-binding. I think maybe I am in the minority here but it feels weird building my DOM using javascript.

There's no issues for this, but I'm not opposed to its exploration. I'm unsure at this point how it would work out since Skate uses Incremental DOM and it would conflict with the default way of rendering a component. Skate used to allow the consumer to do their own templating, but we found with time that this really held Skate back. Skate would need to account for the several ways people might template: everything in `render()` or mutating stuff in property setters. These have implications on where you execute stuff in the lifecycle. On top of this, we found that not having an opinion was a deterrent for many people where they just wanted to get something done. Simplifying this into using Incremental DOM and a single `render()` function really helped us, as I hope many others.

If you have any ideas here, we're open to discussing them, so feel free to talk with us or raise issues.

**Comment by treshugart** [comment]
Closing now as the problem should be fixed and questions hopefully answered. Feel free to reopen or submit other issues. Thanks :)

**Comment by tmpfs** [comment]
Great  - works without the little `process` patch now :) Thanks for clarifying the docs too!

One little detail is that the window global has been renamed from `skate` to `skatejs` (I am not using browserify, webpack etc).

It could be now that it has changed for the other ways of consuming https://github.com/skatejs/skatejs#consuming I am not sure. I preferred the cleaner `skate` variable name but not a big deal, I've renamed my references for the moment.

**Comment by treshugart** [comment]
Yeah, I need to fix that. It's `skate` in the rollup'd build: `dist/index.js`, but in the webpacked stuff it's still `skatejs` (needs to be fixed). To get the build as small as possible, I used Rollup. It didn't like importing the dependencies for some reason which is why I used Webpack for the others. Also, those files that include the deps are probably less likely to be used in a production environment, so I'm not as worried about Webpack not being as good at size.

**Comment by treshugart** [comment]
Fixed `skatejs` -> `skate` in `1.0.0-beta.6` :)

**Comment by tmpfs** [comment]
Perfect - thanks for being so repsonsive!

I have an idea of how to structure components using a `<template>` element without sacrificing performance. I'll do a PoC and then ping you for feedback.

**Comment by treshugart** [comment]
Sounds good, @tmpfs. Thanks for being patient with that bug. We look forward to your PoC!
