### ISSUE TITLE
Remove "events" functionality

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#675]
Since we can attach listeners to elements directly, should we remove the ability to specify "events"? This would clean up the API and remove any confusion around the two.

For example (using JSX to simplify the examples):

```js
skate('x-test', {
  events: {
    'click .my-button'() {}
  },
  render() {
    return <button class="my-button" />
  }
});
```

vs just:

```js
skate('x-test', {
  render() {
    return <button onclick={() => {}} />
  }
});
```

If there aren't any major objections to this, a simple workaround is to just `elem.addEventListener()` in one of the callbacks if you need to attach events to the host. Generally events would be attached to the host from higher up in the tree.

**Comment by bradleyayers** [comment]
While removing it from the implementation is an interesting discussion, perhaps something easier to agree on is demoting it from the documentation and promoting the `onfoo={(event) => {…}}` style (here on referred to as the onFoo style). Encouraging the onFoo style is consistent with the vision of "React for web components".

Having two ways to do the same thing — where the difference appears only syntactic — increases the learning curve because it burdens me with needing to weigh up the strengths and weaknesses of each approach, without understanding the subtle differences between them.

I would prefer a single bullet-proof approach that alleviates me from needing to make a judgment call.

**Comment by treshugart** [comment]
I'd prefer nutting this out and removing it altogether if possible.

**Comment by lukebatchelor** [comment]
FWIW, I don't like the inline way of adding events

```
skate('x-test', {
  render() {
    return <button onclick={() => {}} />
  }
});
```

unless the handler is a function described somewhere else.

Other than that I don't mind either way. Which way is closer to Reacts? Would there be benefits in making them closer?

**Comment by zephor** [comment]
I've so far enjoyed the declarative nature of the 'events' object. That said I'm not really that attached to it and the line of thought around simplifying API is a good one. What I'm curious about is what sparked this? The ability to bind directly to elements has always been there so we could have done this a long time ago. 

Also I notice the example is JSX oriented. I guess non-JSX users would just have to start using `addEventListener`, or in our case we would use jquery's `$.on`. Bottom line is I don't see any problem with removing it if we feel like it simplifies the API.

**Comment by treshugart** [comment]
> Also I notice the example is JSX oriented. I guess non-JSX users would just have to start using addEventListener, or in our case we would use jquery's $.on.

Nah, you'd use `vdom.element()` instead:

```js
skate.vdom.element('button', { onclick: () => {} });
```

> EDIT: this probably goes without saying but as long as we deprecate first I'm ok with removing it in favour of .addEventListener (for non-JSX/react users)

This would go into 1.0 as a breaking change from non-1.0 versions. We're not even to -rc's yet (might just promote to 1.0 when we're ready).
