### ISSUE TITLE
Make props.event optionally bubble

### ISSUE THREAD

**Issue by jpnelson** [skatejs/skatejs#683]
It's nice if you want to make it a part of your API.

**Comment by treshugart** [comment]
I'm wondering if it'd be simpler API if we just trigger a callback before rendering. Props will trigger an re-render and currently we've just implemented a `shouldRender()`, removing the property `render()` callback but we can probably get away with a simpler `beforeRender()` callback that receives the same arguments and has the same semantics. Here, you can do whatever you need before rendering and return `true` to render. It might even better to provide the function a callback to be called that will trigger rendering, therefore if it's never called, it never renders. Do we have a use case for any async behaviour before rendering?

**Comment by treshugart** [comment]
I tried the above in #696 and everything felt great, and works in practice except for the render callback. I instead opted to use a return value because it's less ambiguous to what should happen. For example, what if you just don't ever call the callback. How does that play with renders that might queue before it's called. The callback prevents itself from being being implicitly invoked if you set props within it (to prevent recursion). You can release the lock after the function completes, but what happens if you do weird stuff with setTimeout etc? It's simpler to just say it's synchronous and to use return values.

So the API shape as described above now would look like:

```js
beforeRender(elem, prevProps, nextProps) {
  if (shouldRender(prevProps, nextProps) {
    if (emit(elem, 'update', { detail: { prevProps, nextProps } })) {
      return true;
    }
  }
}
```
