### ISSUE TITLE
Allow usage of symbols in props

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#687]
Currently you cannot - but should be able to - do:

```js
const sym = Symbol();
skate.define('x-test', {
  props: {
    [sym]: {}
  }
});
```

**Comment by mcorbanini** [comment]
@treshugart Just to be sure, the example here describes that you should be able to specify a property with a symbol key, in order to use it only programmatically right? because something like this should not be supported:
```javascript
   props: {
      [sym]: {
         attribute: true
      }
```
Am I right?

**Comment by treshugart** [comment]
Right, reflected symbolised props wouldn't make sense. I'm not sure there's a way we can enforce this when using non-native Symbols, but we could with native. What do you think we should do here?

**Comment by mcorbanini** [comment]
Since using a symbol for a property key is something that can be done only programmatically, I don't think we should enforce anything. 

At least for this specific PR we may just want to update the docs saying that symbols are supported only as internal private properties in our components, so that `attribute` should be always `false`. Worst case scenario, the user didn't read the docs so he/she try to create a symbol prop with attribute: true and it will break.

I guess the error message will be something like `Symbol cannot be converted to string`. To avoid that we can validate if those 2 options are given and throw a more descriptive error.

This is what I have on the top of my head right now.
