### ISSUE TITLE
Run Rollup build as part of travis build

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#793]
This is so that we can test to ensure Rollup doesn't break anything (which it has many times in the past).

**Comment by bengummer** [comment]
Because skatejs `package.json` has `"prepublish": "sk-bundle"`, rollup gets run on every `npm install` of skatejs (see [here](https://docs.npmjs.com/misc/scripts)), so we're already covered in skatejs

It might be good to have a rollup test as part of skatejs/build since that is where rollup is pulled in

**Comment by treshugart** [comment]
Yeah, cool. Closing this for now then.
