### ISSUE TITLE
Ability to extend elements other than HTMLElement

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#804]
Right now, `Component` extends directly from `HTMLElement`. We should keep this as the default, but also allow the consumer to specify a class that `Component` should extend.

**Comment by zzarcon** [comment]
This is very interesting point, I was wondering if the current version supports this already and just found this issue 👍 

I was just thinking on the api, and i think the user will need to define at least 2 properties:
  * `class`: Basically the element class we want to extend (HTMLTextAreaElement, HTMLButtonElement, etc)
  * `elementName`: The string which indicates the actual tag name of the element you want to extend. I think this is still needed since different tag names uses the same Element prototype

For sure the names may change, but I think you get what I mean with them. So based on that, what about:

**Option 1**
```javascript
skate.define('growy-area', {
  props: {
    maxHeight: skate.prop.number({attribute: true})
  },
  extends: {
    class: HTMLTextAreaElement,
    elementName: 'textarea'
  }
});
```

**Option 2**
```javascript
skate.define('growy-area', {
  props: {
    count: skate.prop.number({attribute: true})
  }
}).extends({
  class: HTMLTextAreaElement,
  elementName: 'textarea'
})
```

I think Option 1 its more aligned with the current api, but is worth to think about other approaches. Let me know if some of this makes sense to you and I'll love to work on it once we agree on something.

Thanks!!

**Comment by treshugart** [comment]
You probably don't even need to go that deep. The `extends` option exists currently to support customised-built in elements (`is` attribute, which is still contentious).

I think the main issue here is that the base `skate.Component` class (which is what is extended by default if you pass an object literal) extends `HTMLElement` directly. So all we really need to do is be able to tell `Component` what to extend. The only way to do this without breaking api would be to create a way to generate a component base class from another built-in:

```js
define('my-element', class extends component(HTMLInputElement) {});
```

You could make safe defaults here to get the same default behaviour and deprecate `Component` (uppercase) so you have one way to do it:

```js
define('my-element', class extends component() {});
```

**Comment by bradleyayers** [comment]
@treshugart your proposal looks reasonable.

**Comment by zzarcon** [comment]
I think this feature it's blocked until we merge https://github.com/skatejs/skatejs/pull/824 since right now the element constructor doesn't work well with V1. Thoughts?

**Comment by treshugart** [comment]
Yeah, that definitely needs to go in before anything pretty much. I think Ben is about done with it.

**Comment by treshugart** [comment]
Fixed in https://github.com/skatejs/skatejs/pull/1041.
