### ISSUE TITLE
Tests fails on Chrome 55 (Canary)

### ISSUE THREAD

**Issue by zzarcon** [skatejs/skatejs#813]
Hi! I wanted to run the testsuite in a WebComponents V1 environment, so I decided to run them in Chrome 55, currently in canary and turns out that they fail. Apparently the issue appears when running the [Component constructor](https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L76-L80), which is only used when V1 is available.

```javascript
const elem = HTMLElement.call(this, self);
```
```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator,
this DOM object constructor cannot be called as a function
```

Apparently is not allowed to create an element in such way. So my question is, how are we actually testing that the library works with V1? maybe Im just using a buggy version of Chrome and this is fine :)

If that's not the case, maybe we can use something like `document.createElement` or create a dummy function which has the `HTMLElement` prototype? 

Let me know if this makes sense to you, thanks!!

**Comment by treshugart** [comment]
I think in v1, with transpiled es5, we have to use `new.target` instead. See https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js. I'm unsure the best way to approach this at the moment. Ideas?

**Comment by treshugart** [comment]
Unfortunately `new.target` is a syntax error. I wonder if we can `eval` it?

**Comment by treshugart** [comment]
This seems to work:

```js
const elem = 'Reflect' in window ? Reflect.construct(HTMLElement, args, this.constructor) : HTMLElement.apply(this, args);
```

However, there's a caveat. The tests still fail in Chrome 55 because the [requirements](https://www.w3.org/TR/custom-elements/#custom-element-conformance) for custom elements highlight that you must not set attributes. There's two spots that we do it:

- When initialising props (that have linked attributes)
- Setting the `defined` attribute.

We're going to have to make a breaking change and defer those to `connectedCallback()`, or defer it in a `setTimeout`. The former makes more sense given the spec constraints. So, to outline the changes:

- Move all prop initialisation to `connectedCallback()`
- Change `skate.ready()` to look for a defined property (or just move this to look for when it's been connected). We could also rename this to `attached` at the same time to reflect this and be consistent with our lifecycle nomenclature. This also only ever existed so one could tell when an element has been upgraded in polyfill land or attached in native, so this sort of makes sense anyways.

**Comment by treshugart** [comment]
In fact, it might even be a better idea to remove `skate.ready()` altogether if we're thinking about changing the semantics of it. I'll raise this with the team. We should at least be able to defer the attribute stuff until then.

**Comment by zzarcon** [comment]
Also, how should we handle the `Reflect` support? I think we can assume it will be present in every browser with V1 support, what do you think?

**Comment by treshugart** [comment]
Yep. `Reflect` / `new.target` will be available in all V1 browsers.

**Comment by bengummer** [comment]
I think this is also causing https://github.com/webcomponents/react-integration to fail for skated components in Chrome 55, as `react-integration` calls `new CustomElement()` ([source here](https://github.com/webcomponents/react-integration/blob/64ad669/src/index.js#L34))

Example: http://codepen.io/bgummeratlassian/pen/JRJVxk

Happy to be corrected if this turns out to be unrelated :)

**Comment by treshugart** [comment]
I think you're right @bengummer. That would explain the different error message.

**Comment by bengummer** [comment]
this PR is continued in https://github.com/skatejs/skatejs/pull/824 (just so we could get the Saucelabs tests to run) so this PR can probably be closed
