### ISSUE TITLE
Consider allowing null / undefined remove an attribute

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#832]
Currently `false`, when passed, will remove the corresponding attribute but `undefined` and `null` get stringified.

Does it make sense to allow all falsy values remove the attribute? This means `0` (`Number` not `String`) will remove the attribute. Or is `undefined` / `null` / `false` good enough. Or do we even need to do this at all.

_Note it's a breaking change because those relying on `null` or `undefined` to be stringified would be broken._

**Comment by marcoms** [comment]
Wasn't the `undefined`, `null,` and `false` bunch set to remove the linked attribute in the past? Perhaps it changed after the switch to functional style?

Either way I think the above trio is okay since they don't make much sense to stringify. `0` could feasibly be a useful value for number properties (e.g. `<x-progressbar value="0" max="100">`) and it might not be obvious to the user that an absent attribute implies `0`, so in my opinion `0` should remain.

**Comment by treshugart** [comment]
@marcoms they still remove the attribute when used as a property setter, this is just for Incremental DOM.

**Comment by rhythnic** [comment]
I think it would be good to remove null/undefined attributes, not just for boolean atts, but in general.  I have a use case where I'm styling the host based on an attribute with an unknown value, which in css looks like this.
```
:host {

}
:host[my-att] {

}
```

This is failing for me at the moment, because the attribute is present on the element.  As a workaround, I've removed the attribute from props and I am using getAttribute in the render method.
```
const myAtt = this.getAttribute('my-att');
```

**Comment by treshugart** [comment]
@rhythnic can you provide the prop definition that is giving you grief?

See https://github.com/skatejs/skatejs/blob/master/src/util/attributes-manager.js#L78. That looks like it ensures a prop that is set to an empty value will remove the attribute (cc @andreawyss). This should work for all attribute-linked props.

**Comment by rhythnic** [comment]
@treshugart  Thanks for pointing me to the code.  I was able to fix it by logging a bit from inside of _syncAttrValue.
### Original Prop definition
```
href: skate.prop({ attribute: true })
```

### Fixed
```
href: skate.prop({ attribute: true, default: null })
```

What caused the attribute to show for undefined values is that inside of _syncAttrValue the value is an empty string, so it fails the check for === null.

**Comment by treshugart** [comment]
Now, as a blanket rule, `null` and `undefined` will remove an attribute. Additionally, props that `deserialize` to either will inherently remove an attribute. Done in #1098.
