### ISSUE TITLE
skate.js.org doesn't work

### ISSUE THREAD

**Issue by dillonkrug** [skatejs/skatejs#836]
in Chrome, Version 54.0.2840.41 beta (64-bit)

Just the following error in the console:

```
Uncaught TypeError: Cannot assign to read only property 'customElements' of object '#<Window>'
    at http://skate.js.org/dist/index-with-deps.min.js:10:13938
```

**Comment by zzarcon** [comment]
Thanks for reporting this, it looks like there's something wrong with some polyfill used by the library, probably this? https://github.com/skatejs/skatejs.github.io/blob/master/package.json#L42

**Comment by treshugart** [comment]
This should be fixed once it's updated to use the latest `skatejs-web-components` version. Safari 10 should also be fixed shortly (https://bugs.webkit.org/show_bug.cgi?id=160331).

**Comment by stsvilik** [comment]
+1 site shows up blank on iPhone

**Comment by treshugart** [comment]
I've been trying to find time to work on this. I've got it mostly fixed.
The problem with Safari is Safari's fault. The have a pretty nasty bug I
reported before release and they didn't fix it before it was released to
the public: https://bugs.webkit.org/show_bug.cgi?id=160331. We've tried
hacking a fix in the latest skatejs-web-components but it only seems to fix
itnin certain scenarios and seems to still be broken on the website. It's
fixed in the latest tech preview, so hopefully it goes out in their next
updates.

I'll try and get the site working today.

**Comment by stsvilik** [comment]
Wow, that bug is nasty. Did any of the old IE-style recalc hacks work i.e. zoom:1, or toggling display from none to initial?

**Comment by treshugart** [comment]
I've fixed the Safari issue in skatejs-web-components. The other issues were because of a syncing issue that I've worked around in the router.

I've disabled the todo list example for the time being because it requires #863 be solved. The workarounds don't work due to spec limitations.
