### ISSUE TITLE
Proposal to change the way attributes / properties are reflected

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#838]
After a recent discussion (https://twitter.com/rob_dodson/status/784152571220930561) I'm thinking the best algorithm for attribute / property reflection would be to use props as the source of truth but to have attribute sets affect properties if linked. So basically:

- Attribute set sets props both for init and over time. Attribute value is deserialised as normal.
- Property sets are never reflected back to attributes as this mutates the DOM. Things could become out of sync here but it's kinda like the state vs props thing in React.

### Pros

- Perf: props are faster than attrs (3x, I think), and syncing props to attrs incur the attr set + whatever the serialisation cost is.
- Source of truth is props.
- No DOM state is mutated.

### Cons

- Selectors (DOM or CSS) for attributes that have a linked prop, and the prop is set (but never linked back). This could always be mutated back in the property setter.
- Possible gotchas where most would think if it's linked one way, that it'd be linked both ways. As with the first con, this could be addressed.

### Possible solutions

- Two syncing styles: one-way and two-way.

**Comment by jpnelson** [comment]
What is the advantage in not serialising back to the DOM? If you need to be able to deserialise it, there must be a way to serialise that data again anyway. I guess the advantage would be DOM mutation, which wasn't really discussed in that thread, but is the DOM mutation of the attributes really an issue?

**Comment by treshugart** [comment]
Maybe a possible solution would be to have aggressive vs passive syncing?

**Comment by robdodson** [comment]
Maybe worth noting that some things don't have corresponding properties. Specifically `aria-*` :\

**Comment by treshugart** [comment]
@robdodson this is true. I think in this case one would expect to set an attribute. In the case of Skate, you could do:

```js
props: {
  ariaActiveDescendant: { attribute: true }
}
```

And that would link the attribute to the specified property. In the case of this proposal, setting the property wouldn't set the attribute. However, if you set the attribute, it would set as normal, but also sync to the property and trigger a `render()`. This can be done for `data-*` attributes as well.

I think no matter what choice anyone makes it will not be aligned with native elements, but I don't think there's anything we can do about that. I think the more important question here is what is a good pattern for Web Components, or at the very least, Skate. I think that it's very helpful though to get your insight, and others from the Polymer team about this. This feels like something that is borderline spec-able and even if it doesn't go into the spec, we might be able to align on standardised behaviour between our libraries.

**Comment by marcoms** [comment]
I think having an optional parameter for options (one-way syncing from attributes as default) specifying what behaviour is preferred for each property would be appropriate. In my experience it's very common to have CSS styles dependent on attribute values, especially for custom elements where defining your own attributes is encouraged.

**Comment by robdodson** [comment]
Look at the original proposal:

> Attribute set sets props both for init and over time. Attribute value is deserialised as normal.
> Property sets are never reflected back to attributes as this mutates the DOM. Things could become out of sync here but it's kinda like the state vs props thing in React.

I think I'm in agreement that this is a good pattern for Custom Elements. You've always got the escape hatch of setting the attribute yourself in a property setter if you really need it for styling. Though CSS perf is often not the primary bottleneck on most apps, styling off of attributes is inherently slower than classes anyway (this is why the Polymer team moved off of them, based on the advice of the Chrome team). Since all frameworks pretty much treat props as the source of truth at this point, it seems reasonable for Custom Elements to do the same.

**Comment by treshugart** [comment]
> You've always got the escape hatch of setting the attribute yourself in a property setter if you really need it for styling.

I can't seem to find an issue relating to it, but I remember custom pseudo-classes being discussed over at the w3c/webcomponents repo. I wonder if this is a similar issue, where you could create custom pseudo-classes and link those to internal component state rather than affecting DOM state. This would be in alignment with `:checked` and how that is always the source of truth for styling because the attribute and property are not synced.

**Comment by robdodson** [comment]
@bkardell do you know where the rules live for author defined pseudo properties? I saw you mentioned them recently in https://twitter.com/briankardell/status/783451134476230656

**Comment by bkardell** [comment]
@robdodson in what context do you mean rules?  In that I was talking about parser rules, and to the best of my understanding CSSWG decided on a very simple 'rule' which is basically: CSS has always had 'custom' stuff in its forward compat parsing in the form of vendor prefixes... so,

css properties:
```css
   foo: ... /* normal */
   -webkit-foo: .... /* vendor prefixed */
   --foo: .... /* 'custom' is author prefixed, just drop the vendor */
```

same works for pseudos (elements or classes)
```css
   .foo:focus { ... /* normal */ }
   .foo:-moz-focusring { ... /* vendor prefixed */ }
   .foo:--focusring { .../* 'custom' is author prefixed, just drop the vendor */  }
```

etc.  this includes functions, mqs, etc...

Now, I'd really like @tabatkins or someone to confirm that I am not off the mark since the minutes resolution is ... sparse... but that is my recollection and I remember both being quite happy about it and owning up to instigating it and explaining why it's actually "good" (it's very easy to learn, you already know it and you can apply it equally across the platform) when people hated on custom props. 

If you mean, where are the proposals - there are a few, at various stages.  Tab and I worked on http://tabatkins.github.io/specs/css-aliases/index.html for custom pseudo-classes, there are talks about how to do custom pseudo elements (and discussions about whether that is good in web platform) and maybe others.  I know that there was also a 'not actually custom element' but more like 'slot-like' 'functional pseudo-element' proposal for something like ::part(name) in the specs, but... I'm not sure which you're interested in?

**Comment by robdodson** [comment]
Was looking for proposals on defining custom pseudo classes. This looks to be in the right ballpark http://tabatkins.github.io/specs/css-aliases/index.html#custom-selectors

But I think we were wondering if there is a way for a custom element to signal to the CSS parsee that it should match a custom pseudo class without having to actually modify the DOM itself.

**Comment by tabatkins** [comment]
Well, custom pseudos don't exist yet, so there's no correct answer yet. ^_^

File a bug on my draft spec so I can remember it when I do this properly in Houdini?

**Comment by treshugart** [comment]
To add to this, I think that one-way reflection would be best here. That way, `{ attribute: true }` could be the default and if the consumer wants a custom name for the attribute, they just specify it.

**Comment by robdodson** [comment]
@treshugart looking at this comment https://github.com/skatejs/skatejs/issues/838#issuecomment-252151689 you mentioned:

> And that would link the attribute to the specified property. In the case of this proposal, setting the property wouldn't set the attribute.

Is there a mechanism in Skate that will let me say "anytime this property is set, reflect it to the attribute"? For something like `aria-`, being able to set it as a property and have that reflect to an attribute would be extremely useful.

Basically I agree with the general model of props being one way and not reflecting to the DOM, but it would be nice to have an escape hatch for things like ARIA. That way I could actually program entirely with properties, and never have to imperatively call `setAttribute` in my own code. I could just change the prop and it would reflect. I think ARIA is moving towards a model where you'll be able to do this in JS but it'll still take a few years for that standard to bake.

**Comment by treshugart** [comment]
> I think ARIA is moving towards a model where you'll be able to do this in JS but it'll still take a few years for that standard to bake.

That's great to hear. Yes, I believe having an escape hatch is a good idea. Something that I've discussed internally with @bradleyayers would be to have semantics attached to props internally where a prefix - similar to Angular 2's - would denote what a props is supposed to do:

- set as attr (`@` maybe?)
- set as prop (default?)
- bind as event listener (`#` maybe?)

Unfortunately in supporting JSX, we're limited to a subset of what are available with identifiers. You can do stuff like:

```js
<div {...{ '@aria-describedby': this.id }} />
```

Which isn't too bad. With JSX 2 [this might be possible](https://github.com/facebook/jsx/issues/21). If props are the default, and most widely used, then maybe we can support something like this in the short term and long term.

Now, this only gives us these semantics for props specified inside of a Skate component, but that might be ok because if you're writing HTML, or via another library, then it's up to the author using that entry point to make the decision of what to set, I think.

**Comment by andreawyss** [comment]
@treshugart why when a skate component is NOT connected, setting a property value is not reflected to the attribute?
But setting an attribute value is reflected to the property.
Why we need to have separate sync behavior between connected and disconnected mode?

**Comment by andreawyss** [comment]
@treshugart I was trying to refactor this attribute to prop and prop to attribute logic because of issue #847 with Angular 1.
I'm proposing to split the current attribute option in two separate options: 
attrRead:boolean|string     (attribute when set is deserialized to prop)
attrWrite:boolean|string    (attribute to serialize the prop value when set including when initialized)
For backwards compatibility the attribute option would set both to the same value.

The problem in trying to change the code is that currently the sync logic behaves differently if the component is disconnected vs. it is connected. And then when connecting a synchronization cycle takes place.
What are the reasons that when NOT connected the behavior must be different then when connected?

**Comment by andreawyss** [comment]
@treshugart I would like to refactor this attribute->prop and prop->attribute code because of issue #847 with Angular 1.

I'm proposing to split the current 'attribute' option in two separate options: 
**attrIn**       optional, boolean or attribute name: to deserialize prop value from 
**attrOut**    optional, boolean or attribute name: to serialized prop value to
For compatibility the 'attribute' option would set both: attrInput = attrOutput = attribute

#### prop construction
If attribute defined by attrIn option is present it is deserialized and used to set the initial prop value. Since prop value was set from attrIn, its value will NOT be reflected to attrOut. 
If attribute defined by attrIn option is NOT present, prop value is set to 'initial' or 'default' option. Since prop value was NOT set from attrIn, its value will be serialized to attrOut unless the value was set to the ‘default’ option.

#### attribute set/remove 
Each time the value of attribute described by attrIn option changed/was removed, this is deserialized and set to the prop. Since prop value was set from attrIn, its value will NOT be reflected to attrOut.

#### prop set
Each time prop set() executes, excluding when called from an attrIn change, the value will be serialized to the attribute defined by attrOut option.
Note that if the prop value is set to ‘default‘ option, this has the effect of removing the attribute defined by ‘attrOut’ option.

The behavior will be the same for Component connected or disconnected.
The prop value is defined by the last ‘external’ call to prop set or attribute set/remove.

When declaring only the ‘attrIn’ option you have a one-way data flow.
When declaring the ‘attribute’ option (attrOut=attrIn) you have a similar two-way behavior as we currently have.

#### Questions
Dose this accommodate all usecases?
Why the current code takes in account if the component is connected or not?
Was this done to prevent DOM mutation when not connected?
Are there side effects from polyfills or native that requires that we do NOT synchronize prop to attribute until the Component has been inserted into the DOM?

**Comment by treshugart** [comment]
> Each time the value of attribute described by attrIn option changed/was removed, this is deserialized and set to the prop. Since prop value was set from attrIn, its value will NOT be reflected to attrOut.

If `attrOut` is specified, wouldn't you want to remove it?

> Dose this accommodate all usecases?

Yep, it seems to be backward compatible as well as allow for one-way (either way) or both ways.

> Why the current code takes in account if the component is connected or not? Was this done to prevent DOM mutation when not connected? Are there side effects from polyfills or native that requires that we do NOT synchronize prop to attribute until the Component has been inserted into the DOM?

The v1 spec doesn't allow you to set attributes in `constructor`; it will `throw`. The mutation aspect of it was secondary, even though attribute sets are 3 times slower than props sets. Unfortunately we'll have to keep this behaviour.

### Possible simplification to API

I'd like to propose we don't actually add options here, but just add a value that `attribute` can take:

```js
// boolean (my-prop)
myProp: { attribute: true }

// string (same as bool)
myProp: { attribute: 'my-prop' }

// two-way (same as string, bool)
myProp: {
  attribute: {
    source: 'my-prop',
    target: 'my-prop'
  }
}

// one-way (attr -> prop)
myProp: {
  attribute: { source: 'my-prop }
}

// one-way (prop -> attr)
myProp: {
  attribute: { target: 'my-prop' }
}
```

In that I've also proposed an alteration to the naming of the options. Instead of `in` / `out`, I'm proposing `source` / `target` to follow a similar naming convention as the native DOM in certain places. I also think it's a little bit more clear when specified as options to `attribute`.

**Comment by andreawyss** [comment]
I like your proposed API with attribute 'source' and 'target'.
I will start work on it after I'm done with #942

**Comment by treshugart** [comment]
Stooooked! Very happy to have this in. Thanks everyone for weighing in :)

**Comment by marcoms** [comment]
Sorry for raising this late in the discussion but would we also want to rename `attribute` -> `attr` to match the shortened `prop` naming we currently have? (Original issue is #720)

**Comment by treshugart** [comment]
@marcoms can you raise an issue and label it as "breaking" please?
