### ISSUE TITLE
Remove changelog as it duplicates the GitHub Release functionality

### ISSUE THREAD

**Issue by borisding1994** [skatejs/skatejs#881]

**Comment by treshugart** [comment]
Hey @borisding1994, sorry about the out-of-sync changelog. It should have been being updated by semantic-release, I thought. Since that doesn't seem to be the case, I think we might just delete it as it would be identical to the GitHub releases anyways and keeping it in sync, whichever way we choose, causes more work for us for the same thing the releases gives us.

In particular, is there anything you need to know?
