### ISSUE TITLE
Add FlowType and Comments to the code

### ISSUE THREAD

**Issue by andreawyss** [skatejs/skatejs#918]
Adding FlowType and Comments to the code will it make it easier for other to understand the code and contribute to it.

**Comment by Hotell** [comment]
honestly I would prefer migration to Typescript. Mature ecosystem etc. But definitely at least adding JSDoc would make the code more understandable

**Comment by treshugart** [comment]
I'd prefer to stay in JS proper, but don't oppose definitions for those JS
supersets. Easier to maintain in the long run. Imagine if Skate was written
in CoffeeScript, for example.

I'm on the fence about JSDoc. I feel that if the code isn't self
documenting, a redactor can help that. Doc comments become out of sync very
easily and I feel should only be used as a last resort. Clean Code has some
good info about this.

I'm definitely open to PRs to address readability and flowtype support.

**Comment by Hotell** [comment]
You right about JSDoc and stuff. About Typescript that is whole different story. I don't know why people tend to think that Typescript is different language. It's just javascript, but ofc it's your call in this one :) 

P.S.: also gradual migration by hybrid .js/.ts files is super simple with TS

**Comment by pyros2097** [comment]
Yeah I generally prefer typescript and all my projects are written in typescript and that is mainly for safety and those random undefined errors when you forget the return the promise in js.
But one good thing about js is that I can directly import the code into my html file and test it out. I don't think I even need webpack in this case and everything works out of the box and very easy to get started right away. And maybe in the way future we won't need anymore webpacks, module bundlers and babel and react and anyone can just start coding apps directly.

**Comment by treshugart** [comment]
It feels like TypeScript is to Flow as Webpack is to Gulp. It's definitely something I really like about TypeScript: less build config. I'm open to a (possibly gradual) rewrite to Flow / TS. I don't have a preference right now, but definitely see a need for type checking as the project team grows. My biggest question is can we support both no matter which one we choose without much, if any, extra effort?

**Comment by pyros2097** [comment]
I actually switched from js to flow before. And ran it some problems with flow like installing it, then settting up my project with it. It had a lot of configuration required which wasn't easy. Like I had this depdency fbjs and flow would throw an error on it and not type check my code because that project had a flow compile error (since my flow version and their flow version was different) so I had to ignore it in my flowconfig and flow is more optional in type checking. So I just decided to switch to typescript and it made things easier. And by then typescript 2.0 rolled out which removed the dependency on DefinitelyTyped and we could now add the typedefinitions directly from npmjs using the @types/repo path and the tsc compiler worked without a lot a setup like before.

Support for both is possible till some extent I guess because flow types are almost exactly like typescript types. And now you can event generate flow type definitions .js.flow from typescript type definitions .ts.d.
https://github.com/facebook/flow/issues/7
https://github.com/joarwilk/typedef-converter

**Comment by bsr203** [comment]
+1 for staying with javascript, with flow annotation. flow improved a lot recently, and I think it support incremental adoption and easier setup.

**Comment by treshugart** [comment]
@bsr203 see #931 for discussion around this. TypeScript might be a better fit, but your input in the context of that might be helpful.

**Comment by andreawyss** [comment]
I'm closing this issue since the consensus at this point seams to be a progressive migration to TypeScript.
