### ISSUE TITLE
Setting same prop value schedules a render cycle

### ISSUE THREAD

**Issue by andreawyss** [skatejs/skatejs#945]
If the new value being set is the same as the current one it seams unnecessary to schedule a render cycle: updatedCallback, renderCallback, renderedCallback.

**Comment by treshugart** [comment]
The updated callback should prevent that https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L272. Unless of course your talking about two different object instances which fail `===` but have the same structure. That's currently [expected behaviour](https://github.com/skatejs/skatejs#updatedcallback---supersedes-static-updated).

**Comment by andreawyss** [comment]
I agree that the default implementation of updatedCallback will stop the render cycle but one could have done the === test in the setter and not even scheduled the cycle in the first place.

In #928 you are thinking about redirect the user to no longer use the 'set' option but use the updatedCallback.  **updated**Callback implies something has **changed**.

If the user needs to know when the setter is called they would still be able to use the 'set' option but their updatedCallback implementation which in most cases will then call super.updatedCallback should be invoked only if something actually changed.

We could also consider adding and 'equals' or 'same' option to the property config to allow overriding the default identity equality.
Maybe in some scenarios one needs NaN === NaN to be true.

**Comment by treshugart** [comment]
The equality checking currently happens in the `updatedCallback()`, so I'd prefer to keep it there. Maybe it's worth eventually splitting that out into `shouldUpdateCallback()` and `updatedCallback()`.

Moving forward, I'd like to start placing callbacks on the component prototype instead of in prop defs for a couple reasons:

- Props can require other props. If you do this in the setter, you're relying on ordering. In the callbacks, you can be sure it's called in batches.
- Generally when specifying logic in callbacks, you're doing it for that particular component. Doing it in the prototype makes it easier to extend. If you do this in props there's some indirection that happens. Props are generally more abstract in functionality.

**Comment by treshugart** [comment]
I assume that we can close this for now as currently the `updatedCallback()` is called when a component is updated and returns whether or not it should render. I'll raise an issue to RFC separating these out. Please reopen if you think this needs more discussion here.
