### ISSUE TITLE
Split up updatedCallback()

### ISSUE THREAD

**Issue by treshugart** [skatejs/skatejs#949]
References #945.

To better serve a single responsibility, we should consider splitting up the `updatedCallback()` into two parts:

- `shouldUpdateCallback()` that returns whether or not the component should update (same as React)
- `updatedCallback()` that is called if `shouldUpdateCallback()` returns `true`, and is called before `render()`

*This is a BREAKING CHANGE as you'd be moving the return value for updating from `updatedCallback()` to `shouldUpdateCallback()`. This is a minor breakage because unless someone has overridden the default `updatedCallback()`, it will be transparent to them.*

**Comment by Hotell** [comment]
I would maybe slightly change naming to:
`shouldUpdateCallback`
`updatedCallback` -> `willUpdateCallback`

updatedCallback sounds confusing to me ( like what is this doing, it's calling this LCHook when it's updated ? `will` verb is more explicitly saying in what situation it will be called )

as for https://github.com/skatejs/skatejs/issues/916

it will have React counterparts like this:

**shouldUpdateCallback** ->
- componentWillReceiveProps()
- shouldComponentUpdate()

**willUpdateCallback** ->
- componentWillUpdate()

WDYT?

**Comment by andreawyss** [comment]
In skate we talk about 'render' cycle and not an 'update' cycle
```
   shouldRenderCallback
 
   willRenderCallback
   renderCallBack
   didRenderCallback (renderedCallback)
```

Still not really sure why we need to split this.
What kind of code we expect users to write in willRenderCallback?

I have a usecase where I don't want to use a shadowRoot and I do my rendering with innerHTML inside the current updatedCallback like this:
```
updatedCallback(prevProps) {
        // Using idom when rendering a svg fails silently.
        // The output looks good but does not render the paths!?
        if (!prevProps || prevProps.name !== this.name || prevProps.size !== this.size) {
            this.innerHTML = `<svg viewBox="0 0 24 24" width="${this.size}" height="${this.size}">${icons[this.name]}</svg>`;
        }
        return false;
}
```

**Comment by andreawyss** [comment]
@treshugart
Should updatedCallback execute when the component is disconnected?

React cycle is completely independent of the DOM.  
Current Web Component specs specify different behavior between connected vs disconnected.

To solve this issue on could proxy getAttribute and setAttribute to store attribute values internally and reflect these externally only on connectedCallback.

This could greatly simplify the component code since at any time one could write aria attributes and reflect prop values to attributes while not yet connected or while disconnected again.
On connectedCallback the attributeProxies would just reflect the internal state to the native attributes values.

This should also then solve issue #847

**Comment by Hotell** [comment]
> React cycle is completely independent of the DOM.
this is very falsy statement, for instance componentDidMount et all are triggered only if ReactDOM is used etc

**Comment by treshugart** [comment]
Related to #928.

**Comment by treshugart** [comment]
Done in referenced PR above.
