### ISSUE TITLE
Consider overwriting rendererCallback to customize rendering and re-export incrementalDOM

### ISSUE THREAD

**Issue by Qiu-Kejian** [skatejs/skatejs#980]
I have been trying implement a hierarchical custom elements that render into a svg.
e.g. 

```
>   <x-host>
>        <x-item></x-item>
>        <x-item></x-item>
>    </x-host>
```

x-host goes to svg, and x-item goes to a sub element of svg.

In this case, it seems I can not use the slot thing.
So .. that's where i am, trying to override rendererCallback.

In x-host, the rendererCallback does the same as supper.rendererCallback,
renders a svg element in shadowDom,
but also recording a $lastRenderedNode property referencing to svg.

But in x-item, it first get its parent, or prev sibling's lastRenderedNode, then render accordingly.
Therefore pathOuter, skipNode of IncrementalDOM could be useful.

Because skatejs does not re-export IncrementalDOM,
Now, I am trying to use skatejs umd version which is without deps.

Welcome for comment.

**Comment by treshugart** [comment]
Hey @Qiu-Kejian, you closed this without any activity. Did you find what you were looking for? It's currently an undocumented dark-feature, so likely to change in a breaking way without notice, but you can currently do something like this: http://www.webpackbin.com/Vk07dUF7G. That uses Preact as a renderer instead of Incremental DOM.
